### ISSUE TITLE
Not support links with 302 redirect 

### ISSUE THREAD

**Issue by chameleonTK** [huggingface/datasets#1064]
I have an issue adding this download link https://github.com/jitkapat/thailitcorpus/releases/download/v.2.0/tlc_v.2.0.tar.gz

it might be because it is not a direct link (it returns 302 and redirects to aws that returns 403 for head requests). 

```
r.head("https://github.com/jitkapat/thailitcorpus/releases/download/v.2.0/tlc_v.2.0.tar.gz", allow_redirects=True)                                      
# <Response [403]>
```

**Comment by lhoestq** [comment]
Hi !
This kind of links is now supported by the library since #1316

**Comment by chameleonTK** [comment]
> Hi !
> This kind of links is now supported by the library since #1316

I updated links in TLC datasets to be the github links in this pull request 
 https://github.com/huggingface/datasets/pull/1737

Everything works now. Thank you.
