### ISSUE TITLE
Incorrect URL for MRQA SQuAD train subset

### ISSUE THREAD

**Issue by jimmycode** [huggingface/datasets#1115]
https://github.com/huggingface/datasets/blob/4ef4c8f8b7a60e35c6fa21115fca9faae91c9f74/datasets/mrqa/mrqa.py#L53

The URL for `train+SQuAD` subset of MRQA points to the dev set instead of train set. It should be `https://s3.us-east-2.amazonaws.com/mrqa/release/v2/train/SQuAD.jsonl.gz`.

**Comment by lhoestq** [comment]
good catch !
