### ISSUE TITLE
can't load "german_legal_entity_recognition" dataset

### ISSUE THREAD

**Issue by nataly-obr** [huggingface/datasets#1299]
FileNotFoundError: Couldn't find file locally at german_legal_entity_recognition/german_legal_entity_recognition.py, or remotely at https://raw.githubusercontent.com/huggingface/datasets/1.1.3/datasets/german_legal_entity_recognition/german_legal_entity_recognition.py or https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/german_legal_entity_recognition/german_legal_entity_recognition.py

**Comment by darshan-gandhi** [comment]
Please if you could tell me more about the error? 

1. Please check the directory you've been working on
2. Check for any typos

**Comment by nataly-obr** [comment]
> Please if you could tell me more about the error?
> 
> 1. Please check the directory you've been working on
> 2. Check for any typos

Error happens during the execution of this line:
dataset = load_dataset("german_legal_entity_recognition")

Also, when I try to open mentioned links via Opera I have errors "404: Not Found" and "This XML file does not appear to have any style information associated with it. The document tree is shown below." respectively.

**Comment by sadakmed** [comment]
I have the same problem, not all datasets are available, some of them has been removed or something,

**Comment by SBrandeis** [comment]
Hello @nataly-obr, the `german_legal_entity_recognition` dataset has not yet been released (it is part of the coming soon v2 release).

You can still access it now if you want, but you will need to install `datasets` via the master branch:
`pip install git+https://github.com/huggingface/datasets.git@master`

Please let me know if it solves the issue :)
