### ISSUE TITLE
[Feature Request] Add the OpenWebText dataset

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/datasets#132]
The OpenWebText dataset is an open clone of OpenAI's WebText dataset. It can be used to train ELECTRA as is specified in the [README](https://www.github.com/google-research/electra).

More information and the download link are available [here](https://skylion007.github.io/OpenWebTextCorpus/).

**Comment by vanyacohen** [comment]
We're experimenting with hosting the OpenWebText corpus on Zenodo for easier downloading. https://zenodo.org/record/3834942#.Xs1w8i-z2J8

**Comment by lhoestq** [comment]
Closing since it's been added in #660
