### ISSUE TITLE
SNLI dataset contains labels with value -1

### ISSUE THREAD

**Issue by aarnetalman** [huggingface/datasets#1452]
```
import datasets
nli_data = datasets.load_dataset("snli")
train_data = nli_data['train']
train_labels = train_data['label']
label_set = set(train_labels)
print(label_set)
```

**Output:**
`{0, 1, 2, -1}`

**Comment by vineeths96** [comment]
I believe the `-1` label is used for missing/NULL data as per HuggingFace Dataset conventions. If I recall correctly SNLI has some entries with no (gold) labels in the dataset.

**Comment by aarnetalman** [comment]
Ah, you're right. The dataset has some pairs with missing labels. Thanks for reminding me.
