### ISSUE TITLE
Add helper to resolve namespace collision

### ISSUE THREAD

**Issue by jramapuram** [huggingface/datasets#1590]
Many projects use a module called `datasets`, however this is incompatible with huggingface datasets. It would be great if there if there was some helper or similar function to resolve such a common conflict.

**Comment by thomwolf** [comment]
Do you have an example?

**Comment by jramapuram** [comment]
I was thinking about using something like [importlib](https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly) to over-ride the collision. 

**Reason requested**: I use the [following template](https://github.com/jramapuram/ml_base/) repo where I house all my datasets as a submodule.

**Comment by jramapuram** [comment]
Alternatively huggingface could consider some submodule type structure like:

`import huggingface.datasets`
`import huggingface.transformers`

`datasets` is a very common module in ML and should be an end-user decision and not scope all of python ¯\_(ツ)_/¯

**Comment by thomwolf** [comment]
That's a interestign option indeed. We'll think about it.

**Comment by david-waterworth** [comment]
It also wasn't initially obvious to me that the samples which contain `import datasets` were in fact importing a huggingface library (in fact all the huggingface imports are very generic - transformers, tokenizers, datasets...)
