### ISSUE TITLE
Can't filter language:EN on https://huggingface.co/datasets

### ISSUE THREAD

**Issue by davidefiocco** [huggingface/datasets#1618]
When visiting https://huggingface.co/datasets, I don't see an obvious way to filter only English datasets. This is unexpected for me, am I missing something? I'd expect English to be selectable in the language widget. This problem reproduced on Mozilla Firefox and MS Edge:

![screenshot](https://user-images.githubusercontent.com/4547987/102792244-892e1f00-43a8-11eb-9e89-4826ca201a87.png)

**Comment by julien-c** [comment]
cc'ing @mapmeld

**Comment by mapmeld** [comment]
Full language list is now deployed to https://huggingface.co/datasets ! Recommend close

**Comment by davidefiocco** [comment]
Cool @mapmeld ! My 2 cents (for a next iteration), it would be cool to have a small search widget as you have a ton of languages now here! Closing this in the meantime.
