### ISSUE TITLE
Can't call shape on the output of select()

### ISSUE THREAD

**Issue by noaonoszko** [huggingface/datasets#1622]
I get the error `TypeError: tuple expected at most 1 argument, got 2` when calling `shape` on the output of `select()`.
It's line 531 in shape in arrow_dataset.py that causes the problem:
``return tuple(self._indices.num_rows, self._data.num_columns)``
This makes sense, since `tuple(num1, num2)` is not a valid call.
 
Full code to reproduce:

```python
dataset = load_dataset("cnn_dailymail", "3.0.0")
train_set = dataset["train"]
t = train_set.select(range(10))
print(t.shape)

**Comment by thomwolf** [comment]
Indeed that's a typo, do you want to open a PR to fix it?

**Comment by noaonoszko** [comment]
Yes, created a PR
