### ISSUE TITLE
`Dataset.map` disable progress bar

### ISSUE THREAD

**Issue by Nickil21** [huggingface/datasets#1627]
I can't find anything to turn off the `tqdm` progress bars while running a preprocessing function using `Dataset.map`. I want to do akin to `disable_tqdm=True` in the case of `transformers`. Is there something like that?

**Comment by Nickil21** [comment]
Any updates so far?

**Comment by mariosasko** [comment]
Progress bar can be disabled like this:
```python
from datasets.utils.logging import set_verbosity_error
set_verbosity_error()
```

There is this line in `Dataset.map`:
```python
not_verbose = bool(logger.getEffectiveLevel() > WARNING)
```

So any logging level higher than `WARNING` turns off the progress bar.

**Comment by akeyhero** [comment]
From linked issues above, up to date solution is:

```python
from datasets.utils.logging import disable_progress_bar
disable_progress_bar()
```

**Comment by brynhayder** [comment]
Why not have a parameter in the function such as `progress: bool = True`?

**Comment by ACMCMC** [comment]
+1. We shouldn't need to play with logging levels for a simple thing like this. For instance, trainers have an option `show_progress` that does exactly this.

**Comment by pb-sameereddy** [comment]
Bump on this, such a simple QOL issue why can't we fix this?
