### ISSUE TITLE
Inspecting datasets per category

### ISSUE THREAD

**Issue by ghost** [huggingface/datasets#1634]
Hi
Is there a way I could get all NLI datasets/all QA datasets to get some understanding of available datasets per category? this is hard for me to inspect the datasets one by one in the webpage, thanks for the suggestions @lhoestq

**Comment by thomwolf** [comment]
That's interesting, can you tell me what you think would be useful to access to inspect a dataset?

You can filter them in the hub with the search by the way: https://huggingface.co/datasets have you seen it?

**Comment by juliahane** [comment]
Hi @thomwolf 
thank you, I was not aware of this, I was looking into the data viewer linked into readme page. 

This as what I am looking for, but  this does not work currently, please see the attached 
![5tarDHn9CP6ngeM](https://user-images.githubusercontent.com/53898419/103107612-1509aa80-4638-11eb-85b5-0c995a189969.png)

I am selecting to see all nli datasets in english and it retrieves none. thanks

**Comment by thomwolf** [comment]
I see 4 results for NLI in English but indeed some are not tagged yet and missing (GLUE), we will focus on that in January (cc @yjernite): https://huggingface.co/datasets?filter=task_ids:natural-language-inference,languages:en

**Comment by Eliotmasters** [comment]
￼Good night my friend￼ I'm sorry, I don't understand you, it's my first time
