### ISSUE TITLE
Unable to Download Hindi Wikipedia Dataset

### ISSUE THREAD

**Issue by aditya3498** [huggingface/datasets#1673]
I used the Dataset Library in Python to load the wikipedia dataset with the Hindi Config 20200501.hi along with something called beam_runner='DirectRunner' and it keeps giving me the error that the file is not found. I have attached the screenshot of the error and the code both. Please help me to understand how to resolve this issue.

![Code](https://user-images.githubusercontent.com/30871963/103437466-1f3a3300-4c4e-11eb-9d54-fc9601abfeec.png)

![Error](https://user-images.githubusercontent.com/30871963/103437407-7ee40e80-4c4d-11eb-8151-a86eb664e6be.png)

**Comment by thomwolf** [comment]
Currently this dataset is only available when the library is installed from source since it was added after the last release.

We pin the dataset version with the library version so that people can have a reproducible dataset and processing when pinning the library.

We'll see if we can provide access to newer datasets with a warning that they are newer than your library version, that would help in cases like yours.

**Comment by aditya3498** [comment]
So for now, should i try and install the library from source and then try out the same piece of code? Will it work then, considering both the versions will match then?

**Comment by thomwolf** [comment]
Yes

**Comment by aditya3498** [comment]
Hey, so i tried installing the library from source using the commands : **git clone https://github.com/huggingface/datasets**,  **cd datasets** and then **pip3 install -e .**. But i still am facing the same error that file is not found. Please advise

![Error](https://user-images.githubusercontent.com/30871963/103479005-69f3b080-4df0-11eb-83ae-58d7bb56a90e.png)

**Comment by lhoestq** [comment]
Looks like the wikipedia dump for hindi at the date of 05/05/2020 is not available anymore.
You can try to load an earlier version of wikipedia
```python
from datasets import load_dataset

d = load_dataset("wikipedia", language="hi", date="20210101", split="train", beam_runner="DirectRunner")
```

**Comment by aditya3498** [comment]
Okay, thank you so much
