### ISSUE TITLE
Installation using conda

### ISSUE THREAD

**Issue by pranav-s** [huggingface/datasets#1713]
Will a conda package for installing datasets be added to the huggingface conda channel? I have installed transformers using conda and would like to use the datasets library to use some of the scripts in the transformers/examples folder but am unable to do so at the moment as datasets can only be installed using pip and using pip in a conda environment is generally a bad idea in my experience.

**Comment by thomwolf** [comment]
Yes indeed the idea is to have the next release on conda cc @LysandreJik

**Comment by pranav-s** [comment]
Great! Did you guys have a timeframe in mind for the next release?

Thank you for all the great work in developing this library.

**Comment by LysandreJik** [comment]
I think we can have `datasets` on conda by next week. Will see what I can do!

**Comment by pranav-s** [comment]
Thank you. Looking forward to it.

**Comment by lhoestq** [comment]
`datasets` has been added to conda-forge thanks to @LysandreJik :)

```
conda install -c huggingface -c conda-forge datasets
```
