### ISSUE TITLE
Couldn't reach swda.py

### ISSUE THREAD

**Issue by yangp725** [huggingface/datasets#1731]
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/1.2.0/datasets/swda/swda.py

**Comment by SBrandeis** [comment]
Hi @yangp725,
The SWDA has been added very recently and has not been released yet, thus it is not available in the `1.2.0` version of 🤗`datasets`.
You can still access it by installing the latest version of the library (master branch), by following instructions in [this issue](https://github.com/huggingface/datasets/issues/1641#issuecomment-751571471).
Let me know if this helps !

**Comment by yangp725** [comment]
Thanks @SBrandeis ,
Problem solved by downloading and installing the latest version datasets.
