### ISSUE TITLE
connection issue with glue, what is the data url for glue? 

### ISSUE THREAD

**Issue by ghost** [huggingface/datasets#1733]
Hi
my codes sometimes fails due to connection issue with glue, could you tell me how I can have the URL datasets library is trying to read GLUE from to test the machines I am working on if there is an issue on my side or not
thanks

**Comment by SBrandeis** [comment]
Hello @juliahane, which config of GLUE causes you trouble?
The URLs are defined in the dataset script source code: https://github.com/huggingface/datasets/blob/master/datasets/glue/glue.py
