### ISSUE TITLE
datasets slicing with seed 

### ISSUE THREAD

**Issue by ghost** [huggingface/datasets#1747]
Hi
I need to slice a dataset with random seed, I looked into documentation here https://huggingface.co/docs/datasets/splits.html 
I could not find a seed option, could you assist me please how I can get a slice for different seeds?
thank you.
@lhoestq

**Comment by lhoestq** [comment]
Hi :) 
The slicing API doesn't shuffle the data.
You can shuffle and then take a subset of your dataset with
```python
# shuffle and take the first 100 examples
dataset = dataset.shuffle(seed=42).select(range(100))
```

You can find more information about shuffling and selecting rows in the documentation: https://huggingface.co/docs/datasets/processing.html#selecting-sorting-shuffling-splitting-rows

**Comment by juliahane** [comment]
thank you so much
