### ISSUE TITLE
FewRel

### ISSUE THREAD

**Issue by dspoka** [huggingface/datasets#1757]
## Adding a Dataset
- **Name:** FewRel
- **Description:**  Large-Scale Supervised Few-Shot Relation Classification Dataset
- **Paper:** @inproceedings{han2018fewrel,
               title={FewRel:A Large-Scale Supervised Few-Shot Relation Classification Dataset with State-of-the-Art Evaluation},
               author={Han, Xu and Zhu, Hao and Yu, Pengfei and Wang, Ziyun and Yao, Yuan and Liu, Zhiyuan and Sun, Maosong},
               booktitle={EMNLP},
               year={2018}}
- **Data:** https://github.com/ProKil/FewRel
- **Motivation:** relationship extraction dataset that's been used by some state of the art systems that should be incorporated.

Instructions to add a new dataset can be found [here](https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md).

**Comment by ChrisChross** [comment]
+1

**Comment by gchhablani** [comment]
@dspoka Please check the following link : https://github.com/thunlp/FewRel
This link mentions two versions of the datasets. Would you know what's the difference in the datasets between the link you sent and this link?

**Comment by gchhablani** [comment]
Hi @lhoestq,

This issue can be closed, I guess.

**Comment by dspoka** [comment]
Thanks for adding this @gchhablani ! Sorry didn't see the email notifications sooner!
