### ISSUE TITLE
wikipedia dataset incomplete

### ISSUE THREAD

**Issue by ChrisChross** [huggingface/datasets#1759]
Hey guys,

I am using the https://github.com/huggingface/datasets/tree/master/datasets/wikipedia dataset.
Unfortunately, I found out that there is an incompleteness for the German dataset.
 For reasons unknown to me, the number of inhabitants has been removed from many pages:
Thorey-sur-Ouche has 128 inhabitants according to the webpage (https://de.wikipedia.org/wiki/Thorey-sur-Ouche).
The pickle file however shows: französische Gemeinde mit  Einwohnern (Stand).
 Is it possible to fix this?

Best regards 
Chris

**Comment by lhoestq** [comment]
Hi !
From what pickle file fo you get this ?
I guess you mean the dataset loaded using `load_dataset` ?

**Comment by ChrisChross** [comment]
yes sorry, I mean `load_dataset` ofc.

**Comment by lhoestq** [comment]
The wikipedia articles are processed using the `mwparserfromhell` library. Even if it works well in most cases, such issues can happen unfortunately. You can find the repo here: https://github.com/earwig/mwparserfromhell

There also exist other datasets based on wikipedia that were processed differently (and are often cleaner) such as `wiki40b`.

**Comment by ChrisChross** [comment]
ok great. Thank you, @lhoestq.
