### ISSUE TITLE
Unable to format dataset to CUDA Tensors

### ISSUE THREAD

**Issue by gchhablani** [huggingface/datasets#1762]
Hi,

I came across this [link](https://huggingface.co/docs/datasets/torch_tensorflow.html) where the docs show show to convert a dataset to a particular format. I see that there is an option to convert it to tensors, but I don't see any option to convert it to CUDA tensors.

I tried this, but Dataset doesn't support assignment:
```
  columns=['input_ids', 'token_type_ids', 'attention_mask', 'start_positions','end_positions']

        samples.set_format(type='torch', columns = columns)
        for column in columns:
            samples[column].to(torch.device(self.config.device))
```
There should be an option to do so, or if there is already a way to do this, please let me know.

Thanks,
Gunjan

**Comment by gchhablani** [comment]
Hi @lhoestq,

Thanks a lot. Is this true for all format types?

As in, for 'torch', I can have `**kwargs` to `torch.tensor` and for 'tf' those args are passed to `tf.Tensor`, and the same for 'numpy' and 'pandas'?

**Comment by lhoestq** [comment]
Yes the keywords arguments are passed to the convert function like `np.array`, `torch.tensor` or `tensorflow.ragged.constant`.
We don't support the kwargs for pandas on the other hand.

**Comment by gchhablani** [comment]
Thanks @lhoestq,
Would it be okay if I added this to the docs and made a PR?

**Comment by lhoestq** [comment]
Sure ! Feel free to open a PR to improve the documentation :)

**Comment by gchhablani** [comment]
Closing this issue as it has been resolved.

**Comment by ai-nikolai** [comment]
@lhoestq 

Hi,

I tried the above with 4.5.0, but this seems to not work anymore..
