### ISSUE TITLE
is it possible to make slice to be more compatible like python list and numpy?

### ISSUE THREAD

**Issue by world2vec** [huggingface/datasets#1774]
Hi,
see below error:
```
AssertionError: Requested slice [:10000000000000000] incompatible with 20 examples.
```

**Comment by lhoestq** [comment]
Hi ! Thanks for reporting.
I am working on changes in the way data are sliced from arrow. I can probably fix your issue with the changes I'm doing.
If you have some code to reproduce the issue it would be nice so I can make sure that this case will be supported :)
I'll make a PR in a few days

**Comment by world2vec** [comment]
Good if you can take care at your side.
Here is the [colab notebook](https://colab.research.google.com/drive/19c-abm87RTRYgW9G1D8ktfwRW95zDYBZ?usp=sharing)
