### ISSUE TITLE
[Question & Bug Report] Can we preprocess a dataset on the fly?

### ISSUE THREAD

**Issue by shuaihuaiyi** [huggingface/datasets#1776]
I know we can use `Datasets.map` to preprocess a dataset, but I'm using it with very large corpus which generates huge cache file (several TB cache from a 400 GB text file). I have no disk large enough to save it.  Can we preprocess a dataset on the fly without generating cache?

BTW, I tried raising `writer_batch_size`. Seems that argument doesn't have any effect when it's larger than `batch_size`, because you are saving all the batch instantly after it's processed. Please check the following code:

https://github.com/huggingface/datasets/blob/0281f9d881f3a55c89aeaa642f1ba23444b64083/src/datasets/arrow_dataset.py#L1532

**Comment by thomwolf** [comment]
We are very actively working on this. How does your dataset look like in practice (number/size/type of files)?

**Comment by shuaihuaiyi** [comment]
It's a text file with many lines (about 1B) of Chinese sentences. I use it to train language model using https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_mlm_wwm.py

**Comment by lhoestq** [comment]
Indeed I will submit a PR in a fez days to enable processing on-the-fly :)
This can be useful in language modeling for tokenization, padding etc.

**Comment by acul3** [comment]
any update on this issue? ...really look forward to use it

**Comment by gchhablani** [comment]
Hi @acul3,

Please look at the discussion at the related Issue #1825. I think using `set_transform` after building from source should do.

**Comment by acul3** [comment]
@gchhablani thank you so much

will try look at it
