### ISSUE TITLE
AttributeError: module 'pyarrow' has no attribute 'PyExtensionType' during import 

### ISSUE THREAD

**Issue by PalaashAgrawal** [huggingface/datasets#1781]
I'm using Colab. And suddenly this morning, there is this error. Have a look below!

![screenshot-colab research google com-2021 01 26-08-15-36](https://user-images.githubusercontent.com/45964869/105799890-fdaf3b80-5fae-11eb-8f06-11b65cdccc30.png)

**Comment by lhoestq** [comment]
Hi ! I'm not able to reproduce the issue. Can you try restarting your runtime ?

The PyExtensionType is available in pyarrow starting 0.17.1 iirc. If restarting your runtime doesn't fix this, can you try updating pyarrow ?
```
pip install pyarrow --upgrade
```

**Comment by thomwolf** [comment]
We should bump up the version test of pyarrow maybe no?

https://github.com/huggingface/datasets/blob/master/src/datasets/__init__.py#L60

**Comment by lhoestq** [comment]
Yes indeed.

Also it looks like Pyarrow 3.0.0 got released on pypi 10 hours ago. This might be related to the bug, I'll investigate

**Comment by thomwolf** [comment]
Maybe colab moved to pyarrow 0.16 by default (instead of 0.14 before)?

**Comment by lhoestq** [comment]
Installing datasets installs pyarrow>=0.17.1 so in theory it doesn't matter which version of pyarrow colab has by default (which is currently pyarrow 0.14.1).

Also now the colab runtime refresh the pyarrow version automatically after the update from pip (previously you needed to restart your runtime).

I guess what happened is that Colab didn't refresh pyarrow for some reason, and the AttributeError was raised *before* the pyarrow version check from `datasets` at https://github.com/huggingface/datasets/blob/master/src/datasets/__init__.py#L60

**Comment by thomwolf** [comment]
Yes colab doesn’t reload preloaded library unless you restart the instance. Maybe we should move the check on top of the init

**Comment by lhoestq** [comment]
Yes I'll do that :)

**Comment by lhoestq** [comment]
I updated the pyarrow version check in #1782

**Comment by sharaijaz** [comment]
restarting worked for me
> ```

yes it worked for me
