### ISSUE TITLE
test.json has been removed from the limit dataset repo (breaks dataset)

### ISSUE THREAD

**Issue by Paethon** [huggingface/datasets#1836]
https://github.com/huggingface/datasets/blob/16042b233dbff2a7585110134e969204c69322c3/datasets/limit/limit.py#L51

The URL is not valid anymore since test.json has been removed in master for some reason. Directly referencing the last commit works:

`https://raw.githubusercontent.com/ilmgut/limit_dataset/0707d3989cd8848f0f11527c77dcf168fefd2b23/data`

**Comment by lhoestq** [comment]
Thanks for the heads up ! I'm opening a PR to fix that
