### ISSUE TITLE
Add common voice

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/datasets#1840]
## Adding a Dataset
- **Name:** *common voice*
- **Description:** *Mozilla Common Voice Dataset*
- **Paper:** Homepage: https://voice.mozilla.org/en/datasets
- **Data:** https://voice.mozilla.org/en/datasets
- **Motivation:** Important speech dataset
- **TFDatasets Implementation**: https://www.tensorflow.org/datasets/catalog/common_voice
If interested in tackling this issue, feel free to tag @patrickvonplaten

Instructions to add a new dataset can be found [here](https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md).

**Comment by BirgerMoell** [comment]
I have started working on adding this dataset.

**Comment by patrickvonplaten** [comment]
Hey @BirgerMoell - awesome that you started working on Common Voice. Common Voice is a bit special since, there is no direct download link to download the data. In these cases we usually consider two options:

1) Find a hacky solution to extract the download link somehow from the XLM tree of the website 
2) If this doesn't work we force the user to download the data himself and add a `"data_dir"` as an input parameter. E.g. you can take a look at how it is done for [this](https://github.com/huggingface/datasets/blob/66f2a7eece98d2778bd22bb5034cb7c2376032d4/datasets/arxiv_dataset/arxiv_dataset.py#L66) 

Also the documentation here: https://huggingface.co/docs/datasets/add_dataset.html?highlight=data_dir#downloading-data-files-and-organizing-splits (especially the "note") might be helpful.

**Comment by patrickvonplaten** [comment]
Let me know if you have any other questions

**Comment by BirgerMoell** [comment]
I added a Work in Progress pull request (hope that is ok). I've made a card for the dataset and filled out the common_voice.py file with information about the datset (not completely).

I didn't manage to get the tagging tool working locally on my machine but will look into that later.

Left to do.

- Tag the dataset
- Add missing information and update common_voice.py

https://github.com/huggingface/datasets/pull/1886

**Comment by patrickvonplaten** [comment]
Awesome! I left a longer comment on the PR :-)

**Comment by bagustris** [comment]
I saw that this current datasets package holds common voice version 6.1, how to new add version 7.0 that is already available?

**Comment by patrickvonplaten** [comment]
Will me merged next week - we're working on it :-)

**Comment by pjbbuzz61** [comment]
Common voice still appears to be a 6.1. Is the plan still to upgrade to 7.0?

**Comment by patrickvonplaten** [comment]
We actually already have the code and everything ready to add Common Voice 7.0 to `datasets` but are still waiting for the common voice authors to give us the green light :-) 

Also gently pinging @phirework and @milupo here

**Comment by patrickvonplaten** [comment]
Common Voice 7.0 is available here now: https://huggingface.co/datasets/mozilla-foundation/common_voice_7_0

**Comment by bfelbo** [comment]
For anyone stumbling upon this thread, the 8.0 version is also available now: https://huggingface.co/datasets/mozilla-foundation/common_voice_8_0
