### ISSUE TITLE
request to mirror wmt datasets, as they are really slow to download

### ISSUE THREAD

**Issue by stas00** [huggingface/datasets#1892]
Would it be possible to mirror the wmt data files under hf? Some of them take hours to download and not because of the local speed. They are all quite small datasets, just extremely slow to download.

Thank you!

**Comment by lhoestq** [comment]
Yes that would be awesome. Not only the download speeds are awful, but also some files are missing.
We list all the URLs in the datasets/wmt19/wmt_utils.py so we can make a script to download them all and host on S3.
Also I think most of the materials are under the CC BY-NC-SA 3.0 license (must double check) so it should be possible to redistribute the data with no issues.

cc @patrickvonplaten who knows more about the wmt scripts

**Comment by patrickvonplaten** [comment]
Yeah, the scripts are pretty ugly! A big refactor would make sense here...and I also remember that the datasets were veeery slow to download

**Comment by lhoestq** [comment]
I'm downloading them.
I'm starting with the ones hosted on http://data.statmt.org which are the slowest ones

**Comment by julien-c** [comment]
@lhoestq better to use our new git-based system than just raw S3, no? (that way we have built-in CDN etc.)

**Comment by lhoestq** [comment]
Closing since the urls were changed to mirror urls in #1912
