### ISSUE TITLE
ALT dataset has repeating instances in all splits

### ISSUE THREAD

**Issue by 10-zin** [huggingface/datasets#1898]
The [ALT](https://huggingface.co/datasets/alt) dataset has all the same instances within each split :/
Seemed like a great dataset for some experiments I wanted to carry out, especially since its medium-sized, and has all splits.

Would be great if this could be fixed :)

Added a snapshot of the contents from `explore-datset` feature, for quick reference.

![image](https://user-images.githubusercontent.com/33179372/108206321-442a2d00-714c-11eb-882f-b4b6e708ef9c.png)

**Comment by lhoestq** [comment]
Thanks for reporting. This looks like a very bad issue. I'm looking into it

**Comment by lhoestq** [comment]
I just merged a fix, we'll do a patch release soon. Thanks again for reporting, and sorry for the inconvenience.
In the meantime you can load `ALT` using `datasets` from the master branch

**Comment by 10-zin** [comment]
Thanks!!! works perfectly in the bleading edge master version

**Comment by albertvillanova** [comment]
Closed by #1899
