### ISSUE TITLE
Failure to save with save_to_disk

### ISSUE THREAD

**Issue by M-Salti** [huggingface/datasets#1919]
When I try to save a dataset locally using the `save_to_disk` method I get the error:

```bash
FileNotFoundError: [Errno 2] No such file or directory: '/content/squad/train/squad-train.arrow'
```

To replicate:

1. Install `datasets` from master
2. Run this code:

    ```python
    from datasets import load_dataset
    squad = load_dataset("squad")   # or any other dataset
    squad.save_to_disk("squad")     # error here
    ```

The problem is that the method is not creating a directory with the name `dataset_path` for saving the dataset in (i.e. it's not creating the *train* and *validation* directories in this case). After creating the directory the problem resolves.
I'll open a PR soon doing that and linking this issue.

**Comment by lhoestq** [comment]
Hi thanks for reporting and for proposing a fix :)

I just merged a fix, feel free to try it from the master branch !
