### ISSUE TITLE
Anonymous Dataset Addition (i.e Anonymous PR?)

### ISSUE THREAD

**Issue by PierreColombo** [huggingface/datasets#1924]
Hello,
Thanks a lot for your librairy.
We plan to submit a paper on OpenReview using the Anonymous setting. Is it possible to add a new dataset without breaking the anonimity, with a link to the paper ? 
Cheers 
@eusip

**Comment by lhoestq** [comment]
Hi !
I guess you can add a dataset without links and then add the links when the anonymity period is over.
Pinging @yjernite just to make sure it's ok

**Comment by PierreColombo** [comment]
Hello,
I would prefer to do the reverse: adding a link to an anonymous paper without the people names/institution in the PR. Would it be conceivable ?
Cheers

**Comment by lhoestq** [comment]
Sure, I think it's ok

**Comment by yjernite** [comment]
Yup, sounds good!
