### ISSUE TITLE
CommonGen dataset page shows an error OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by yuchenlin** [huggingface/datasets#1937]
The page of the CommonGen data https://huggingface.co/datasets/viewer/?dataset=common_gen  shows 
![image](https://user-images.githubusercontent.com/10104354/108959311-1865e600-7629-11eb-868c-cf4cb27034ea.png)

**Comment by alexdor** [comment]
Facing the same issue for [Squad](https://huggingface.co/datasets/viewer/?dataset=squad) and [TriviaQA](https://huggingface.co/datasets/viewer/?dataset=trivia_qa) datasets as well.

**Comment by lhoestq** [comment]
We just fixed the issue, thanks for reporting !
