### ISSUE TITLE
add a new column 

### ISSUE THREAD

**Issue by dorost1234** [huggingface/datasets#1954]
Hi
I'd need to add a new column to the dataset, I was wondering how this can be done? thanks 
@lhoestq

**Comment by dorost1234** [comment]
Hi
not sure how change the lable after creation, but this is an issue not dataset request. thanks

**Comment by lhoestq** [comment]
Hi ! Currently you have to use `map` . You can see an example of how to do it in this comment: https://github.com/huggingface/datasets/issues/853#issuecomment-727872188

In the future we'll add support for a more native way of adding a new column ;)
