### ISSUE TITLE
Bug in skip_rows argument of load_dataset function ?

### ISSUE THREAD

**Issue by LedaguenelArthur** [huggingface/datasets#1959]
Hello everyone,

I'm quite new to Git so sorry in advance if I'm breaking some ground rules of issues posting... :/
I tried to use the load_dataset function, from Huggingface datasets library, on a csv file using the skip_rows argument described on Huggingface page to skip the first row containing column names

`test_dataset = load_dataset('csv', data_files=['test_wLabel.tsv'], delimiter='\t', column_names=["id", "sentence", "label"], skip_rows=1)`

But I got the following error message

`__init__() got an unexpected keyword argument 'skip_rows'`

Have I used the wrong argument ? Am I missing something or is this a bug ?

Thank you very much for your time,
Best regards,
Arthur

**Comment by mariosasko** [comment]
Hi,

try `skiprows` instead. This part is not properly documented in the docs it seems.
