### ISSUE TITLE
Readme.md is misleading about kinds of datasets?

### ISSUE THREAD

**Issue by surak** [huggingface/datasets#1988]
Hi!

At the README.MD, you say: "efficient data pre-processing: simple, fast and reproducible data pre-processing for the above public datasets as well as your own local datasets in CSV/JSON/text. "

But here:
https://github.com/huggingface/datasets/blob/master/templates/new_dataset_script.py#L82-L117

You mention other kinds of datasets, with images and so on. I'm confused. 

Is it possible to use it to store, say, imagenet locally?

**Comment by lhoestq** [comment]
Hi ! Yes it's possible to use image data. There are already a few of them available (MNIST, CIFAR..)
