### ISSUE TITLE
How to load a dataset with load_from disk and save it again after doing transformations without changing the original? 

### ISSUE THREAD

**Issue by shamanez** [huggingface/datasets#1993]
I am using the latest datasets library.  In my work, I first use **load_from_disk** to load a data set that contains 3.8Gb information. Then during my training process, I update that dataset object and add new elements and save it in a different place.  

When I save the dataset with **save_to_disk**, the original dataset which is already in the disk also gets updated. I do not want to update it.  How to prevent from this?

**Comment by lhoestq** [comment]
Hi ! That looks like a bug, can you provide some code so that we can reproduce ?
It's not supposed to update the original dataset

**Comment by shamanez** [comment]
Hi, I experimented with RAG. 

Actually, you can run the [use_own_knowldge_dataset.py](https://github.com/shamanez/transformers/blob/rag-end-to-end-retrieval/examples/research_projects/rag/use_own_knowledge_dataset.py#L80). In the 80 you can save the dataset object to the disk with save_to_disk. Then in order to compute the embeddings in this use **load_from_disk**. 

Then finally save it. You can see the original dataset object (CSV after splitting also will be changed)

One more thing- when I save the dataset object with **save_to_disk** it name the arrow file with cache.... rather than using dataset. arrow.  Can you add a variable that we can feed a name to save_to_disk function?

**Comment by shamanez** [comment]
@lhoestq   I also found that cache in tmp directory gets updated after transformations. This is really problematic when using datasets interactively. Let's say we use the shards function to a dataset loaded with csv, atm when we do transformations to shards and combine them it updates the original csv cache.

**Comment by lhoestq** [comment]
I plan to update the save_to_disk method in #2025 so I can make sure the new save_to_disk doesn't corrupt your cache files.
But from your last message it looks like save_to_disk isn't the root cause right ?

**Comment by shamanez** [comment]
ok, one more thing. When we use save_to_disk there are two files other than .arrow. dataset_info.json and state.json. Sometimes most of the fields in the dataset_infor.json are null, especially when saving dataset objects. Anyways I think load_from_disk uses the arrow files mentioned in state.json right?

**Comment by lhoestq** [comment]
> Anyways I think load_from_disk uses the arrow files mentioned in state.json right?

Yes exactly

**Comment by shamanez** [comment]
Perfect.  For now, I am loading the dataset from CSV in my interactive process and will wait until you make the PR!
