### ISSUE TITLE
Interactively doing  save_to_disk and load_from_disk corrupts the datasets object?

### ISSUE THREAD

**Issue by shamanez** [huggingface/datasets#2021]
dataset_info.json file saved after using  save_to_disk gets corrupted as follows. 
 
 
![image](https://user-images.githubusercontent.com/16892570/110568474-ed969880-81b7-11eb-832f-2e5129656016.png)

Is there a way to disable the cache that will save to /tmp/huggiface/datastes ? 
I have a feeling there is a serious issue with cashing.

**Comment by mariosasko** [comment]
Hi,

Can you give us a minimal reproducible example? This [part](https://huggingface.co/docs/datasets/master/processing.html#controling-the-cache-behavior) of the docs explains how to control caching.
