### ISSUE TITLE
Build custom dataset to fine-tune Wav2Vec2

### ISSUE THREAD

**Issue by Omarnabk** [huggingface/datasets#2050]
Thank you for your recent tutorial on how to finetune Wav2Vec2 on a custom dataset. The example you gave here (https://huggingface.co/blog/fine-tune-xlsr-wav2vec2) was on the CommonVoice dataset. However, what if I want to load my own dataset?  I have a manifest (transcript and their audio files) in a JSON file.

**Comment by patrickvonplaten** [comment]
@lhoestq - We could simply use the "general" json dataset for this no?

**Comment by lhoestq** [comment]
Sure you can use the json loader
```python
data_files = {"train": "path/to/your/train_data.json", "test": "path/to/your/test_data.json"}
train_dataset = load_dataset("json", data_files=data_files, split="train")
test_dataset = load_dataset("json", data_files=data_files, split="test")
```

You just need to make sure that the data contain the paths to the audio files.
If not, feel free to use `.map()` to add them.

**Comment by Omarnabk** [comment]
Many thanks! that was what I was looking for.
