### ISSUE TITLE
Is it possible to convert a `tfds` to HuggingFace `dataset`?

### ISSUE THREAD

**Issue by abarbosa94** [huggingface/datasets#2058]
I was having some weird bugs with `C4`dataset version of HuggingFace, so I decided to try to download `C4`from `tfds`. I would like to know if it is possible to convert a tfds dataset to HuggingFace dataset format :)

I can also open a new issue reporting the bug I'm receiving with `datasets.load_dataset('c4','en')` in the future if you think that it would be useful.

Thanks!

**Comment by mariosasko** [comment]
Hi! You can either save the TF dataset to one of the formats supported by datasets (`parquet`, `csv`, `json`, ...) or pass a generator function to `Dataset.from_generator` that yields its examples.
