### ISSUE TITLE
Remove test set from NLP viewer

### ISSUE THREAD

**Issue by chrisdonahue** [huggingface/datasets#207]
While the new [NLP viewer](https://huggingface.co/nlp/viewer/) is a great tool, I think it would be best to outright remove the option of looking at the test sets. At the very least, a warning should be displayed to users before showing the test set. Newcomers to the field might not be aware of best practices, and small things like this can help increase awareness.

**Comment by Mistobaan** [comment]
is the viewer also open source?

**Comment by chrisdonahue** [comment]
Appears that [two thirds of those polled on Twitter](https://twitter.com/srush_nlp/status/1265734497632477185) are in favor of some mechanism for averting eyeballs from the test data.

**Comment by albertvillanova** [comment]
We do no longer use datasets-viewer.
