### ISSUE TITLE
ConnectionError: Couldn't reach common_voice.py

### ISSUE THREAD

**Issue by LifaSun** [huggingface/datasets#2075]
When I run: 
from datasets import load_dataset, load_metric

common_voice_train = load_dataset("common_voice", "zh-CN", split="train+validation")
common_voice_test = load_dataset("common_voice", "zh-CN", split="test")

Got:
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/master/datasets/common_voice/common_voice.py

Version:
1.4.1

Thanks!  @lhoestq @LysandreJik @thomwolf

**Comment by albertvillanova** [comment]
Hi @LifaSun, thanks for reporting this issue.

Sometimes, GitHub has some connectivity problems. Could you confirm that the problem persists?

**Comment by LifaSun** [comment]
@albertvillanova Thanks! It works well now.
