### ISSUE TITLE
How to disable making arrow tables in load_dataset ?

### ISSUE THREAD

**Issue by Jeevesh8** [huggingface/datasets#2092]
Is there a way to disable the construction of arrow tables, or to make them on the fly as the dataset is being used ?

**Comment by lhoestq** [comment]
Hi ! We plan to add streaming features in the future.

This should allow to load a dataset instantaneously without generating the arrow table. The trade-off is that accessing examples from a streaming dataset must be done in an iterative way, and with an additional (but hopefully minor) overhead.
What do you think about this ?

If you have ideas or suggestions of what you expect from such features as a user, feel free to share them, this is really valuable to us !

**Comment by Jeevesh8** [comment]
People mainly want this feature either because it takes too much time too make arrow tables, or they occupy too much memory on the disk. I think both the problem can be solved if we provide arrow tables themselves on datasets hub. Can we do this currently @lhoestq ?

**Comment by Jeevesh8** [comment]
@lhoestq I think the ```try_from_hf_gcs``` provide the same functionality. What all datasets are available on HF GCS? Are all the datasets on huggingFace datasets hub are made available on GCS, automatically?

**Comment by lhoestq** [comment]
Only datasets like wikipedia, wiki40b, wiki_dpr and natural questions are available already processed on the HF google storage. This is used to download directly the arrow file instead of building it from the original data files.

**Comment by Jeevesh8** [comment]
@lhoestq How can we make sure that the data we upload on huggingFace hub is availablein form of preprocessed arrow files ?

**Comment by lhoestq** [comment]
We're still working on this :) This will be available soon

**Comment by mariosasko** [comment]
Hi! You can now use `Dataset.push_to_hub` to store preprocessed files on the Hub.
