### ISSUE TITLE
SQuAD version 

### ISSUE THREAD

**Issue by h-peng17** [huggingface/datasets#2098]
Hi~ 
I want train on squad dataset. What's the version of the squad? Is it 1.1 or 1.0? I'm new in QA, I don't find some descriptions about it.

**Comment by lhoestq** [comment]
Hi ! This is 1.1 as specified by the download urls here:

https://github.com/huggingface/nlp/blob/349ac4398a3bcae6356f14c5754483383a60e8a4/datasets/squad/squad.py#L50-L55

**Comment by h-peng17** [comment]
Got it. Thank you~
