### ISSUE TITLE
dataset viewer does not work anymore 

### ISSUE THREAD

**Issue by dorost1234** [huggingface/datasets#2120]
Hi
I normally use this link to see all datasets and how I can load them 

https://huggingface.co/datasets/viewer/

Now I am getting 

502 Bad Gateway
nginx/1.18.0 (Ubuntu)

could you bring this webpage back ? this was very helpful @lhoestq 
thanks for your help

**Comment by lhoestq** [comment]
Thanks for reporting :) We're looking into it

**Comment by srush** [comment]
Back up.
