### ISSUE TITLE
Problem downloading GEM wiki_auto_asset_turk dataset

### ISSUE THREAD

**Issue by mille-s** [huggingface/datasets#2123]
@yjernite 

### Summary

I am currently working on the GEM datasets and do not manage to download the wiki_auto_asset_turk data, whereas all other datasets download well with the same code.

### Steps to reproduce
Code snippet:

from datasets import load_dataset
#dataset = load_dataset('gem', 'web_nlg_en')
dataset = load_dataset('gem', 'wiki_auto_asset_turk')

```

**Expected behavior:**

I expect the dataset to start downloading (download bar appears and progresses toward 100%)

**Actual behavior:**
Instead of seeing the download bar appearing, nothing happens; the following appears in the console as expected, but nothing more:

Downloading: 36.6kB [00:00, 37.2MB/s]
Downloading: 41.7kB [00:00, ?B/s]
Downloading and preparing dataset gem/wiki_auto_asset_turk (download: 121.37 MiB, generated: 145.69 MiB, post-processed: Unknown size, total: 267.07 MiB) to C:\Users\sfmil\.cache\huggingface\datasets\gem\wiki_auto_asset_turk\1.0.0\f252756d7f1b8f019aac71a1623b2950acfe10d25d956668ac4eae4e93c58b8d...

### Is this a regression?
No, it was the first time I was trying to download this dataset (same for the other ones).

### Debug info
- Python version: Python 3.8.2
- OS version: Windows 10 Family

**Comment by mariosasko** [comment]
Hi,

sadly I can't replicate the problem on my Windows machine. Try to update the library to the newest version with:
```bash
pip install git+https://github.com/huggingface/datasets
```

**Comment by mille-s** [comment]
Thanks for the answer! I updated the library but unfortunately it didn't solve the problem.

**Comment by lhoestq** [comment]
Is there an error message ?
What stacktrace do you get if you interrupt the execution of the program while downloading ?

**Comment by mille-s** [comment]
Sorry for the long time since my last comment, I tried again and don't seem to have the problem anymore, thanks for your support!

**Comment by lhoestq** [comment]
Great ! I'm closing the issue then. Feel free to re-open if you experience this issue again
