### ISSUE TITLE
NonMatchingSplitsSizesError when loading blog_authorship_corpus

### ISSUE THREAD

**Issue by cedricconol** [huggingface/datasets#215]
Getting this error when i run `nlp.load_dataset('blog_authorship_corpus')`. 

```
raise NonMatchingSplitsSizesError(str(bad_splits))
nlp.utils.info_utils.NonMatchingSplitsSizesError: [{'expected': SplitInfo(name='train', 
num_bytes=610252351, num_examples=532812, dataset_name='blog_authorship_corpus'), 
'recorded': SplitInfo(name='train', num_bytes=616473500, num_examples=536323, 
dataset_name='blog_authorship_corpus')}, {'expected': SplitInfo(name='validation', 
num_bytes=37500394, num_examples=31277, dataset_name='blog_authorship_corpus'), 
'recorded': SplitInfo(name='validation', num_bytes=30786661, num_examples=27766, 
dataset_name='blog_authorship_corpus')}]
```

Upon checking it seems like there is a disparity between the information in `datasets/blog_authorship_corpus/dataset_infos.json` and what was downloaded. Although I can get away with this by passing `ignore_verifications=True` in `load_dataset`, I'm thinking doing so might give problems later on.

**Comment by lhoestq** [comment]
I just ran it on colab and got this
```
[{'expected': SplitInfo(name='train', num_bytes=610252351, num_examples=532812, dataset_name='blog_authorship_corpus'), 'recorded': SplitInfo(name='train', num_bytes=611607465, num_examples=533285, dataset_name='blog_authorship_corpus')}, {'expected': SplitInfo(name='validation', num_bytes=37500394, num_examples=31277, dataset_name='blog_authorship_corpus'), 'recorded': SplitInfo(name='validation', num_bytes=35652716, num_examples=30804, dataset_name='blog_authorship_corpus')}]
```
which is different from the `dataset_infos.json` and also different from yours.

It looks like the script for generating examples is not consistent

**Comment by lhoestq** [comment]
The files provided by the authors are corrupted and the script seems to ignore the xml files that can't be decoded (it does `try:... except UnicodeDecodeError`). Maybe depending of the environment some files can be opened and some others don't but not sure why

**Comment by lhoestq** [comment]
Feel free to do `ignore_verifications=True` for now... The verifications only include a check on the checksums of the downloaded files, an a check on the number of examples in each splits.

**Comment by EmilyAlsentzer** [comment]
I'm getting this same issue when loading the `imdb` corpus via `dataset = load_dataset("imdb")`. When I try `ignore_verifications=True`, no examples are read into the `train` portion of the dataset.

**Comment by lhoestq** [comment]
> I'm getting this same issue when loading the `imdb` corpus via `dataset = load_dataset("imdb")`. When I try `ignore_verifications=True`, no examples are read into the `train` portion of the dataset.

When the checksums don't match, it may mean that the file you downloaded is corrupted. In this case you can try to load the dataset again `load_dataset("imdb", download_mode="force_redownload")`

Also I just checked on my side and it worked fine:

```python
from datasets import load_dataset

dataset = load_dataset("imdb")
print(len(dataset["train"]))
# 25000
```

Let me know if redownloading fixes your issue @EmilyAlsentzer .
If not, feel free to open a separate issue.

**Comment by EmilyAlsentzer** [comment]
It doesn't seem to fix the problem. I'll open a separate issue. Thanks.

**Comment by putssander** [comment]
I wasn't aware of the "force_redownload" option and manually removed the '/home/me/.cache/huggingface/datasets/' dir, this worked for me (dataset 'cnn_dailymail')

**Comment by thomwolf** [comment]
Yes I think this might not be documented well enough. Let’s add it to the doc @lhoestq @SBrandeis.
And everything on how to control the cache behavior better (removing, overriding, changing the path, etc)

**Comment by albertvillanova** [comment]
Already fixed:
```python
In [1]: from datasets import load_dataset

In [2]: ds = load_dataset("blog_authorship_corpus")

In [3]: ds
Out[3]: 
DatasetDict({
    train: Dataset({
        features: ['text', 'date', 'gender', 'age', 'horoscope', 'job'],
        num_rows: 689793
    })
    validation: Dataset({
        features: ['text', 'date', 'gender', 'age', 'horoscope', 'job'],
        num_rows: 37919
    })
})

**Comment by JanRodriguez** [comment]
In my case, I had to remove the cache datasets directory completely as @putssander suggested, the download_mode='forced_redownload' was insufficient.

I had a private repository with data files that I loaded with a loading script. It was working fine until I pushed a new version of the data files and then the NonMatchingSplitsSizesError was raised.

**Comment by Xiaomin-HUANG** [comment]
I had the same issue. Adding` verification_mode="no_checks"` in laod_dataset() as param works for me

**Comment by goknurarican** [comment]
i had the same issue, solved it by "
dataset = load_dataset(
    "cnn_dailymail",
    "3.0.0",
    download_mode="force_redownload",
    ignore_verifications=True
)
" and the dataset downloaded without a problem: DatasetDict({
    train: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 861339
    })
    validation: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 40104
    })
    test: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 34470
    })
})
