### ISSUE TITLE
any possibility to download part of large datasets only?

### ISSUE THREAD

**Issue by dorost1234** [huggingface/datasets#2161]
Hi
Some of the datasets I need like cc100 are very large, and then I wonder if I can download first X samples of the shuffled/unshuffled data without going through first downloading the whole data then sampling? thanks

**Comment by thomwolf** [comment]
Not yet but it’s on the short/mid-term roadmap (requested by many indeed).

**Comment by dorost1234** [comment]
oh, great, really awesome feature to have, thank you very much for the great, fabulous work

**Comment by lhoestq** [comment]
We'll work on dataset streaming soon. This should allow you to only load the examples you need ;)

**Comment by dorost1234** [comment]
thanks a lot Quentin, this would be really really a great feature to have

**Comment by joshbriegal** [comment]
Is streaming completed? On the 1.8.0 docs it is mentioned (https://huggingface.co/docs/datasets/dataset_streaming.html), but when following the example I get the following error:

```
>>> dataset2 = load_dataset("amazon_us_reviews", "Pet_Products_v1_00", split='train', streaming=True)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-1eedab26cff1> in <module>()
----> 1 en_dataset = load_dataset('oscar', "unshuffled_deduplicated_en", split='train', streaming=True)

3 frames
/usr/local/lib/python3.7/dist-packages/datasets/builder.py in _create_builder_config(self, name, custom_features, **config_kwargs)
    339                 if value is not None:
    340                     if not hasattr(builder_config, key):
--> 341                         raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
    342                     setattr(builder_config, key, value)
    343 

ValueError: BuilderConfig OscarConfig(name='unshuffled_deduplicated_en', version=1.0.0, data_dir=None, data_files=None, description='Unshuffled and deduplicated, English OSCAR dataset') doesn't have a 'streaming' key.
```

**Comment by lhoestq** [comment]
Hi ! Streaming is available on `master` only right now. We'll make a new release 1.9.0 on Monday :)
