### ISSUE TITLE
visualization for cc100 is broken 

### ISSUE THREAD

**Issue by dorost1234** [huggingface/datasets#2162]
Hi
visualization through dataset viewer for cc100 is broken
https://huggingface.co/datasets/viewer/

thanks a lot

**Comment by lhoestq** [comment]
This looks like an issue with the cc100 dataset itself but not sure
Did you try loading cc100 on your machine ?

**Comment by dorost1234** [comment]
Hi
loading works fine, but the viewer only is broken
thanks

**Comment by mariosasko** [comment]
Hi! This visualization tool is deprecated now. The viewer at https://huggingface.co/datasets/cc100 works fine, so I'm closing this issue.
