### ISSUE TITLE
Duplicate data in Timit dataset

### ISSUE THREAD

**Issue by BHM-RB** [huggingface/datasets#2188]
I ran a simple code to list all texts in Timit dataset and the texts were all the same.
Is this dataset corrupted?
**Code:**
timit = load_dataset("timit_asr")
print(*timit['train']['text'], sep='\n')
**Result:**
Would such an act of refusal be useful?
Would such an act of refusal be useful?
Would such an act of refusal be useful?
Would such an act of refusal be useful?
...
...
Would such an act of refusal be useful?

**Comment by lhoestq** [comment]
Hi ! Thanks for reporting
This has been recently fixed on master #1995 
We'll do a new release soon !

**Comment by BHM-RB** [comment]
Hi Ihoestq,

Thank you. It works after upgrading the datasets
