### ISSUE TITLE
`xnli` dataset creating a tuple key while yielding instead of `str` or `int`

### ISSUE THREAD

**Issue by NikhilBartwal** [huggingface/datasets#2229]
When using  `ds = datasets.load_dataset('xnli', 'ar')`, the dataset generation script uses the following section of code in the egging, which yields a tuple key instead of the specified `str` or `int` key:
https://github.com/huggingface/datasets/blob/56346791aed417306d054d89bd693d6b7eab17f7/datasets/xnli/xnli.py#L196

Since, community datasets in Tensorflow Datasets also use HF datasets, this causes a Tuple key error while loading HF's `xnli` dataset. 
I'm up for sending a fix for this, I think we can simply use `file_idx + "_" + row_idx` as a unique key instead of a tuple.

**Comment by lhoestq** [comment]
Hi ! Sure sounds good. Also if you find other datasets that use tuples instead of str/int, you can also fix them !
thanks :)

**Comment by NikhilBartwal** [comment]
@lhoestq I have sent a PR for fixing the issue. Would be great if you could have a look! Thanks!
