### ISSUE TITLE
Bug in Dataset.class_encode_column

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#2272]
## Describe the bug

All the rest of the columns except the one passed to `Dataset.class_encode_column` are discarded.

## Expected results

All the original columns should be kept.

This needs regression tests.

**Comment by lhoestq** [comment]
This has been fixed in this commit: https://github.com/huggingface/datasets/pull/2254/commits/88676c930216cd4cc31741b99827b477d2b46cb6
