### ISSUE TITLE
A syntax error in example

### ISSUE THREAD

**Issue by mymusise** [huggingface/datasets#2327]
![image](https://user-images.githubusercontent.com/6883957/117315905-b47a5c00-aeba-11eb-91eb-b2a4a0212a56.png)

Sorry to report with an image, I can't find the template source code of this snippet.

**Comment by lhoestq** [comment]
cc @beurkinger but I think this has been fixed internally and will soon be updated right ?

**Comment by mymusise** [comment]
This issue has been fixed.
