### ISSUE TITLE
[Question] How to move and reuse preprocessed dataset? 

### ISSUE THREAD

**Issue by AtmaHou** [huggingface/datasets#2345]
Hi, I am training a gpt-2 from scratch using run_clm.py.

I want to move and reuse the preprocessed dataset (It take 2 hour to preprocess),

I tried to :

copy path_to_cache_dir/datasets to new_cache_dir/datasets
set export HF_DATASETS_CACHE="new_cache_dir/"
but the program still re-preprocess the whole dataset without loading cache.

I also tried to torch.save(lm_datasets, fw), but the saved file is only 14M.

What is the proper way to do this?

**Comment by lhoestq** [comment]
Hi :) Can you share with us the code you used ?

**Comment by lhoestq** [comment]
Also note that for the caching to work, you must reuse the exact same parameters as in the first run. Did you change any parameter ? The `preprocessing_num_workers` should also stay the same

**Comment by AtmaHou** [comment]
> Also note that for the caching to work, you must reuse the exact same parameters as in the first run. Did you change any parameter ? The `preprocessing_num_workers` should also stay the same

I changed the `preprocessing_num_workers` maybe it is the problem~ I will try again~
