### ISSUE TITLE
Add an API to access the language and pretty name of a dataset

### ISSUE THREAD

**Issue by sgugger** [huggingface/datasets#2347]
It would be super nice to have an API to get some metadata of the dataset from the name and args passed to `load_dataset`. This way we could programmatically infer the language and the name of a dataset when creating model cards automatically in the Transformers examples scripts.

**Comment by lhoestq** [comment]
Hi ! With @bhavitvyamalik we discussed about having something like
```python
from datasets import load_dataset_card

dataset_card = load_dataset_card("squad")
print(dataset_card.metadata.pretty_name)
# Stanford Question Answering Dataset (SQuAD)
print(dataset_card.metadata.languages)
# ["en"]

```
What do you think ?

I don't know if you already have a way to load the model tags in `transformers` but we can agree on the API to have something consistent.

Also note that the pretty name would only be used to show users something prettier than a dataset id, but in the end the source of truth will stay the dataset id (here `squad`).

**Comment by julien-c** [comment]
maybe use the hub-backed dataset_info method? (so there's only one parser of README.md metadata)?

**Comment by lhoestq** [comment]
What dataset_info method are you talking about @julien-c ? In `huggingface_hub` I can only see `model_info`.

**Comment by julien-c** [comment]
hmm the equivalent method in `datasets` (which could go into `huggingface_hub` at some point)

**Comment by mariosasko** [comment]
Indeed, this info can now be fetched with `huggingface_hub.dataset_info`, so I think we can close this issue.
