### ISSUE TITLE
Missing original answers in kilt-TriviaQA

### ISSUE THREAD

**Issue by PaulLerner** [huggingface/datasets#2391]
I previously opened an issue at https://github.com/facebookresearch/KILT/issues/42 but from the answer of @fabiopetroni it seems that the problem comes from HF-datasets

## Describe the bug
The `answer` field in kilt-TriviaQA, e.g. `kilt_tasks['train_triviaqa'][0]['output']['answer']` contains a list of alternative answer which are accepted for the question.  
However it'd be nice to know the original answer to the question (the only fields in `output` are `'answer', 'meta', 'provenance'`)

## How to fix
It can be fixed by retrieving the original answer from the original TriviaQA (e.g. `trivia_qa['train'][0]['answer']['value']`), perhaps at the same place as here where one retrieves the questions https://github.com/huggingface/datasets/blob/master/datasets/kilt_tasks/README.md#loading-the-kilt-knowledge-source-and-task-data

cc @yjernite who previously answered to an issue about KILT and TriviaQA :)

**Comment by yjernite** [comment]
Hi @PaulLerner!

Haha this is by design since we wanted to mirror the way the dataset was originally released, but you can very easily link the TriviaQA answers [as described in the dataset card](https://huggingface.co/datasets/kilt_tasks#loading-the-kilt-knowledge-source-and-task-data)

you can then use the `save_to_disk` function to save the processed version to disk for easy re-use

**Comment by yjernite** [comment]
That could be useful indeed! Feel free to open a PR on the dataset card if you already have some code that runs, otherwise we'll take care of it soon :)

**Comment by PaulLerner** [comment]
I can open a PR but there is 2 details to fix:
- the name for the corresponding key (e.g. `original_answer`)
- how to implement it: I’m not sure what happens when you map `lambda x: {'input': ...}` as it keeps the other keys (e.g. `output`) intact but here since we want to set a nested value (e.g. `x['output']['original_answer']`) I implemented it with a regular function (not lambda), see below

```py
def add_original_answer(x, trivia_qa, triviaqa_map):
    i = triviaqa_map[x['id']]
    item['output']['original_answer'] = trivia_qa['validation'][i]['answer']['value']
    return x
```
