### ISSUE TITLE
Datasets with tricky task templates

### ISSUE THREAD

**Issue by lewtun** [huggingface/datasets#2520]
I'm collecting a list of datasets here that don't follow the "standard" taxonomy and require further investigation to implement task templates for.

## Text classification

* [hatexplain](https://huggingface.co/datasets/hatexplain): ostensibly a form of text classification, but not in the standard `(text, target)` format and each sample appears to be tokenized.
* [muchocine](https://huggingface.co/datasets/muchocine): contains two candidate text columns (long-form and summary) which in principle requires two `TextClassification` templates which is not currently supported

**Comment by mariosasko** [comment]
The `task_templates` API is deprecated in favor of the `train-eval-index` YAML field, so I'm closing this issue.
