### ISSUE TITLE
Load datasets from the Hub without requiring a dataset script

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets#2629]
As a user I would like to be able to upload my csv/json/text/parquet/etc. files in a dataset repository on the Hugging Face Hub and be able to load this dataset with `load_dataset` without having to implement a dataset script.

Moreover I would like to be able to specify which file goes into which split using the `data_files` argument.

This feature should be compatible with private repositories and dataset streaming.

This can be implemented by checking the extension of the files in the dataset repository and then by using the right dataset builder that is already packaged in the library (csv/json/text/parquet/etc.)

**Comment by julien-c** [comment]
This is so cool, let us know if we can help with anything on the hub side (@Pierrci @elishowk) 🎉
