### ISSUE TITLE
Allow the selection of multiple columns at once

### ISSUE THREAD

**Issue by Dref360** [huggingface/datasets#2655]
**Is your feature request related to a problem? Please describe.**

Similar to pandas, it would be great if we could select multiple columns at once.

**Describe the solution you'd like**
```python
my_dataset = ...  # Has columns ['idx', 'sentence', 'label']
idx, label = my_dataset[['idx', 'label']]
```

**Describe alternatives you've considered**
we can do `[dataset[col] for col in ('idx', 'label')]`

**Additional context**
This is of course very minor.

**Comment by Ap1075** [comment]
Hi! I was looking into this and hope you can clarify a point. Your my_dataset variable would be of type DatasetDict which means the alternative you've described (dict comprehension) is what makes sense. 
Is there a reason why you wouldn't want to convert my_dataset to a pandas df if you'd like to use it like one? Please let me know if I'm missing something.

**Comment by Dref360** [comment]
Hi! Sorry for the delay.

In this case, the dataset would be a `datasets.Dataset` and we want to select multiple columns, the `idx` and `label` columns for example.

My issue is that my dataset is too big for memory if I load everything into pandas.

**Comment by dusadvarshit** [comment]
Hello - any update on this? Thank you.
