### ISSUE TITLE
Error when downloading C4

### ISSUE THREAD

**Issue by Aktsvigun** [huggingface/datasets#2677]
Hi,
I am trying to download `en` corpus from C4 dataset. However, I get an error caused by validation files download (see image). My code is very primitive:
`datasets.load_dataset('c4', 'en')`

Is this a bug or do I have some configurations missing on my server? 
Thanks!

<img width="1014" alt="Снимок экрана 2021-07-20 в 11 37 17" src="https://user-images.githubusercontent.com/36672861/126289448-6e0db402-5f3f-485a-bf74-eb6e0271fc25.png">

**Comment by lhoestq** [comment]
Hi Thanks for reporting !
It looks like these files are not correctly reported in the list of expected files to download, let me fix that ;)

**Comment by lhoestq** [comment]
Alright this is fixed now. We'll do a new release soon to make the fix available.

In the meantime feel free to simply pass `ignore_verifications=True` to `load_dataset` to skip this error

**Comment by Aktsvigun** [comment]
@lhoestq thank you for such a quick feedback!
