### ISSUE TITLE
Calling shuffle on IterableDataset will disable batching in case any functions were mapped

### ISSUE THREAD

**Issue by amankhandelia** [huggingface/datasets#2716]
When using dataset in streaming mode, if one applies `shuffle` method on the dataset and `map` method for which `batched=True` than the batching operation will not happen, instead `batched` will be set to `False`

I did RCA on the dataset codebase, the problem is emerging from [this line of code](https://github.com/huggingface/datasets/blob/d25a0bf94d9f9a9aa6cabdf5b450b9c327d19729/src/datasets/iterable_dataset.py#L197) here as it is
`self.ex_iterable.shuffle_data_sources(seed), function=self.function, batch_size=self.batch_size`, as one can see it is missing batched argument, which means that the iterator fallsback to default constructor value, which in this case is `False`.
To remedy the problem we can change this line to
`self.ex_iterable.shuffle_data_sources(seed), function=self.function, batched=self.batched, batch_size=self.batch_size`

**Comment by lhoestq** [comment]
Hi :) Good catch ! Feel free to open a PR if you want to contribute, this would be very welcome ;)

**Comment by amankhandelia** [comment]
Have raised the PR [here](https://github.com/huggingface/datasets/pull/2717)

**Comment by albertvillanova** [comment]
Fixed by #2717.
