### ISSUE TITLE
Missing cache file

### ISSUE THREAD

**Issue by PosoSAgapo** [huggingface/datasets#2722]
Strangely missing cache file after I  restart my program again.

`glue_dataset = datasets.load_dataset('glue', 'sst2')`

`FileNotFoundError: [Errno 2] No such file or directory: /Users/chris/.cache/huggingface/datasets/glue/sst2/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96d6053ad/dataset_info.json'`

**Comment by PosoSAgapo** [comment]
This could be solved by going to the glue/ directory and delete sst2 directory, then load the dataset again will help you redownload the dataset.

**Comment by lhoestq** [comment]
Hi ! Not sure why this file was missing, but yes the way to fix this is to delete the sst2 directory and to reload the dataset
