### ISSUE TITLE
BERTScore Error

### ISSUE THREAD

**Issue by gagan3012** [huggingface/datasets#2765]
## Steps to reproduce the bug
```python
predictions = ["hello there", "general kenobi"]
references = ["hello there", "general kenobi"]
bert = load_metric('bertscore')
bert.compute(predictions=predictions, references=references,lang='en')
```

# Bug
`TypeError: get_hash() missing 1 required positional argument: 'use_fast_tokenizer'`

## Environment info

- `datasets` version:
- Platform: Colab 
- Python version:
- PyArrow version:

**Comment by mariosasko** [comment]
Hi,

The `use_fast_tokenizer` argument has been recently added to the bert-score lib. I've opened a PR with the fix. In the meantime, you can try to downgrade the version of bert-score with the following command to make it work:
```
pip uninstall bert-score
pip install "bert-score<0.3.10"
```
