### ISSUE TITLE
ConnectionError: Couldn't reach https://raw.githubusercontent.com

### ISSUE THREAD

**Issue by jinec** [huggingface/datasets#2787]
Hello,
I am trying to run run_glue.py and it gives me this error -

Traceback (most recent call last):
  File "E:/BERT/pytorch_hugging/transformers/examples/pytorch/text-classification/run_glue.py", line 546, in <module>
    main()
  File "E:/BERT/pytorch_hugging/transformers/examples/pytorch/text-classification/run_glue.py", line 250, in main
    datasets = load_dataset("glue", data_args.task_name, cache_dir=model_args.cache_dir)
  File "C:\install\Anaconda3\envs\huggingface\lib\site-packages\datasets\load.py", line 718, in load_dataset
    use_auth_token=use_auth_token,
  File "C:\install\Anaconda3\envs\huggingface\lib\site-packages\datasets\load.py", line 320, in prepare_module
    local_path = cached_path(file_path, download_config=download_config)
  File "C:\install\Anaconda3\envs\huggingface\lib\site-packages\datasets\utils\file_utils.py", line 291, in cached_path
    use_auth_token=download_config.use_auth_token,
  File "C:\install\Anaconda3\envs\huggingface\lib\site-packages\datasets\utils\file_utils.py", line 623, in get_from_cache
    raise ConnectionError("Couldn't reach {}".format(url))
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/1.7.0/datasets/glue/glue.py

Trying to do python run_glue.py  --model_name_or_path
bert-base-cased
--task_name
mrpc
--do_train
--do_eval
--max_seq_length
128
--per_device_train_batch_size
32
--learning_rate
2e-5
--num_train_epochs
3
--output_dir
./tmp/mrpc/

Is this something on my end? From what I can tell, this was re-fixeded by @fullyz a few months ago.
Thank you!

**Comment by jinec** [comment]
the bug code locate in ：
    if data_args.task_name is not None:
        # Downloading and loading a dataset from the hub.
        datasets = load_dataset("glue", data_args.task_name, cache_dir=model_args.cache_dir)

**Comment by albertvillanova** [comment]
Hi @jinec,

From time to time we get this kind of `ConnectionError` coming from the github.com website: https://raw.githubusercontent.com

Normally, it should work if you wait a little and then retry.

**Comment by jinec** [comment]
cannot connect，even by Web browser，please check that  there is some  problems。

**Comment by albertvillanova** [comment]
I can access https://raw.githubusercontent.com/huggingface/datasets/1.7.0/datasets/glue/glue.py without problem...

**Comment by renmada** [comment]
> I can access https://raw.githubusercontent.com/huggingface/datasets/1.7.0/datasets/glue/glue.py without problem...

I can not access https://raw.githubusercontent.com/huggingface/datasets either,   I am in China

**Comment by jinec** [comment]
Finally i can access it, by the superfast software. Thanks

**Comment by xrzz597** [comment]
> Finally i can access it, by the superfast software. Thanks

Excuse me, I have the same problem as you, could you please tell me how to solve it？

**Comment by mikechen66** [comment]
It is not related to the area, the ConnectionError with http://raw.githubuserconent.coim persisted with load_data function, datasets module. However, it can be set ssl if there is a snippet to allow directly downloading from github such as following. 

`$ wget https://raw.githubusercontent.com/...`


or 

for the tfds or nltk downloading as follows. 

```
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context
```
