### ISSUE TITLE
Dataset Preprocessing Cache with .map() function not working as expected

### ISSUE THREAD

**Issue by sarahwie** [huggingface/datasets#279]
I've been having issues with reproducibility when loading and processing datasets with the `.map` function. I was only able to resolve them by clearing all of the cache files on my system. 

Is there a way to disable using the cache when processing a dataset? As I make minor processing changes on the same dataset, I want to be able to be certain the data is being re-processed rather than loaded from a cached file. 

Could you also help me understand a bit more about how the caching functionality is used for pre-processing? E.g. how is it determined when to load from a cache vs. reprocess. 
I was particularly having an issue where the correct dataset splits were loaded, but as soon as I applied the `.map()` function to each split independently, they somehow all exited this process having been converted to the test set.
Thanks!

**Comment by lhoestq** [comment]
When you're processing a dataset with `.map`, it checks whether it has already done this computation using a hash based on the function and the input (using some fancy serialization with `dill`). If you found that it doesn't work as expected in some cases, let us know !

Given that, you can still force to re-process using `.map(my_func, load_from_cache_file=False)` if you want to.

I am curious about the problem you have with splits. It makes me think about #160 that was an issue of version 0.1.0. What version of `nlp` are you running ? Could you give me more details ?

**Comment by sarahwie** [comment]
Thanks, that's helpful! I was running 0.1.0, but since upgraded to 0.2.1. I can't reproduce the issue anymore as I've cleared the cache & everything now seems to be running fine since the upgrade. I've added some checks to my code, so if I do encounter it again I will reopen this issue.

**Comment by sarahwie** [comment]
Just checking in, the cache sometimes still does not work when I make changes in my processing function in version `1.2.1`. Is this a system-specific issue?

**Comment by lhoestq** [comment]
Hi @sarahwie 
The data are reloaded from the cache if the hash of the function you provide is the same as a computation you've done before. The hash is computed by recursively looking at the python objects of the function you provide.

If you think there's an issue, can you share the function you used or a google colab please ?

**Comment by sarahwie** [comment]
I can't reproduce it, so I'll close for now.

**Comment by moinnadeem** [comment]
Hi @lhoestq!

I have a `hparams.yaml` configuration, and I have noticed that when I change some hyperparameter in the YAML file, it changes the hash of my tokenizer function as well. I am calculating the hash by `Hasher.hash(tokenize_function)`, and my tokenize function is as follows: 

```
          # credit: taken from Huggingface's `run_clm.py` example.
          def tokenize_function(examples):
              with CaptureLogger(tok_logger) as cl:
                  output = self.tokenizer(examples[text_column_name])
              # clm input could be much much longer than block_size
              if "Token indices sequence length is longer than the" in cl.out:
                  tok_logger.warning(
                      "^^^^^^^^^^^^^^^^ Please ignore the warning above - this long input will be chunked"
                      "into smaller bits before being passed to the model."
                  )
              return output
````

Is there some way to force it to read from a particular cache file , regardless of the fingerprint for the function? I won't be changing the function very often. 

Thanks!

**Comment by Cloud0310** [comment]
<img width="942" height="382" alt="Image" src="https://github.com/user-attachments/assets/2fb0acba-ac07-4f00-bf30-c1ac932c9072" />
Guess I met with the case in which this caching misses all the time.

Once the map function has a default param, things gets crazy here.
<img width="838" height="239" alt="Image" src="https://github.com/user-attachments/assets/856aab17-129f-4122-800b-04c3e9d4b880" />
Like in this case, the use of param (self.image_size) of `rasterize_strokes` function is causing me duplicate cache. 

And I think there should **be a better way to implement the caching hash** function here,or, at least , **tell your user with explicit WARNING** to pass map pure functions only.
