### ISSUE TITLE
OpenWebText: NonMatchingSplitsSizesError

### ISSUE THREAD

**Issue by thomasw21** [huggingface/datasets#2839]
## Describe the bug

When downloading `openwebtext`, I'm getting:
```
datasets.utils.info_utils.NonMatchingSplitsSizesError: [{'expected': SplitInfo(name='train', num_bytes=39769494896, num_examples=8013769, dataset_name='openwebtext'), 'recorded': SplitInfo(name='train', num_bytes=39611023912, num_examples=7982430, dataset_name='openwebtext')}]
```

I suspect that the file we download from has changed since the size doesn't look like to match with documentation

`Downloading:   0%|          | 0.00/12.9G [00:00<?, ?B/s]` This suggest the total size is 12.9GB, whereas the one documented mentions `Size of downloaded dataset files: 12283.35 MB`.

## Steps to reproduce the bug
```python
from datasets import load_dataset

load_dataset("openwebtext", download_mode="force_redownload")
```

## Expected results

Loading is successful

## Actual results

Loading throws above error.

## Environment info

- `datasets` version:1.10.2
- Platform:OS
- Python version:3.8
- PyArrow version:4.0.1

**Comment by lhoestq** [comment]
Thanks for reporting, I'm updating the verifications metadata

**Comment by lhoestq** [comment]
I just regenerated the verifications metadata and noticed that nothing changed: the data file is fine (the checksum didn't change), and the number of examples is still 8013769. Not sure how you managed to get 7982430 examples.

Can you try to delete your cache ( by default at `~/.cache/huggingface/datasets`) and try again please ?

**Comment by thomasw21** [comment]
I'll try without deleting the whole cache (we have large datasets already stored).
Sorry plateform should be linux (Redhat version 8.1)

**Comment by lhoestq** [comment]
Hi @thomasw21 , are you still having this issue after clearing your cache ?

**Comment by thomasw21** [comment]
Sorry I haven't had time to work on this. I'll close and re-open if I can't figure out why I'm having this issue. Thanks for taking a look !
