### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Chenfei-Kang** [huggingface/datasets#2869]
## Describe the bug

TypeError: 'NoneType' object is not callable
## Steps to reproduce the bug
```python
from datasets import load_dataset, load_metric
dataset = datasets.load_dataset("glue", 'cola')
```

## Expected results
A clear and concise description of the expected results.

## Actual results
Specify the actual results or traceback.

## Environment info

- `datasets` version: 1.11.0
- Platform:
- Python version: 3.7
- PyArrow version:

**Comment by albertvillanova** [comment]
Hi, @Chenfei-Kang.

I'm sorry, but I'm not able to reproduce your bug:
```python
from datasets import load_dataset

ds = load_dataset("glue", 'cola')
ds
```
```
DatasetDict({
    train: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 8551
    })
    validation: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1043
    })
    test: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1063
    })
})
```

Could you please give more details and environment info (platform, PyArrow version)?

**Comment by Chenfei-Kang** [comment]
> Hi, @Chenfei-Kang.
> 
> I'm sorry, but I'm not able to reproduce your bug:
> 
> ```python
> from datasets import load_dataset
> 
> ds = load_dataset("glue", 'cola')
> ds
> ```
> 
> ```
> DatasetDict({
>     train: Dataset({
>         features: ['sentence', 'label', 'idx'],
>         num_rows: 8551
>     })
>     validation: Dataset({
>         features: ['sentence', 'label', 'idx'],
>         num_rows: 1043
>     })
>     test: Dataset({
>         features: ['sentence', 'label', 'idx'],
>         num_rows: 1063
>     })
> })
> ```
> 
> Could you please give more details and environment info (platform, PyArrow version)?

Sorry to reply you so late.
platform: pycharm 2021 + anaconda with python 3.7
PyArrow version: 5.0.0
huggingface-hub: 0.0.16
datasets: 1.9.0

**Comment by albertvillanova** [comment]
- For the platform, we need to know the operating system of your machine. Could you please run the command `datasets-cli env` and copy-and-paste its output below?
- In relation with the error, you just gave us the error type and message (`TypeError: 'NoneType' object is not callable`). Could you please copy-paste the complete stack trace, so that we know exactly which part of the code threw the error?

**Comment by Chenfei-Kang** [comment]
> * For the platform, we need to know the operating system of your machine. Could you please run the command `datasets-cli env` and copy-and-paste its output below?
> * In relation with the error, you just gave us the error type and message (`TypeError: 'NoneType' object is not callable`). Could you please copy-paste the complete stack trace, so that we know exactly which part of the code threw the error?

1. For the platform, here are the output:
        - datasets` version: 1.11.0
        - Platform: Windows-10-10.0.19041-SP0
        - Python version: 3.7.10
        - PyArrow version: 5.0.0
2. For the code and error：
     ```python
     from datasets import load_dataset, load_metric
     dataset = load_dataset("glue", "cola")
    ```
    ```python
    Traceback (most recent call last):
    ....
    ....
    File "my_file.py", line 2, in <module>
    dataset = load_dataset("glue", "cola")
    File "My environments\lib\site-packages\datasets\load.py", line 830, in load_dataset
    **config_kwargs,
     File "My environments\lib\site-packages\datasets\load.py", line 710, in load_dataset_builder
    **config_kwargs,
    TypeError: 'NoneType' object is not callable
    ```
   Thank you!

**Comment by albertvillanova** [comment]
For that environment, I am sorry but I can't reproduce the bug: I can load the dataset without any problem.

**Comment by albertvillanova** [comment]
One naive question: do you have internet access from the machine where you execute the code?

**Comment by Chenfei-Kang** [comment]
> For that environment, I am sorry but I can't reproduce the bug: I can load the dataset without any problem.

But I can download other task dataset such as `dataset = load_dataset('squad')`. I don't know what went wrong.  Thank you so much!

**Comment by klyuhang9** [comment]
Hi,friends. I meet the same problem. Do you have a way to fix this? Thanks!

**Comment by OptNuo** [comment]
I'm getting the same error. Have you solved the problem? Please tell me how to fix it

**Comment by rippleD030** [comment]
same error, fix by Downgrade the datasets version to 2.16.0.

**Comment by Doby-Xu** [comment]
Similar error when trying to download another dataset with 2.16.0, but 2.10.0 works

**Comment by Ki-Seki** [comment]
Same issue in v3.1.0; resolved by downgrading to v2.21.0.

**Comment by no-con** [comment]
same error, using the lower version 2.16.0 works

**Comment by nanu23333** [comment]
I met the same error, how did you save your problem?

**Comment by rippleD030** [comment]
> I met the same error, how did you save your problem?

down grade datasets version, try 2.16.0 or 2.10.0

**Comment by mightyerwa** [comment]
success solve the problem by downgrade to 2.10.0

**Comment by fzhml** [comment]
ERROR: Could not find a version that satisfies the requirement dataset==2.10.0 (from versions: 0.3, 0.3.3, 0.3.5, 0.3.6, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.4, 0.5.5, 0.5.6, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.7.1, 0.8.0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.2)
ERROR: No matching distribution found for dataset==2.10.0
