### ISSUE TITLE
Don't keep the dummy data folder or dataset_infos.json when resolving data files

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets#2877]
When there's no dataset script, all the data files of a folder or a repository on the Hub are loaded as data files.

There are already a few exceptions:
- files starting with "." are ignored
- the dataset card "README.md" is ignored
- any file named "config.json" is ignored (currently it isn't used anywhere, but it could be used in the future to define splits or configs for example, but not 100% sure)

However any data files in a folder named "dummy" should be ignored as well as they should only be used to test the dataset.
Same for "dataset_infos.json" which should only be used to get the `dataset.info`

**Comment by Ishan-Kumar2** [comment]
Hi @lhoestq I am new to huggingface datasets, I would like to work on this issue!

**Comment by lhoestq** [comment]
Thanks for the help :) 

As mentioned in the PR, excluding files named "dummy_data.zip" is actually more general than excluding the files inside a "dummy" folder. I just did the change in the PR, I think we can merge it now
