### ISSUE TITLE
windows download abnormal

### ISSUE THREAD

**Issue by wei1826676931** [huggingface/datasets#2917]
## Describe the bug
The script clearly exists (accessible from the browser), but the script download fails on windows. Then I tried it again and it can be downloaded normally on linux. why??
## Steps to reproduce the bug
```python3.7 + windows
![image](https://user-images.githubusercontent.com/52347799/133436174-4303f847-55d5-434f-a749-08da3bb9b654.png)


# Sample code to reproduce the bug
```

## Expected results
It can be downloaded normally.

## Actual results
it cann't

## Environment info

- `datasets` version:1.11.0
- Platform:windows
- Python version:3.7
- PyArrow version:

**Comment by lhoestq** [comment]
Hi ! Is there some kind of proxy that is configured in your browser that gives you access to internet ? If it's the case it could explain why it doesn't work in the code, since the proxy wouldn't be used

**Comment by wei1826676931** [comment]
It is indeed an agency problem, thank you very, very much

**Comment by lhoestq** [comment]
Let me know if you have other questions :)

Closing this issue now
