### ISSUE TITLE
Support loading a dataset from SQLite files

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#3094]
As requested by @julien-c, we could eventually support loading a dataset from SQLite files, like it is the case for JSON/CSV files.

**Comment by julien-c** [comment]
for reference Kaggle has a good number of open source datasets stored in sqlite

Alternatively a tutorial or tool on how to convert from sqlite to parquet would be cool too

**Comment by Dref360** [comment]
Hello, could we leverage [`pandas.read_sql`](https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html) for this? 

Or do we want to support very large SQLite files and we need to add pagination?

Happy to take a stab at it.
