### ISSUE TITLE
`cast_column` makes audio decoding fail

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/datasets#3095]
## Describe the bug

After changing the sampling rate automatic decoding fails.

## Steps to reproduce the bug
```python
from datasets import load_dataset
import datasets

ds = load_dataset("common_voice", "ab", split="train")

ds = ds.cast_column("audio", datasets.features.Audio(sampling_rate=16_000))

print(ds[0]["audio"])  # <- this fails currently
```

yields:

```
TypeError: forward() takes 2 positional arguments but 4 were given
```

## Expected results
no failure

## Actual results
Specify the actual results or traceback.

## Environment info

Copy-and-paste the text below in your GitHub issue.

- `datasets` version: 1.13.2 (master)
- Platform: Linux-5.11.0-1019-aws-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyArrow version: 5.0.0

**Comment by albertvillanova** [comment]
Thanks for reporting, @patrickvonplaten.

I think the issue is related to mp3 decoding, not to `cast_column`.

You can check that `cast_column` works OK with non-mp3 audio files:
```python
from datasets import load_dataset
import datasets
ds = load_dataset("arabic_speech_corpus", split="train")
ds = ds.cast_column("audio", datasets.features.Audio(sampling_rate=16_000))
print(ds[0]["audio"])
```

I'm fixing it.

**Comment by v-yunbin** [comment]
the` “cast_column("audio", Audio(sampling_rate=16000))”` can filter empy audio？actuall，In many scenes，some audio   is empy and can not be detected.  when traing，it (some audio) leads that training throw error.
