### ISSUE TITLE
conll2002 issues

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/datasets#3188]
**Link:** https://huggingface.co/datasets/conll2002

The dataset viewer throws a server error when trying to preview the dataset. 

```
Message:       Extraction protocol 'train' for file at 'https://raw.githubusercontent.com/teropa/nlp/master/resources/corpora/conll2002/esp.train' is not implemented yet
```

In addition, the "point of contact" has encoding issues and does not work when clicked.

Am I the one who added this dataset ? No, @lhoestq  did

**Comment by lhoestq** [comment]
Hi ! Thanks for reporting :)

This is related to https://github.com/huggingface/datasets/issues/2742, I'm working on it. It should fix the viewer for around 80 datasets.

**Comment by BramVanroy** [comment]
Ah, hadn't seen that sorry.

The scrambled "point of contact" is a separate issue though, I think.

**Comment by BramVanroy** [comment]
@lhoestq The "point of contact" is still an issue.

**Comment by lhoestq** [comment]
It will be fixed in https://github.com/huggingface/datasets/pull/3274, thanks
