### ISSUE TITLE
FileNotFoundError for TupleIE dataste

### ISSUE THREAD

**Issue by arda-vianai** [huggingface/datasets#3204]
Hi,
`dataset = datasets.load_dataset('tuple_ie', 'all')`

returns a FileNotFound error. Is the data not available? 

Many thanks.

**Comment by arda-vianai** [comment]
@mariosasko @lhoestq Could you give me an update on how to load the dataset after the fix?
Thanks.

**Comment by mariosasko** [comment]
Hi,

first, you can try:
```python
import datasets
dataset = datasets.load_dataset('tuple_ie', 'all', revision="master")
```
If this doesn't work, your version of `datasets` is missing some features that are required to run the dataset script, so install the master version with the following command:
```
pip install git+https://github.com/huggingface/datasets.git
```
and then:
```python
import datasets
dataset = datasets.load_dataset('tuple_ie', 'all')
```
should work (even without `revision`).

**Comment by arda-vianai** [comment]
@mariosasko 
Thanks, it is working now. I actually did that before but I didn't restart the kernel. I restarted it and it works now. My bad!!!
Many thanks and great job!
-arda
