### ISSUE TITLE
Sort files before loading

### ISSUE THREAD

**Issue by lvwerra** [huggingface/datasets#3212]
When loading a dataset that consists of several files (e.g. `my_data/data_001.json`, `my_data/data_002.json` etc.) they are not loaded in order when using `load_dataset("my_data")`.

This could lead to counter-intuitive results if, for example, the data files are sorted by date or similar since they would appear in different order in the `Dataset`.

The straightforward solution is to sort the list of files alphabetically before loading them.

cc @lhoestq

**Comment by lhoestq** [comment]
This will be fixed by https://github.com/huggingface/datasets/pull/3221
