### ISSUE TITLE
wikitext description wrong

### ISSUE THREAD

**Issue by hongyuanmei** [huggingface/datasets#3237]
## Describe the bug
Descriptions of the wikitext datasests are wrong. 

## Steps to reproduce the bug
Please see: https://github.com/huggingface/datasets/blob/f6dcafce996f39b6a4bbe3a9833287346f4a4b68/datasets/wikitext/wikitext.py#L50

## Expected results
The descriptions for raw-v1 and v1 should be switched.

**Comment by albertvillanova** [comment]
Hi @hongyuanmei, thanks for reporting.

I'm fixing it.

**Comment by albertvillanova** [comment]
Duplicate of #795.
