### ISSUE TITLE
Couldn't reach data file for disaster_response_messages

### ISSUE THREAD

**Issue by pandya6988** [huggingface/datasets#3240]
## Describe the bug
Following command gives an ConnectionError.

## Steps to reproduce the bug
```python
disaster = load_dataset('disaster_response_messages')
```

## Error
```
ConnectionError: Couldn't reach https://datasets.appen.com/appen_datasets/disaster_response_data/disaster_response_messages_training.csv
```
## Expected results
It should load dataset without an error

## Actual results
Specify the actual results or traceback.

## Environment info

- `datasets` version:
- Platform: Google Colab
- Python version: 3.7
- PyArrow version:

**Comment by lhoestq** [comment]
It looks like the dataset isn't available anymore on appen.com

The CSV files appear to still be available at https://www.kaggle.com/landlord/multilingual-disaster-response-messages though. It says that the data are under the CC0 license so I guess we can host the dataset elsewhere instead ?
