### ISSUE TITLE
Use f-strings for string formatting 

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets#3257]
f-strings offer better readability/performance than `str.format` and `%`, so we should use them in all places in our codebase unless there is good reason to keep the older syntax.

> **NOTE FOR CONTRIBUTORS**: To avoid large PRs and possible merge conflicts, do 1-3 modules per PR. Also, feel free to ignore the files located under `datasets/*`.

**Comment by Carlosbogo** [comment]
Hi, I would be glad to help with this. Is there anyone else working on it?

**Comment by Mehdi2402** [comment]
Hi, I would be glad to work on this too.

**Comment by Mehdi2402** [comment]
#self-assign

**Comment by Carlosbogo** [comment]
Oh I see. I will be glad to help with the `datasets` directory then.
