### ISSUE TITLE
Add Speech Commands dataset

### ISSUE THREAD

**Issue by osanseviero** [huggingface/datasets#3283]
## Adding a Dataset
- **Name:** Speech commands
- **Description:** A Dataset for Limited-Vocabulary Speech Recognition
- **Paper:** https://arxiv.org/abs/1804.03209
- **Data:** https://www.tensorflow.org/datasets/catalog/speech_commands,  Available:
http://download.tensorflow.org/data/speech_commands_v0.02.tar.gz
- **Motivation:** Nice dataset for audio classification training

cc @anton-l 

Instructions to add a new dataset can be found [here](https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md).

**Comment by polinaeterna** [comment]
#self-assign

**Comment by polinaeterna** [comment]
#self-assign
