### ISSUE TITLE
Agnews dataset viewer is not working

### ISSUE THREAD

**Issue by pietrolesci** [huggingface/datasets#3298]
## Dataset viewer issue for '*name of the dataset*'

**Link:** https://huggingface.co/datasets/ag_news

Hi there, the `ag_news` dataset viewer is not working.

Am I the one who added this dataset? No

**Comment by lhoestq** [comment]
Hi ! Thanks for reporting
We've already fixed the code that generates the preview for this dataset, we'll release the fix soon :)

**Comment by pietrolesci** [comment]
Hi @lhoestq, thanks for your feedback!

**Comment by severo** [comment]
Fixed in the viewer.

https://huggingface.co/datasets/ag_news
