### ISSUE TITLE
nested sequence feature won't encode example if the first item of the outside sequence is an empty list

### ISSUE THREAD

**Issue by function2-llx** [huggingface/datasets#3306]
## Describe the bug
As the title, nested sequence feature won't encode example if the first item of the outside sequence is an empty list.

## Steps to reproduce the bug
```python
from datasets import Features, Sequence, ClassLabel
features = Features({
    'x': Sequence(Sequence(ClassLabel(names=['a', 'b']))),
})
print(features.encode_batch({
    'x': [
        [['a'], ['b']],
        [[], ['b']],
    ]
}))
```

## Expected results
print `{'x': [[[0], [1]], [[], ['1']]]}`

## Actual results
print `{'x': [[[0], [1]], [[], ['b']]]}`

## Environment info
- `datasets` version: 1.15.1
- Platform: Linux-5.13.0-21-generic-x86_64-with-glibc2.34
- Python version: 3.9.7
- PyArrow version: 6.0.0

## Additional information
I think the issue stems from [here](https://github.com/huggingface/datasets/blob/8555197a3fe826e98bd0206c2d031c4488c53c5c/src/datasets/features/features.py#L847-L848).

**Comment by function2-llx** [comment]
knock knock

**Comment by mariosasko** [comment]
Hi, thanks for reporting! I've linked a PR that should fix the issue.

**Comment by function2-llx** [comment]
I've checked the PR and it looks great, thanks a lot!
