### ISSUE TITLE
Integrate Polars library

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#3334]
Check potential integration of the Polars library: https://github.com/pola-rs/polars
- Benchmark: https://h2oai.github.io/db-benchmark/

CC: @thomwolf @lewtun

**Comment by lewtun** [comment]
If possible, a neat API could be something like `Dataset.to_polars()`, as well as `Dataset.set_format("polars")`

**Comment by albertvillanova** [comment]
Note they use a "custom" implementation of Arrow: [Arrow2](https://github.com/jorgecarleitao/arrow2).

**Comment by amrit110** [comment]
Is there some direction regarding this from the HF team @lewtun ? Can conversion from polars to HF dataset be implemented with limited/zero copy? So, something like ``Dataset.from_polars()`` and ``Dataset.to_polars()`` like you mentioned. Happy to contribute if I can get some pointers on how this may be implemented.

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks!

**Comment by baggiponte** [comment]
> Hi, is there any updates? Thanks!

The feature has been there for a bit 😊 You can call `dataset.to_polars()` (on a `Dataset`, not a `DatasetDict`). The issue can be closed, I guess! @lhoestq

**Comment by fzyzcjy** [comment]
Looks great and thanks!

**Comment by albertvillanova** [comment]
Thank you.
