### ISSUE TITLE
Mirror the canonical datasets to the Hugging Face Hub

### ISSUE THREAD

**Issue by severo** [huggingface/datasets#3341]
- [ ] create a repo on https://hf.co/datasets for every canonical dataset
- [ ] on every commit related to a dataset, update the hf.co repo

See https://github.com/huggingface/moon-landing/pull/1562

@SBrandeis: I let you edit this description if needed to precise the intent.

**Comment by lhoestq** [comment]
I created a GitHub project to keep track of what needs to be done:
https://github.com/huggingface/datasets/projects/3

I also store my code in a (private for now) repository at https://github.com/huggingface/mirror_canonical_datasets_on_hub

**Comment by severo** [comment]
I understand that the datasets are mirrored on the Hub now, right? Might I close @lhoestq @SBrandeis?
