### ISSUE TITLE
[Audio] Allow resampling for audio datasets in streaming mode

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/datasets#3369]
Many audio datasets like Common Voice always need to be resampled. This can very easily be done in non-streaming mode as follows:

```python
from datasets import load_dataset

ds = load_dataset("common_voice", "ab", split="test")

ds = ds.cast_column("audio", Audio(sampling_rate=16_000))
```

However in streaming mode it fails currently:

```python
from datasets import load_dataset

ds = load_dataset("common_voice", "ab", split="test", streaming=True)

ds = ds.cast_column("audio", Audio(sampling_rate=16_000))
```

with the following error:

```
AttributeError: 'IterableDataset' object has no attribute 'cast_column'  
```

It would be great if we could add such a feature (I'm not 100% sure though how complex this would be)

**Comment by lhoestq** [comment]
This requires implementing `cast_column` for iterable datasets. It can also be useful to be able to disable the audio/image decoding for the dataset viewer cc @severo

**Comment by patrickvonplaten** [comment]
Just to clarify a bit. This feature is **always** needed when using the common voice dataset in streaming mode. So I think it's quite important
