### ISSUE TITLE
Dataset preview is not available (I think for all Hugging Face datasets)

### ISSUE THREAD

**Issue by Abirate** [huggingface/datasets#3479]
## Dataset viewer issue for '*french_book_reviews*'

**Link:** https://huggingface.co/datasets/Abirate/french_book_reviews

**short description of the issue**
For my dataset, the dataset preview is no longer functional (it used to work: The dataset had been added the day before and it was fine...)  
And, after looking over the datasets, I discovered that this issue affects all Hugging Face datasets (as of yesterday, December 23, 2021, around 10 p.m. (CET)).  
**Am I the one who added this dataset** :  Yes   

**Note**: here a screenshot showing the issue
![Dataset preview is not available for my dataset](https://user-images.githubusercontent.com/66887439/147333078-60734578-420d-4e91-8691-a90afeaa8948.jpg)  

**And here for glue dataset :**  

![Dataset preview is not available for other Hugging Face datasets(glue)](https://user-images.githubusercontent.com/66887439/147333492-26fa530c-befd-4992-8361-70c51397a25a.jpg)

**Comment by severo** [comment]
You're right, we have an issue today with the datasets preview. We're investigating.

**Comment by severo** [comment]
It should be fixed now. Thanks for reporting.

**Comment by severo** [comment]
Down again.

**Comment by severo** [comment]
Fixed for good.
