### ISSUE TITLE
skip columns which cannot set to specific format when set_format

### ISSUE THREAD

**Issue by tshu-w** [huggingface/datasets#3485]
**Is your feature request related to a problem? Please describe.**
When using `dataset.set_format("torch")`, I must make sure every columns in datasets can convert to `torch`, however, sometimes I want to keep some string columns.

**Describe the solution you'd like**
skip columns which cannot set to specific format when set_format instead of raise an error.

**Comment by bhavitvyamalik** [comment]
You can add columns that you wish to set into `torch` format using `dataset.set_format("torch", ['id', 'abc'])` so that input batch of the transform only contains those columns

**Comment by tshu-w** [comment]
Sorry, I miss `output_all_columns` args and thought after `dataset.set_format("torch", columns=columns)` I can only get specific columns I assigned.
