### ISSUE TITLE
wmt19 is broken (zh-en)

### ISSUE THREAD

**Issue by AjayP13** [huggingface/datasets#3522]
## Steps to reproduce the bug
```python
from datasets import load_dataset
dataset = load_dataset("wmt19", 'zh-en')
```

## Expected results
The dataset should download.

## Actual results
`ConnectionError: Couldn't reach ftp://cwmt-wmt:cwmt-wmt@datasets.nju.edu.cn/parallel/casia2015.zip`

## Environment info
- `datasets` version: 1.15.1
- Platform: Linux
- Python version: 3.8

**Comment by albertvillanova** [comment]
This issue is not reproducible.
