### ISSUE TITLE
Allow loading community metrics from the hub, just like datasets

### ISSUE THREAD

**Issue by eladsegal** [huggingface/datasets#3543]
**Is your feature request related to a problem? Please describe.**
Currently, I can load a metric implemented by me by providing the local path to the file in `load_metric`.
However, there is no option to do it with the metric uploaded to the hub.
This means that if I want to allow other users to use it, they must download it first which makes the usage less smooth.

**Describe the solution you'd like**
Load metrics from the hub just like datasets are loaded.
In order to not break stuff, the convention can be to put the metric file in a "metrics" folder in the hub.

**Comment by eladsegal** [comment]
This is a great solution in the meantime, thanks!

**Comment by eladsegal** [comment]
Here's the code I used, in case it can be of help for someone else:
```python
import os, shutil
from huggingface_hub import hf_hub_download
def download_metric(repo_id, file_path):
    # repo_id: for models "username/model_name", for datasets "datasets/username/model_name"
    local_metric_path = hf_hub_download(repo_id=repo_id, filename=file_path)
    updated_local_metric_path = (os.path.dirname(local_metric_path) + os.path.basename(local_metric_path).replace(".", "_") + ".py")
    shutil.copy(local_metric_path, updated_local_metric_path)
    return updated_local_metric_path

metric = load_metric(download_metric(REPO_ID, FILE_PATH))
```

**Comment by eladsegal** [comment]
Solved with https://github.com/huggingface/evaluate 🤗

**Comment by julien-c** [comment]
Yay!! cc @lvwerra @sashavor @douwekiela 

Please share your feedback @eladsegal =)
