### ISSUE TITLE
ConnectionError in IndicGLUE dataset

### ISSUE THREAD

**Issue by sahoodib** [huggingface/datasets#3572]
While I am trying to load IndicGLUE dataset (https://huggingface.co/datasets/indic_glue) it is giving me with the error:
```
ConnectionError: Couldn't reach https://storage.googleapis.com/ai4bharat-public-indic-nlp-corpora/evaluations/wikiann-ner.tar.gz (error 403)

**Comment by albertvillanova** [comment]
@sahoodib, thanks for reporting.

Indeed, none of the data links appearing in the IndicGLUE website are working, e.g.: https://storage.googleapis.com/ai4bharat-public-indic-nlp-corpora/evaluations/soham-articles.tar.gz
```
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for the owning project is disabled in state delinquent
</Details>
</Error>
```

We are contacting the data owners to inform them about their issue and ask them if they plan to fix it.

**Comment by albertvillanova** [comment]
Yesterday I resent a reminder email with more AI4Bharat-related people in the loop.

**Comment by albertvillanova** [comment]
We have received a reply from the authors reporting they have updated the URLs of their data files and opened a PR. See:
- #4978
