### ISSUE TITLE
Dataset Viewer not showing Previews for Private Datasets

### ISSUE THREAD

**Issue by abidlabs** [huggingface/datasets#3604]
## Dataset viewer issue for 'abidlabs/test-audio-13'

It seems that the dataset viewer does not show previews for `private` datasets, even for the user who's private dataset it is. See [1] for example. If I change the visibility to public, then it does show, but it would be useful to have the viewer even for private datasets.

![image](https://user-images.githubusercontent.com/1778297/150200515-93ff1545-11fd-4793-be64-6bed3cd895e2.png)

**Link:** 

[1] https://huggingface.co/datasets/abidlabs/test-audio-13

**Am I the one who added this dataset?** 

Yes

**Comment by severo** [comment]
Sure, it's on the roadmap.

**Comment by severo** [comment]
Closing in favor of https://github.com/huggingface/datasets-server/issues/39.
