### ISSUE TITLE
Consider adding `ipywidgets` as a dependency.

### ISSUE THREAD

**Issue by koaning** [huggingface/datasets#3621]
When I install `datasets` in a fresh virtualenv with jupyterlab I always see this error. 

```
ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

It's a bit of a nuisance, because I need to run shut down the jupyterlab server in order to install the required dependency. Might it be an option to just include it as a dependency here?

**Comment by mariosasko** [comment]
Hi! We use `tqdm` to display progress bars, so I suggest you open this issue in their repo.

**Comment by koaning** [comment]
It depends on how you use `tqdm`, no? 

Doesn't this library import via; 

```
from tqdm.notebook import tqdm
```

**Comment by mariosasko** [comment]
Hi! Sorry for the late reply. We import `tqdm` as `from tqdm.auto import tqdm`, which should be equal to `from tqdm.notebook import tqdm` in Jupyter/Colab.

**Comment by koaning** [comment]
Any objection if I make a PR that checks if the widgets library is installed beforehand?
