### ISSUE TITLE
`load_dataset("snli")` is different from dataset viewer

### ISSUE THREAD

**Issue by pietrolesci** [huggingface/datasets#3673]
## Describe the bug
The dataset that is downloaded from the Hub via `load_dataset("snli")` is different from what is available in the dataset viewer. In the viewer the labels are not encoded (i.e., "neutral", "entailment", "contradiction"), while the downloaded dataset shows the encoded labels (i.e., 0, 1, 2).

Is this expected? 

## Environment info

- `datasets` version:
- Platform: Ubuntu 20.4
- Python version: 3.7

**Comment by severo** [comment]
Yes, we decided to replace the encoded label with the corresponding label when possible in the dataset viewer. But
1. maybe it's the wrong default
2. we could find a way to show both (with a switch, or showing both ie. `0 (neutral)`).

**Comment by pietrolesci** [comment]
Hi @severo,

Thanks for clarifying. 

I think this default is a bit counterintuitive for the user. However, this is a personal opinion that might not be general. I think it is nice to have the actual (non-encoded) labels in the viewer. On the other hand, it would be nice to match what the user sees with what they get when they download a dataset. I don't know - I can see the difficulty of choosing a default :)
Maybe having non-encoded labels as a default can be useful?

Anyway, I think the issue has been addressed. Thanks a lot for your super-quick answer!

**Comment by severo** [comment]
Thanks for the 👍  in https://github.com/huggingface/datasets/issues/3673#issuecomment-1029008349, but as I proposed various solutions, it does not help me chose between them. Could you write your preferences as a comment?

**Comment by pietrolesci** [comment]
As I am working with seq2seq, I prefer having the label in string form rather than numeric. So the viewer is fine and the underlying dataset should be "decoded" (from int to str). In this way, the user does not have to search for a mapping `int -> original name` (even though is trivial to find, I reckon). Also, encoding labels is rather easy.

I hope this is useful

**Comment by lhoestq** [comment]
I like the idea of "0 (neutral)". The label name can even be greyed to make it clear that it's not part of the actual item in the dataset, it's just the meaning.

**Comment by mariosasko** [comment]
I like @lhoestq's idea of having grayed-out labels.

**Comment by severo** [comment]
Proposals by @gary149. Which one do you prefer? Please vote with the thumbs

- 👍 

    ![image](https://user-images.githubusercontent.com/1676121/152387949-883c7d7e-a9f3-48aa-bff9-11a691555e6e.png)

- 👎 

    ![image (1)](https://user-images.githubusercontent.com/1676121/152388061-32d95e42-cade-4ae4-9a77-7365e7b72b8f.png)

**Comment by pietrolesci** [comment]
I like Option 1 better as it shows clearly what the user is downloading

**Comment by severo** [comment]
Thanks!

**Comment by lhoestq** [comment]
Love it ! thanks :)
