### ISSUE TITLE
Add CodeContests dataset

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets#3675]
## Adding a Dataset
- **Name:** CodeContests
- **Description:** CodeContests is a competitive programming dataset for machine-learning.
- **Paper:**
- **Data:** https://github.com/deepmind/code_contests
- **Motivation:** This dataset was used when training [AlphaCode](https://deepmind.com/blog/article/Competitive-programming-with-AlphaCode).

Instructions to add a new dataset can be found [here](https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md).

**Comment by gchhablani** [comment]
@mariosasko Can I take this up?

**Comment by mariosasko** [comment]
This dataset is now available here: https://huggingface.co/datasets/deepmind/code_contests.
