### ISSUE TITLE
Cannot preview dataset

### ISSUE THREAD

**Issue by frascuchon** [huggingface/datasets#3755]
## Dataset viewer issue for '*rubrix/news*'

**Link:https://huggingface.co/datasets/rubrix/news** *link to the dataset viewer page*

Cannot see the dataset preview:

```
Status code:   400
Exception:     Status400Error
Message:       Not found. Cache is waiting to be refreshed.
```
Am I the one who added this dataset ? No

**Comment by severo** [comment]
Thanks for reporting. The dataset viewer depends on some backend treatments, and for now, they might take some hours to get processed. We're working on improving it.

**Comment by frascuchon** [comment]
Thanks for the info @severo !
