### ISSUE TITLE
Not be able to download dataset - "Newsroom"

### ISSUE THREAD

**Issue by Darshan2104** [huggingface/datasets#3778]
Hello,

I tried to download the **newsroom** dataset but it didn't work out for me. it said me to **download it manually**!

For manually, Link is also didn't work! It is sawing some ad or something!

If anybody has solved this issue please help me out or if somebody has this dataset please share your google drive link, it would be a great help!

Thanks
Darshan Tank

**Comment by albertvillanova** [comment]
Hi @Darshan2104, thanks for reporting.

Please note that at Hugging Face we do not host the data of this dataset, but just a loading script pointing to the host of the data owners.

Apparently the data owners changed their data host server. After googling it, I found their new website at: https://lil.nlp.cornell.edu/newsroom/index.html
- Download page: https://lil.nlp.cornell.edu/newsroom/download/index.html

I'm fixing the link in our Datasets library.

**Comment by Darshan2104** [comment]
@albertvillanova Thanks for the solution and link you made my day!
