### ISSUE TITLE
NonMatchingChecksumError in xcopa dataset

### ISSUE THREAD

**Issue by afcruzs-ms** [huggingface/datasets#3807]
## Describe the bug
Loading the xcopa dataset doesn't work, it fails due to a mismatch in the checksum.

## Steps to reproduce the bug
```python
from datasets import load_dataset
dataset = load_dataset("xcopa", "it")
```

## Expected results
The dataset should be loaded correctly.

## Actual results
Fails with:
```python
in verify_checksums(expected_checksums, recorded_checksums, verification_name)
     38     if len(bad_urls) > 0:
     39         error_msg = "Checksums didn't match" + for_verification_name + ":\n"
---> 40         raise NonMatchingChecksumError(error_msg + str(bad_urls))
     41     logger.info("All the checksums matched successfully" + for_verification_name)
     42 

NonMatchingChecksumError: Checksums didn't match for dataset source files:
['https://github.com/cambridgeltl/xcopa/archive/master.zip']
```

## Environment info

- `datasets` version: 1.18.3, and 1.18.4.dev0
- Platform:
- Python version: 3.8
- PyArrow version:

**Comment by afcruzs-ms** [comment]
@albertvillanova here's a separate issue for a bug similar to #3792

**Comment by albertvillanova** [comment]
Hi @afcruzs-ms, thanks for opening this separate issue for your problem.

The root problem in the other issue (#3792) was a change in the service of Google Drive.

But in your case, the `xcopa` dataset is not hosted on Google Drive. Therefore, the root cause is a different one.

Let me look at it...

**Comment by afcruzs-ms** [comment]
It works indeed, thanks!

**Comment by albertvillanova** [comment]
Thanks @labouz for reporting: yes, better opening a new GitHub issue as you did. I'm addressing it:
- #4376
