### ISSUE TITLE
Missing google file for `multi_news` dataset

### ISSUE THREAD

**Issue by severo** [huggingface/datasets#3896]
## Dataset viewer issue for '*multi_news*'

**Link:** https://huggingface.co/datasets/multi_news

```
Server error

Status code:   400
Exception:     FileNotFoundError
Message:       https://drive.google.com/uc?export=download&id=1vRY2wM6rlOZrf9exGTm5pXj5ExlVwJ0C/multi-news-original/train.src
```

Am I the one who added this dataset ? No

**Comment by severo** [comment]
reported by @abidlabs

**Comment by severo** [comment]
related to https://github.com/huggingface/datasets/pull/3843?

**Comment by albertvillanova** [comment]
That is. The PR #3843 was just opened a bit later we had made our 1.18.4 patch release...
Once merged, that will fix this issue.

**Comment by severo** [comment]
OK. Should fix the viewer for 50 datasets

<img width="148" alt="Capture d’écran 2022-03-14 à 11 51 02" src="https://user-images.githubusercontent.com/1676121/158157853-6c544a47-2d6d-4ac4-964a-6f10951ec36b.png">
