### ISSUE TITLE
Cannot preview cnn_dailymail dataset

### ISSUE THREAD

**Issue by hasan-besh** [huggingface/datasets#3969]
## Dataset viewer issue for '*cnn_dailymail*'

**Link:** https://huggingface.co/datasets/cnn_dailymail

*short description of the issue*

Am I the one who added this dataset ? Yes-No

**Comment by albertvillanova** [comment]
I guess the cache got corrupted due to a previous issue with Google Drive service.

The cache should be regenerated, e.g. by passing `download_mode="force_redownload"`.

CC: @severo

**Comment by albertvillanova** [comment]
Yes @lhoestq, I didn't explain myself well: my previous message was addressed to @severo.

**Comment by severo** [comment]
I remove the tag dataset-viewer, since it's more an issue with the hosting on Google Drive

**Comment by lhoestq** [comment]
Sounds good. I was looking for another host of this dataset but couldn't find any (yet)

**Comment by severo** [comment]
It seems like the issue is with the streaming mode, not with the hosting:

```python
>>> import datasets
>>> dataset = datasets.load_dataset('cnn_dailymail', name="3.0.0", split="train", streaming=True, download_mode="force_redownload")
Downloading builder script: 9.35kB [00:00, 10.2MB/s]
Downloading metadata: 9.50kB [00:00, 12.2MB/s]
>>> len(list(dataset))
0
>>> dataset = datasets.load_dataset('cnn_dailymail', name="3.0.0", split="train", streaming=False)
Reusing dataset cnn_dailymail (/home/slesage/.cache/huggingface/datasets/cnn_dailymail/3.0.0/3.0.0/3cb851bf7cf5826e45d49db2863f627cba583cbc32342df7349dfe6c38060234)
>>> len(dataset)
287113
```

Note, in particular, that the streaming mode is failing silently, returning 0 row while I would have expected an exception instead. The result is that the dataset viewer shows `No data` instead of a detailed error.

<img width="1511" alt="Capture d’écran 2022-04-12 à 11 50 46" src="https://user-images.githubusercontent.com/1676121/162935341-d50f1e73-d053-41d4-917f-e79708a0ca23.png">

**Comment by severo** [comment]
Do you think that `datasets` should detect this anyway and throw an exception?

**Comment by albertvillanova** [comment]
Indeed, streaming was not supported: tgz archives were not properly iterated.

I've opened a PR to support streaming.

However, keep in mind that Google Drive will keep generating issues from time to time, like 403,...
