### ISSUE TITLE
[Feature] Keep the list of labels of a dataset as metadata

### ISSUE THREAD

**Issue by jplu** [huggingface/datasets#4]
It would be useful to keep the list of the labels of a dataset as metadata. Either directly in the `DatasetInfo` or in the Arrow metadata.

**Comment by chiapas** [comment]
Hi,
I hope we could get a better documentation.
It took me more than 1 hour to found this way to get the label information.

**Comment by thomwolf** [comment]
Yes we are working on the doc right now, should be in the next release quite soon.
