### ISSUE TITLE
How to use generate this multitask dataset for SQUAD? I am getting a value error. 

### ISSUE THREAD

**Issue by gsk1692** [huggingface/datasets#4001]
## Dataset viewer issue for 'squad_multitask*'

**Link:** https://huggingface.co/datasets/vershasaxena91/squad_multitask

*short description of the issue*

I am trying to generate the multitask dataset for squad dataset. However, gives the error in dataset explorer as well as my local machine. 
I tried the command: dataset = load_dataset("vershasaxena91/squad_multitask", 'highlight_qg_format')
Error:
Status code:   400
Exception:     TypeError
Message:       argument of type 'Value' is not iterable

Kindly advice.

**Comment by mariosasko** [comment]
Hi! Replacing `nlp.<obj>` with `datasets.<obj>` in the script should fix the problem. `nlp` has been renamed to `datasets` more than a year ago, so please use `datasets` instead to avoid weird issues.

**Comment by gsk1692** [comment]
Thank You! Was able to solve with the help of this.

**Comment by gsk1692** [comment]
But I request you to please fix the same in the dataset hub explorer as well...

**Comment by tonyken12345** [comment]
May I ask how to get this dataset?
