### ISSUE TITLE
can't download cats_vs_dogs dataset

### ISSUE THREAD

**Issue by RRaphaell** [huggingface/datasets#4032]
## Describe the bug
can't download cats_vs_dogs dataset. error: Checksums didn't match for dataset source files

## Steps to reproduce the bug
```python
from datasets import load_dataset
dataset = load_dataset("cats_vs_dogs")
```

## Expected results
loaded successfully.

## Actual results
NonMatchingChecksumError: Checksums didn't match for dataset source files:
['https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip']

## Environment info
fresh google colab notebook

**Comment by albertvillanova** [comment]
Thnaks for reporting @RRaphaell.

We are fixing it.
