### ISSUE TITLE
Modify datatype from `int32` to `float` for pearsonr, spearmanr.

### ISSUE THREAD

**Issue by woodywarhol9** [huggingface/datasets#4053]
**Is your feature request related to a problem? Please describe.**
- Now [Pearsonr](https://github.com/huggingface/datasets/blob/master/metrics/pearsonr/pearsonr.py) and [Spearmanr](https://github.com/huggingface/datasets/blob/master/metrics/spearmanr/spearmanr.py) both get input data as 'int32'. 

**Describe the solution you'd like**
- Considering that those metrics are widely used for the STS task(labels are in 'float' data type),
it would be better to modify datatype from 'int32' to 'float' for getting exact values of similarity.

**Comment by albertvillanova** [comment]
@Woodywarhol9 good catch, thanks for reporting.

We are fixing this.
