### ISSUE TITLE
Add CCAgT dataset

### ISSUE THREAD

**Issue by johnnv1** [huggingface/datasets#4075]
## Adding a Dataset
- **Name:** CCAgT dataset: Images of Cervical Cells with AgNOR Stain Technique
- **Description:** The dataset contains 2540 images (1600x1200 where each pixel is 0.111μm×0.111μm) from three different slides, having at least one nucleus per image. These images are from fields belonging to a sample cervical slide, colored with silver-stained, a method known as Argyrophilic Nucleolar Organizer Regions (AgNOR).
- **Paper:** https://doi.org/10.1109/cbms49503.2020.00110
- **Data:** https://arquivos.ufsc.br/d/373be2177a33426a9e6c/ or https://drive.google.com/drive/u/4/folders/1TBpYCv6S1ydASLauSzcsvO7Wc5O-WUw0
- **Motivation:** This is a unique dataset (because of the stain), for a major health problem, cervical cancer, with real data.

Instructions to add a new dataset can be found [here](https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md).

Hi, this is a public version of the dataset that I have been working on, soon we will have another version of this dataset. But until this new version goes out, I thought I would add this dataset here, if it makes sense for the repository. You can assign the task to me if possible

**Comment by lhoestq** [comment]
Awesome ! Let us know if you have questions or if we can help ;) I'm assigning you

PS: if possible, please try to not use Google Drive links in your dataset script, since Google Drive has download quotas and is not always reliable.

**Comment by johnnv1** [comment]
HI, I was waiting to come out in the second version to do the implementation.

- Paper: https://ssrn.com/abstract=4126881
- Data: [Data mendelay](http://doi.org/10.17632/wg4bpm33hj.2)

**Comment by lhoestq** [comment]
Nice ! 🚀

**Comment by johnnv1** [comment]
The link of CCAgT dataset is: https://huggingface.co/datasets/lapix/CCAgT
