### ISSUE TITLE
elena-soare/crawled-ecommerce: missing dataset

### ISSUE THREAD

**Issue by seevaratnam** [huggingface/datasets#4093]
elena-soare/crawled-ecommerce

**Link:** *link to the dataset viewer page*

*short description of the issue*

Am I the one who added this dataset ? Yes-No

**Comment by severo** [comment]
It's a bug! Thanks for reporting, I'm looking at it.

**Comment by severo** [comment]
By the way, the error on our part is due to the huge size of every row (~90MB). The dataset viewer does not support such big dataset rows for the moment.
Anyway, we're working to give a hint about this in the dataset viewer.

**Comment by severo** [comment]
Fixed. See https://huggingface.co/datasets/elena-soare/crawled-ecommerce/viewer/elena-soare--crawled-ecommerce/train.

<img width="1552" alt="Capture d’écran 2022-04-12 à 11 23 51" src="https://user-images.githubusercontent.com/1676121/162929722-2e2b80e2-154a-4b61-87bd-e341bd6c46e6.png">

Thanks for reporting!
