### ISSUE TITLE
RGBA images not showing

### ISSUE THREAD

**Issue by cceyda** [huggingface/datasets#4160]
## Dataset viewer issue for ceyda/smithsonian_butterflies_transparent

[**Link:** *link to the dataset viewer page*](https://huggingface.co/datasets/ceyda/smithsonian_butterflies_transparent)

![image](https://user-images.githubusercontent.com/15624271/163117683-e91edb28-41bf-43d9-b371-5c62e14f40c9.png)

Am I the one who added this dataset ? Yes

👉  More of a general issue of 'RGBA' png images not being supported 
(the dataset itself is just for the huggan sprint and not that important, consider it just an example)

**Comment by severo** [comment]
Thanks for reporting. It's a known issue, and we hope to fix it soon.

**Comment by severo** [comment]
Fixed, thanks!
