### ISSUE TITLE
Support streaming FLEURS dataset

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/datasets#4181]
## Dataset viewer issue for '*name of the dataset*'

https://huggingface.co/datasets/google/fleurs

```
Status code:   400
Exception:     NotImplementedError
Message:       Extraction protocol for TAR archives like 'https://storage.googleapis.com/xtreme_translations/FLEURS/af_za.tar.gz' is not implemented in streaming mode. Please use `dl_manager.iter_archive` instead.
```

Am I the one who added this dataset ? Yes

Can I fix this somehow in the script? @lhoestq @severo

**Comment by lhoestq** [comment]
Yes, you just have to use `dl_manager.iter_archive` instead of `dl_manager.download_and_extract`.

That's because `download_and_extract` doesn't support TAR archives in streaming mode.

**Comment by polinaeterna** [comment]
@patrickvonplaten hm I think the metadata file should be found before audios as audios are contained in a folder next to metadata files (just as in common voice), so the metadata files should be "on top of the list".

**Comment by polinaeterna** [comment]
@patrickvonplaten I think the metadata file should be found first because the audio files are contained in a folder next to the metadata files (just as in common voice), so the metadata files should be "on top of the list"

**Comment by polinaeterna** [comment]
@patrickvonplaten but apparently it doesn't... I don't really know why.

**Comment by patrickvonplaten** [comment]
Yeah! Any ideas what could be the reason here? cc @lhoestq ?

**Comment by lhoestq** [comment]
The order of the files is determined when the TAR archive is created, depending on the commands the creator ran.
If the metadata file is not at the beginning of the file, that makes streaming completely inefficient. In this case the TAR archive needs to be recreated in an appropriate order.

**Comment by patrickvonplaten** [comment]
Actually we could maybe just host the metadata file ourselves and then stream the audio data only. Don't think that this would be a problem for the FLEURS authors (I can ask them :-))

**Comment by albertvillanova** [comment]
I'm closing this issue as the PR above has been merged.
