### ISSUE TITLE
The data preview of XGLUE

### ISSUE THREAD

**Issue by czq1999** [huggingface/datasets#4247]
It seems that something wrong with the data previvew of XGLUE

**Comment by albertvillanova** [comment]
Thanks for reporting @czq1999.

Note that the dataset viewer uses the dataset in streaming mode and that not all datasets support streaming yet.

That is the case for XGLUE dataset (as the error message points out): this must be refactored to support streaming.

**Comment by severo** [comment]
Fixed, thanks @albertvillanova !

https://huggingface.co/datasets/xglue

<img width="824" alt="Capture d’écran 2022-04-29 à 10 23 14" src="https://user-images.githubusercontent.com/1676121/165909391-9f98d98a-665a-4e57-822d-8baa2dc9b7c9.png">
