### ISSUE TITLE
Issues: Adding a FAISS or Elastic Search index to a Dataset

### ISSUE THREAD

**Issue by nsankar** [huggingface/datasets#439]
It seems the DPRContextEncoder, DPRContextEncoderTokenizer cited[ in this documentation](https://huggingface.co/nlp/faiss_and_ea.html) is not implemented ? It didnot work with the standard nlp installation . Also, I couldn't find or use it with the latest nlp install from github in Colab.  Is  there any dependency on the latest PyArrow 1.0.0 ? Is it yet to be made generally available ?

**Comment by lhoestq** [comment]
`DPRContextEncoder` and `DPRContextEncoderTokenizer` will be available in the next release of `transformers`.

Right now you can experiment with it by installing `transformers` from the master branch.
You can also check the docs of DPR [here](https://huggingface.co/transformers/master/model_doc/dpr.html).

Moreover all the indexing features will also be available in the next release of `nlp`.

**Comment by nsankar** [comment]
@lhoestq Thanks for the info

**Comment by nsankar** [comment]
@lhoestq  I tried installing transformer from the master branch. Python import didnt' work.  Anyways, Looking forward to trying it in the next release of nlp

**Comment by yjernite** [comment]
@nsankar have you tried with the latest version of the library?

**Comment by nsankar** [comment]
@yjernite it worked. Thanks
