### ISSUE TITLE
Dataset Viewer issue for conll2012_ontonotesv5

### ISSUE THREAD

**Issue by jiangwy99** [huggingface/datasets#4407]
### Link

https://huggingface.co/datasets/conll2012_ontonotesv5

### Description

Dataset viewer outage.

### Owner

No

**Comment by albertvillanova** [comment]
Thanks for reporting, @jiangwy99.

I guess this might be addressed once we fix our issue with irresponsive backend endpoint.

CC: @severo

**Comment by albertvillanova** [comment]
I've just sent the forcing of the refresh of the preview to the new endpoint.

**Comment by severo** [comment]
Fixed, thanks for the patience. The issue was the amount of RAM allowed to extract the first rows of the dataset was not sufficient.
