### ISSUE TITLE
Add loading variable number of columns for different splits

### ISSUE THREAD

**Issue by DrMatters** [huggingface/datasets#4426]
**Is your feature request related to a problem? Please describe.**
The original dataset `blended_skill_talk` consists of different sets of columns for the different splits: (test/valid) splits have additional data column `label_candidates` that the (train) doesn't have.
When loading such data, an exception occurs at table.py:cast_table_to_schema, because of mismatched columns.

**Comment by mariosasko** [comment]
Hi! Indeed the column is missing, but you shouldn't get an error? Have you made some modifications to the script? I've opened a PR to add the missing columns to the loading script.
