### ISSUE TITLE
Dataset Viewer issue for amazon_polarity

### ISSUE THREAD

**Issue by lewtun** [huggingface/datasets#4442]
### Link

https://huggingface.co/datasets/amazon_polarity/viewer/amazon_polarity/test

### Description

For some reason the train split is OK but the test split is not for this dataset:

```
Server error
Status code:   400
Exception:     FileNotFoundError
Message:       [Errno 2] No such file or directory: '/cache/modules/datasets_modules/datasets/amazon_polarity/__init__.py'
```

### Owner

No

**Comment by severo** [comment]
Thanks, looking at it

**Comment by severo** [comment]
Not sure what happened 😬, but it's fixed
