### ISSUE TITLE
Dataset Viewer issue for Yaxin/SemEval2015

### ISSUE THREAD

**Issue by WithYouTo** [huggingface/datasets#4453]

**Comment by severo** [comment]
I understand that the issue is that a remote file (URL) is being loaded as a local file. Right @albertvillanova @lhoestq?

```
Message:       [Errno 2] No such file or directory: 'https://raw.githubusercontent.com/YaxinCui/ABSADataset/main/SemEval2015Task12Corrected/train/restaurants_train.xml'
```

**Comment by lhoestq** [comment]
`xml.dom.minidom.parse` is not supported in streaming mode. I opened a PR here to fix it:
https://huggingface.co/datasets/Yaxin/SemEval2015/discussions/1

Please review the PR @WithYouTo and let me know if it works !

**Comment by albertvillanova** [comment]
Additionally, I'm also patching our library, so that we support streaming datasets that use `xml.dom.minidom.parse`.
