### ISSUE TITLE
AttributeError: module 'datasets' has no attribute 'load_dataset'

### ISSUE THREAD

**Issue by AlexNLP** [huggingface/datasets#4461]
## Describe the bug
I have piped install datasets, but this package doesn't have these attributes: load_dataset, load_metric.

## Environment info
- `datasets` version: 1.9.0
- Platform: Linux-5.13.0-44-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.6.13
- PyArrow version: 6.0.1

**Comment by HarperHao** [comment]
I'm having the same issue，Can you tell me how to fix it？

**Comment by jrt-20** [comment]
I have the same issue, can you tell me how to solve it? Thanks

**Comment by briandw** [comment]
I'm seeing the same issue in datasets.__version__ '2.17.0'

**Comment by izellevy** [comment]
@briandw your comment saved my day 👍
