### ISSUE TITLE
CI error with repo lhoestq/_dummy

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#4471]
## Describe the bug
CI is failing because of repo "lhoestq/_dummy". See: https://app.circleci.com/pipelines/github/huggingface/datasets/12461/workflows/1b040b45-9578-4ab9-8c44-c643c4eb8691/jobs/74269
```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/datasets/lhoestq/_dummy?full=true
```

The repo seems to no longer exist: https://huggingface.co/api/datasets/lhoestq/_dummy
```
error: "Repository not found"
```

CC: @lhoestq

**Comment by lhoestq** [comment]
fixed by https://github.com/huggingface/datasets/pull/4472
