### ISSUE TITLE
How to let `load_dataset` return a `Dataset` instead of `DatasetDict` in customized loading script

### ISSUE THREAD

**Issue by liyucheng09** [huggingface/datasets#4507]
If the dataset does not need splits, i.e., no training and validation split, more like a table. How can I let the `load_dataset` function return a `Dataset` object directly rather than return a `DatasetDict` object with only one key-value pair.

Or I can paraphrase the question in the following way: how to skip `_split_generators` step in `DatasetBuilder` to let `as_dataset` gives a single `Dataset` rather than a list`[Dataset]`?

Many thanks for any help.

**Comment by albertvillanova** [comment]
Hi @liyucheng09.

Users can pass the `split` parameter to `load_dataset`. For example, if your split name is "train",
```python
ds = load_dataset("dataset_name", split="train")
```
will return a `Dataset` instance.

**Comment by liyucheng09** [comment]
@albertvillanova Thanks! I can't believe I didn't know this feature till now.
