### ISSUE TITLE
Dataset Viewer issue for CSV datasets

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/datasets#4531]
### Link

https://huggingface.co/datasets/scikit-learn/breast-cancer-wisconsin

### Description

I'm populating CSV datasets [here](https://huggingface.co/scikit-learn) but the viewer is not enabled and it looks for a dataset loading script, the datasets aren't on queue as well. 

You can replicate the problem by simply uploading any CSV dataset.

### Owner

Yes

**Comment by julien-c** [comment]
this should now be fixed

**Comment by severo** [comment]
Confirmed, it's fixed now. Thanks @coyotte508
