### ISSUE TITLE
FileNotFoundError when passing a data_file inside a directory starting with double underscores

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets#4549]
Bug experienced in the `accelerate` CI: https://github.com/huggingface/accelerate/runs/7016055148?check_suite_focus=true

This is related to https://github.com/huggingface/datasets/pull/4505 and the changes from https://github.com/huggingface/datasets/pull/4412

**Comment by daavoo** [comment]
I have consistently experienced this bug on GitHub actions when bumping to `2.3.2`

**Comment by lhoestq** [comment]
We're working on a fix ;)
