### ISSUE TITLE
Dataset Viewer issue for allocine

### ISSUE THREAD

**Issue by lewtun** [huggingface/datasets#4562]
### Link

https://huggingface.co/datasets/allocine

### Description

Not sure if this is a problem with `bz2` compression, but I thought these datasets could be streamed:

```
Status code:   400
Exception:     AttributeError
Message:       'TarContainedFile' object has no attribute 'readable'
```

### Owner

No

**Comment by severo** [comment]
I removed my assignment as @huggingface/datasets should be able to answer better than me

**Comment by albertvillanova** [comment]
Let me have a look...

**Comment by lewtun** [comment]
Thanks for the quick fix @albertvillanova

**Comment by albertvillanova** [comment]
Note that the underlying issue is that datasets containing TAR files are not streamable out of the box: they need being iterated with `dl_manager.iter_archive` to avoid performance issues because they access their file content *sequentially* (no random access).

**Comment by lewtun** [comment]
> Note that the underlying issue is that datasets containing TAR files are not streamable out of the box: they need being iterated with `dl_manager.iter_archive` to avoid performance issues because they access their file content _sequentially_ (no random access).

Ah thanks for the clarification! I'll look out for this next time and implement the fix myself :)
