### ISSUE TITLE
Document link #load_dataset_enhancing_performance points to nowhere

### ISSUE THREAD

**Issue by subercui** [huggingface/datasets#4566]
## Describe the bug

![image](https://user-images.githubusercontent.com/11674033/175752806-5b066b92-9d28-4771-9112-5c8606f07741.png)

The [load_dataset_enhancing_performance](https://huggingface.co/docs/datasets/v2.3.2/en/package_reference/main_classes#load_dataset_enhancing_performance) link [here](https://huggingface.co/docs/datasets/v2.3.2/en/package_reference/main_classes#datasets.Dataset.load_from_disk.keep_in_memory) points to nowhere, I guess it should point to https://huggingface.co/docs/datasets/v2.3.2/en/cache#improve-performance?

**Comment by mariosasko** [comment]
Hi! This is indeed the link the docstring should point to. Are you interested in submitting a PR to fix this?
