### ISSUE TITLE
Dataset Viewer issue for mlsum

### ISSUE THREAD

**Issue by lewtun** [huggingface/datasets#4572]
### Link

https://huggingface.co/datasets/mlsum/viewer/de/train

### Description

There's seems to be a problem with the download / streaming of this dataset:

```
Server error
Status code:   400
Exception:     BadZipFile
Message:       File is not a zip file
```

### Owner

No

**Comment by albertvillanova** [comment]
Thanks for reporting, @lewtun.

After investigation, it seems that the server https://gitlab.lip6.fr does not allow HTTP Range requests.

We are trying to find a workaround...
