### ISSUE TITLE
Dataset Viewer issue with False positive PII redaction

### ISSUE THREAD

**Issue by cakiki** [huggingface/datasets#4595]
### Link

https://huggingface.co/datasets/cakiki/rosetta-code

### Description

Hello, I just noticed an entry being redacted that shouldn't have been:

`RootMeanSquare@Range[10]` is being displayed as `[email protected][10]`

**Comment by severo** [comment]
The value is in the data, it's not an issue with the "dataset-viewer". Maybe open a PR: https://huggingface.co/datasets/cakiki/rosetta-code/discussions
