### ISSUE TITLE
Dataset Viewer issue for universal_dependencies

### ISSUE THREAD

**Issue by Jordy-VL** [huggingface/datasets#4596]
### Link

https://huggingface.co/datasets/universal_dependencies

### Description

invalid json response body at https://datasets-server.huggingface.co/splits?dataset=universal_dependencies reason: Unexpected token I in JSON at position 0

**Comment by severo** [comment]
Thanks, looking at it!

**Comment by severo** [comment]
Finally fixed! We updated the dataset viewer and it fixed the issue.

https://huggingface.co/datasets/universal_dependencies/viewer/aqz_tudet/train

<img width="1561" alt="Capture d’écran 2022-09-07 à 13 29 18" src="https://user-images.githubusercontent.com/1676121/188867795-4f7dd438-d4f2-46cd-8a92-20a37fb2d6bc.png">
