### ISSUE TITLE
Streaming issue for financial_phrasebank

### ISSUE THREAD

**Issue by lewtun** [huggingface/datasets#4597]
### Link

https://huggingface.co/datasets/financial_phrasebank/viewer/sentences_allagree/train

### Description

As reported by a community member using [AutoTrain Evaluate](https://huggingface.co/spaces/autoevaluate/model-evaluator/discussions/5#62bc217436d0e5d316a768f0), there seems to be a problem streaming this dataset:

```
Server error
Status code:   400
Exception:     Exception
Message:       Give up after 5 attempts with ConnectionError
```

### Owner

No

**Comment by severo** [comment]
cc @huggingface/datasets: it seems like https://www.researchgate.net/ is flaky too for hosting datasets.

**Comment by albertvillanova** [comment]
Let's see if their license allows hosting their data on the Hub.

**Comment by albertvillanova** [comment]
License is Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0).

We can host their data on the Hub.
