### ISSUE TITLE
Dataset Viewer issue for boris/gis_filtered

### ISSUE THREAD

**Issue by WaterKnight1998** [huggingface/datasets#4605]
### Link

https://huggingface.co/datasets/boris/gis_filtered/viewer/boris--gis_filtered/train

### Description

When I try to access this from the website I get this error:

Status code:   400
Exception:     ClientResponseError
Message:       401, message='Unauthorized', url=URL('https://huggingface.co/datasets/boris/gis_filtered/resolve/80b805053ce61d4eb487b6b8d9095d775c2c466e/data/train/0000.parquet')

If I try to load with code I also get the same issue: 
```python
dataset2_train=load_dataset("boris/gis_filtered", use_auth_token=os.environ["HF_TOKEN"],split="train",streaming=True)
dataset2_validation=load_dataset("boris/gis_filtered", use_auth_token=os.environ["HF_TOKEN"], split="validation",streaming=True)
```

### Owner

No

**Comment by severo** [comment]
Yes, this dataset is "gated": you first have to go to https://huggingface.co/datasets/boris/gis_filtered and click "Access repository" (if you accept to share your contact information with the repository authors).

**Comment by WaterKnight1998** [comment]
I already did that, it returns error when using streaming

**Comment by severo** [comment]
Oh, sorry, I misread. Looking at it. Maybe @huggingface/datasets or @SBrandeis

**Comment by lhoestq** [comment]
I could reproduce the error, even though I provided my token and accepted the gate form

**Comment by lhoestq** [comment]
This is indeed a bug in `datasets`. Parquet datasets in gated/private repositories can't be streamed properly, which caused the viewer to fail. I opened a PR at https://github.com/huggingface/datasets/pull/4608
