### ISSUE TITLE
Dataset Viewer issue for vadis/sv-ident

### ISSUE THREAD

**Issue by e-tornike** [huggingface/datasets#4635]
### Link

https://huggingface.co/datasets/vadis/sv-ident/viewer/default/validation

### Description

Error message when loading validation split in the viewer:

```
Status code:   400
Exception:     Status400Error
Message:       The split cache is empty.
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @e-tornike 

Some context:
- #4527 

The dataset loads locally in streaming mode:
```python
In [2]: from datasets import load_dataset; ds = load_dataset("vadis/sv-ident", split="validation", streaming=True); item = next(iter(ds)); item
Using custom data configuration default
Out[2]: 
{'sentence': 'Im Falle von Umweltbelastungen kann selten eindeutig entschieden werden, ob Unbedenklichkeitswerte bereits erreicht oder überschritten sind, die die menschliche Gesundheit oder andere Wohlfahrts»güter« beeinträchtigen.',
 'is_variable': 0,
 'variable': [],
 'research_data': [],
 'doc_id': '51971',
 'uuid': 'ee3d7f88-1a3e-4a59-997f-e986b544a604',
 'lang': 'de'}
```

**Comment by albertvillanova** [comment]
I have forced the refresh of the split in the preview without success.

**Comment by e-tornike** [comment]
Preview seems to work now. 

https://huggingface.co/datasets/vadis/sv-ident/viewer/default/validation

**Comment by albertvillanova** [comment]
OK, thank you @e-tornike.

After forcing the refresh, we just had to wait a little until it is effectively refreshed.

**Comment by e-tornike** [comment]
Thanks a lot! :)
