### ISSUE TITLE
Streaming issue for ccdv/pubmed-summarization

### ISSUE THREAD

**Issue by lewtun** [huggingface/datasets#4642]
### Link

https://huggingface.co/datasets/ccdv/pubmed-summarization

### Description

This was reported by a [user of AutoTrain Evaluate](https://huggingface.co/spaces/autoevaluate/model-evaluator/discussions/7). It seems like streaming doesn't work due to the way the dataset loading script is defined?

```
Status code:   400
Exception:     FileNotFoundError
Message:       https://huggingface.co/datasets/ccdv/pubmed-summarization/resolve/main/train.zip/train.txt
```

### Owner

No

**Comment by albertvillanova** [comment]
Thanks for reporting @lewtun.

I confirm there is an issue with streaming: it does not stream locally.

**Comment by albertvillanova** [comment]
Oh, after investigation, the source of the issue is in the Hub dataset loading script.

I'm opening a PR on the Hub dataset.

**Comment by albertvillanova** [comment]
I've opened a PR on their Hub dataset to support streaming: https://huggingface.co/datasets/ccdv/pubmed-summarization/discussions/2
