### ISSUE TITLE
Dataset Viewer issue for shamikbose89/lancaster_newsbooks

### ISSUE THREAD

**Issue by shamikbose** [huggingface/datasets#4720]
### Link

https://huggingface.co/datasets/shamikbose89/lancaster_newsbooks

### Description

Status code:   400
Exception:     ValueError
Message:       Cannot seek streaming HTTP file

I am able to use the dataset loading script locally and it also runs when I'm using the one from the hub, but the viewer still doesn't load

### Owner

Yes

**Comment by severo** [comment]
It seems like the list of splits could not be obtained:

```python
from datasets import get_dataset_split_names
get_dataset_split_names("shamikbose89/lancaster_newsbooks", "default")
```

ping @huggingface/datasets

**Comment by shamikbose** [comment]
Oh, I removed the 'split' key from `kwargs`. I put  it back in, but there's still the same error

**Comment by shamikbose** [comment]
@lhoestq Thanks! That seems to have solved it. I can get the splits with the `get_dataset_split_names()` function. The dataset viewer is still not loading properly, though. Maybe it's cached?
