### ISSUE TITLE
Dataset Viewer issue for yanekyuk/wikikey

### ISSUE THREAD

**Issue by ai-ashok** [huggingface/datasets#4746]

**Comment by lhoestq** [comment]
The dataset is empty, as far as I can tell: there are no files in the repository at https://huggingface.co/datasets/yanekyuk/wikikey/tree/main

Maybe the viewer can display a better message for empty datasets

**Comment by severo** [comment]
OK. Closing as it's not an error. We will work on making the error message a lot clearer.
