### ISSUE TITLE
Easily create loading script for benchmark comprising multiple huggingface datasets

### ISSUE THREAD

**Issue by JoelNiklaus** [huggingface/datasets#4750]
Hi,

I would like to create a loading script for a benchmark comprising multiple huggingface datasets.
The function _split_generators needs to return the files for the respective dataset. However, the files are not always in the same location for each dataset. I want to just make a wrapper dataset that provides a single interface to all the underlying datasets. 
I thought about downloading the files with the load_dataset function and then providing the link to the cached file. But this seems a bit inelegant to me. What approach would you propose to do this?

Please let me know if you have any questions.

Cheers,
Joel

**Comment by lhoestq** [comment]
Hi ! I think the simplest is to copy paste the `_split_generators` code from the other datasets and do a bunch of if-else, as in the glue dataset: https://huggingface.co/datasets/glue/blob/main/glue.py#L467

**Comment by JoelNiklaus** [comment]
Ok, I see. Thank you
