### ISSUE TITLE
TFDS wiki_dialog dataset to Huggingface dataset

### ISSUE THREAD

**Issue by djaym7** [huggingface/datasets#4863]
## Adding a Dataset
- **Name:** *Wiki_dialog*
- **Description: https://github.com/google-research/dialog-inpainting#:~:text=JSON%20object%2C%20for-,example,-%3A
- **Paper: https://arxiv.org/abs/2205.09073
- **Data: https://github.com/google-research/dialog-inpainting
- **Motivation:** *Research and Development on biggest corpus of dialog data*

Instructions to add a new dataset can be found [here](https://github.com/huggingface/datasets/blob/main/ADD_NEW_DATASET.md).

**Comment by djaym7** [comment]
@albertvillanova any help ? The linked dataset is in beam format which is similar to wikipedia dataset in huggingface that you  scripted..

**Comment by djaym7** [comment]
Nvm, I was able to port it to huggingface datasets, will upload to the hub soon

**Comment by djaym7** [comment]
https://huggingface.co/datasets/djaym7/wiki_dialog

**Comment by albertvillanova** [comment]
Thanks for the addition, @djaym7.
