### ISSUE TITLE
Dataset Viewer issue for subjqa

### ISSUE THREAD

**Issue by lewtun** [huggingface/datasets#4888]
### Link

https://huggingface.co/datasets/subjqa

### Description

Getting the following error for this dataset:

```
Status code:   500
Exception:     Status500Error
Message:       2 or more items returned, instead of 1
```

Not sure what's causing it though 🤔 

### Owner

Yes

**Comment by severo** [comment]
It's a bug in the viewer, thanks for reporting it. We're hoping to update to a new version in the next few days which should fix it.

**Comment by severo** [comment]
Fixed 

https://huggingface.co/datasets/subjqa

<img width="1040" alt="Capture d’écran 2022-09-08 à 10 23 26" src="https://user-images.githubusercontent.com/1676121/189073210-2a57ff88-8bb1-44bd-851e-0e75473cea3f.png">
