### ISSUE TITLE
Name the default config `default`

### ISSUE THREAD

**Issue by severo** [huggingface/datasets#4902]
Currently, if a dataset has no configuration, a default configuration is created from the dataset name.

For example, for a dataset loaded from the hub repository, such as https://huggingface.co/datasets/user/dataset (repo id is `user/dataset`), the default configuration will be `user--dataset`.

It might be easier to handle to set it to `default`, or another reserved word.

**Comment by mariosasko** [comment]
Addressed in #5331.
