### ISSUE TITLE
None Type error for swda datasets

### ISSUE THREAD

**Issue by hannan72** [huggingface/datasets#4907]
## Describe the bug
I got `'NoneType' object is not callable` error while calling the swda datasets.

## Steps to reproduce the bug
```python
from datasets import load_dataset
dataset = load_dataset("swda")
```

## Expected results
Run without error

## Environment info

- `datasets` version: 2.4.0
- Python version: 3.8.10

**Comment by lhoestq** [comment]
Thanks for reporting @hannan72 ! I couldn't reproduce the error on my side, can you share the full stack trace please ?

**Comment by hannan72** [comment]
Thanks a lot for your response @lhoestq 
The problem is solved accidentally today and I don't know exactly why it was happened yesterday.
The issue can be closed.

**Comment by lhoestq** [comment]
Ok, let us know if you encounter the issue again ;)
