### ISSUE TITLE
Keys mismatch: make error message more informative

### ISSUE THREAD

**Issue by PaulLerner** [huggingface/datasets#4917]
**Is your feature request related to a problem? Please describe.**
When loading a dataset from disk with a defect in its `dataset_info.json` describing its features (I don’t know when/why/how this happens but it deserves its own issue), you will get an error message like:
`ValueError: Keys mismatch: between {'bar': Value(dtype='int64', id=None)} and {'foo': Value(dtype='int64', id=None)}`

Which is fine when you have only a few features like in the example but it gets very hard to read when you have a lot of features in your dataset.

**Describe the solution you'd like**
The error message should give the difference between the features (what keys are in A but missing in B and vice-versa). It should also tell which keys are inferred from `dataset.arrow` and which come from `dataset_info.json`.

Willing to help :)

**Comment by lhoestq** [comment]
Good idea ! I think this can be improved in `Features.reorder_fields_as()` indeed at

https://github.com/huggingface/datasets/blob/7feeb5648a63b6135a8259dedc3b1e19185ee4c7/src/datasets/features/features.py#L1739-L1740

Is it something you would be interested in contributing ?

**Comment by daspartho** [comment]
Is this open to work on? I'd love to take on this as my first issue.

**Comment by PaulLerner** [comment]
Hi @daspartho I’ve opened a PR #4919 
I don’t think there’s much left to do

**Comment by daspartho** [comment]
ok : )
