### ISSUE TITLE
Dataset Viewer issue for pysentimiento/spanish-targeted-sentiment-headlines

### ISSUE THREAD

**Issue by finiteautomata** [huggingface/datasets#4918]
### Link

https://huggingface.co/datasets/pysentimiento/spanish-targeted-sentiment-headlines

### Description

After moving the dataset from my user (`finiteautomata`) to the `pysentimiento` organization, the dataset viewer says that it doesn't exist.

**Comment by severo** [comment]
Thanks for reporting, it's fixed now (I refreshed it manually). It's a known issue; we hope it will be fixed permanently in a few days.

<img width="1508" alt="Capture d’écran 2022-09-05 à 18 31 22" src="https://user-images.githubusercontent.com/1676121/188489762-0ed86a7e-dfb3-46e8-a125-43b815a2c6f4.png">

**Comment by finiteautomata** [comment]
Thanks @severo!
