### ISSUE TITLE
Dataset Viewer issue for ubuntu_dialogs_corpus

### ISSUE THREAD

**Issue by CibinQuadance** [huggingface/datasets#4935]

**Comment by severo** [comment]
The dataset maintainers (https://huggingface.co/datasets/ubuntu_dialogs_corpus) decided to forbid the dataset from being downloaded automatically (https://huggingface.co/docs/datasets/v2.4.0/en/loading#manual-download), and the dataset viewer respects this.
We will try to improve the error display though. Thanks for reporting.
