### ISSUE TITLE
Dataset without script does not support regular JSON data file

### ISSUE THREAD

**Issue by julien-c** [huggingface/datasets#4963]
### Link

https://huggingface.co/datasets/julien-c/label-studio-my-dogs

### Description

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/326577/189422048-7e9c390f-bea7-4521-a232-43f049ccbd1f.png">

### Owner

Yes

**Comment by albertvillanova** [comment]
Hi @julien-c,

Out of the box, we only support JSON lines (NDJSON) data files, but your data file is a regular JSON file. The reason is we use `pyarrow.json.read_json` and this only supports JSON lines.
