### ISSUE TITLE
Dataset Viewer issue for loubnabnl/humaneval-x

### ISSUE THREAD

**Issue by loubnabnl** [huggingface/datasets#5002]
### Link

https://huggingface.co/datasets/loubnabnl/humaneval-x/viewer/

### Description

The dataset has subsets but the viewer gets stuck in the default subset even when I select another one (the data loading of the subsets works fine)

### Owner

Yes

**Comment by severo** [comment]
It's a bug! Thanks for reporting, I'm looking at it

**Comment by severo** [comment]
Fixed.
