### ISSUE TITLE
would huggingface like publish cpp binding for datasets package ?

### ISSUE THREAD

**Issue by mullerhai** [huggingface/datasets#5013]
HI:
I use cpp env libtorch, I like use hugggingface ,but huggingface not cpp binding, would you like publish cpp binding for it.
thanks

**Comment by lhoestq** [comment]
Hi ! Can you share more information about your use case ? How could it help you to have cpp bindings versus using the python libraries ?

**Comment by mullerhai** [comment]
> Hi ! Can you share more information about your use case ? How could it help you to have cpp bindings versus using the python libraries ?

for example ,the huggingface  load_model() and load_dataset()  can  execute in cpp env

**Comment by lhoestq** [comment]
If it's a viable option for you, you can check [tch-rs](https://github.com/LaurentMazare/tch-rs) to load models in Rust. Regarding datasets, you can first download them in python and then use Arrow C++ or Rust to load them

**Comment by mariosasko** [comment]
If you are more adventurous, another option is to embed python calls inside c++ e.g. with `pybind11`.

**Comment by mullerhai** [comment]
> pybind11

I think it is not the best solution
