### ISSUE TITLE
I need to read the custom dataset in conll format

### ISSUE THREAD

**Issue by 506610466** [huggingface/datasets#5014]
I need to read the custom dataset in conll format

**Comment by mariosasko** [comment]
Hi! We don't currently have a builder for parsing custom `conll` datasets, but I guess we could add one as a packaged module (similarly to what [TFDS](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_builders/conll/conll_dataset_builder.py) did). @lhoestq @albertvillanova WDYT?

In the meantime, you can use `Dataset.from_generator` to create a dataset as follows:
```python
from datasets import Dataset

# 2009 version
INPUT_COLUMNS = "ID FORM LEMMA PLEMMA POS PPOS FEAT PFEAT HEAD PHEAD DEPREL PDEPREL".split()

def read_conll(file):
    example = {col: [] for col in INPUT_COLUMNS}
    idx = 0
    with open(file) as f:
        for line in f:
            if line.startswith("-DOCSTART-") or line == "\n" or not line:
                if example[next(iter(example))]:
                    yield idx, example
                idx += 1
                example = {col: [] for col in INPUT_COLUMNS}
            else:
                row_cols = line.split()
                for i, col in enumerate(example):
                    example[col] = row_cols[i].rstrip()

# (optional) pass custom features with `features=Features(...)`
dset = Dataset.from_generator(read_conll, gen_kwargs={"file": "path/to/conll/file"})   
```

**Comment by albertvillanova** [comment]
I think we could add a dedicated builder if you think this format is general enough.

**Comment by 506610466** [comment]
> I think we could add a dedicated builder if you think this format is general enough.

I think its functions are incomplete. It should have to_ Conll and from_ There are two methods of conll.

**Comment by Taghreed7878** [comment]
> Hi! We don't currently have a builder for parsing custom `conll` datasets, but I guess we could add one as a packaged module (similarly to what [TFDS](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_builders/conll/conll_dataset_builder.py) did). @lhoestq @albertvillanova WDYT?
> 
> In the meantime, you can use `Dataset.from_generator` to create a dataset as follows:
> 
> ```python
> from datasets import Dataset
> 
> # 2009 version
> INPUT_COLUMNS = "ID FORM LEMMA PLEMMA POS PPOS FEAT PFEAT HEAD PHEAD DEPREL PDEPREL".split()
> 
> def read_conll(file):
>     example = {col: [] for col in INPUT_COLUMNS}
>     idx = 0
>     with open(file) as f:
>         for line in f:
>             if line.startswith("-DOCSTART-") or line == "\n" or not line:
>                 if example[next(iter(example))]:
>                     yield idx, example
>                 idx += 1
>                 example = {col: [] for col in INPUT_COLUMNS}
>             else:
>                 row_cols = line.split()
>                 for i, col in enumerate(example):
>                     example[col] = row_cols[i].rstrip()
> 
> # (optional) pass custom features with `features=Features(...)`
> dset = Dataset.from_generator(read_conll, gen_kwargs={"file": "path/to/conll/file"})   
> ```

I'm trying to load a custom dataset in a Dataset object, it's similar to conll2003 but with 2 columns only (word entity), I used the following script:

features = datasets.Features(
{"tokens": datasets.Sequence(datasets.Value("string")),
"ner_tags": datasets.Sequence(
datasets.features.ClassLabel(
names=["B-PER", .... etc.]))}
)

from datasets import Dataset

INPUT_COLUMNS = "tokens ner_tags".split(" ")

def read_conll(file):
#all_labels = []
example = {col: [] for col in INPUT_COLUMNS}
idx = 0
with open(file) as f:
for line in f:
if line:
if line.startswith("-DOCSTART-") and example["tokens"] != []:
print(idx, example)
yield idx, example
idx += 1
example = {col: [] for col in INPUT_COLUMNS}
elif line == "\n" or (line.startswith("-DOCSTART-") and example["tokens"] == []):
continue
else:
row_cols = line.split(" ")
for i, col in enumerate(example):
example[col].append(row_cols[i].rstrip())

dset = Dataset.from_generator(read_conll, gen_kwargs={"file": "/content/new_train.txt"}, features = features)

The following error happened:
[/usr/local/lib/python3.7/dist-packages/datasets/utils/py_utils.py](https://localhost:8080/#) in (.0)
285 for key in unique_values(itertools.chain(*dicts)): # set merge all keys
286 # Will raise KeyError if the dict don't have the same keys
--> 287 yield key, tuple(d[key] for d in dicts)
288

TypeError: tuple indices must be integers or slices, not str

What does this mean and what should I modify?
