### ISSUE TITLE
Hendrycks Checksum

### ISSUE THREAD

**Issue by DanielHesslow** [huggingface/datasets#5039]
Hi, 
The checksum for [hendrycks_test](https://huggingface.co/datasets/hendrycks_test) does not compare correctly, I guess it has been updated on the remote.

```
datasets.utils.info_utils.NonMatchingChecksumError: Checksums didn't match for dataset source files:
['https://people.eecs.berkeley.edu/~hendrycks/data.tar']
```

**Comment by albertvillanova** [comment]
Thanks for reporting, @DanielHesslow. We are fixing it.

**Comment by DanielHesslow** [comment]
@albertvillanova thanks for taking care of this so quickly!

**Comment by albertvillanova** [comment]
The dataset metadata is fixed. You can download it normally.
