### ISSUE TITLE
Restore saved format state in `load_from_disk`

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets#5050]
Even though we save the `format` state in `save_to_disk`, we don't restore it in `load_from_disk`. We should fix that.
 
Reported here: https://discuss.huggingface.co/t/save-to-disk-loses-formatting-information/23815

**Comment by asofiaoliveira** [comment]
Hi, can I work on this?

**Comment by mariosasko** [comment]
Hi, sure! Let us know if you need some pointers/help.
