### ISSUE TITLE
Replace AssertionErrors with more meaningful errors

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets#5074]
Replace the AssertionErrors with more meaningful errors such as ValueError, TypeError, etc.

The files with AssertionErrors that need to be replaced:
```
src/datasets/arrow_reader.py
src/datasets/builder.py
src/datasets/utils/version.py
```

**Comment by galbwe** [comment]
Hi, can I pick up this issue?

**Comment by galbwe** [comment]
Looks like the top-level datasource directory was removed when https://github.com/huggingface/datasets/pull/4974 was merged, so there are 3 files to fix.
