### ISSUE TITLE
Throw EnvironmentError when token is not present

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets#5075]
Throw EnvironmentError instead of OSError ([link](https://github.com/huggingface/datasets/blob/6ad430ba0cdeeb601170f732d4bd977f5c04594d/src/datasets/arrow_dataset.py#L4306) to the line) in `push_to_hub` when the Hub token is not present.

**Comment by rahulXs** [comment]
@mariosasko I've raised a PR #5076 against this issue. Please help to review. Thanks.
