### ISSUE TITLE
Error in create a dataset from a Python generator

### ISSUE THREAD

**Issue by yangxuhui** [huggingface/datasets#5102]
## Describe the bug
In HOW-TO-GUIDES > Load > [Python generator](https://huggingface.co/docs/datasets/v2.5.2/en/loading#python-generator), the code example defines the `my_gen` function, but when creating the dataset, an undefined `my_dict` is passed in.  

```Python
>>> from datasets import Dataset
>>> def my_gen():
...    for i in range(1, 4):
...        yield {"a": i}
>>> dataset = Dataset.from_generator(my_dict)
```

**Comment by mariosasko** [comment]
Hi, thanks for reporting! The last line should be `dataset = Dataset.from_generator(my_gen)`.

**Comment by riccardobucco** [comment]
#self-assign
