### ISSUE TITLE
Progress bars have color red and never completed to 100%

### ISSUE THREAD

**Issue by echatzikyriakidis** [huggingface/datasets#5117]
## Describe the bug
Progress bars after transformative operations turn in red and never be completed to 100%

## Steps to reproduce the bug
```python
from datasets import load_dataset

load_dataset('rotten_tomatoes', split='test').filter(lambda o: True)
```

## Expected results
Progress bar should be 100% and green

## Actual results
Progress  bar turn in red and never completed to 100%

## Environment info
- `datasets` version: 2.6.1
- Platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.14
- PyArrow version: 6.0.1
- Pandas version: 1.3.5

**Comment by david1542** [comment]
Hi @echatzikyriakidis, thanks for submitting the issue.
Which shell are you using exactly? I tried to run the command you sent, but I don't see colors at all 🧐

#self-assign

**Comment by david1542** [comment]
#self-assign

**Comment by echatzikyriakidis** [comment]
Hi @david1542 ,

I use Google Colab.

**Comment by david1542** [comment]
Got it. I created a PR that fixes this issue. Turns out that the wrapping logic for the inner loop was slightly incorrect.

**Comment by echatzikyriakidis** [comment]
Thank you!

**Comment by 11301858** [comment]
Hello @mariosasko 

I am still facing this issue. Was this problem fixed?

![Screen Shot 2024-06-19 at 11 35 57 AM](https://github.com/huggingface/datasets/assets/66180831/cd9c6ac4-178c-4297-821c-a56411d34c89)

I cleared the hugging face cache before running, and no error message was given. Let me know if you need a minimal repro of my code.
