### ISSUE TITLE
Depracate `num_proc` parameter in `DownloadManager.extract`

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets#5132]
The `num_proc` parameter is only present in `DownloadManager.extract` but not in `StreamingDownloadManager.extract`, making it impossible to support streaming in the dataset scripts that use it (`openwebtext` and `the_pile_stack_exchange`). We can avoid this situation by deprecating this parameter and passing `DownloadConfig`'s `num_proc` to `map_nested` instead, as it's done in `DownloadManager.download`.

**Comment by lazarust** [comment]
I can take this!

**Comment by lazarust** [comment]
#self-assign

**Comment by ayushthe1** [comment]
@lazarust i'm already working on this issue :smile:

**Comment by ayushthe1** [comment]
#self-assign

**Comment by ayushthe1** [comment]
hey @mariosasko , i made a pr for this issue. Could you please review it.
