### ISSUE TITLE
Raise ImportError instead of OSError if required extraction library is not installed

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets#5134]
According to the official Python docs, `OSError` should be thrown in the following situations:
> This exception is raised when a system function returns a system-related error, including I/O failures such as “file not found” or “disk full” (not for illegal argument types or other incidental errors).

Hence, it makes more sense to raise `ImportError` instead of `OSError` when the required extraction/decompression library is not installed.

**Comment by ayushthe1** [comment]
hey ,i would like to work on this issue . Please assign it to me.

**Comment by ayushthe1** [comment]
hey @mariosasko , i made a pr for this issue. Could you please review it.
Also i found multiple `OSError` in `extract.py` file which i thought could be replaced too but wasn't sure about them.
Please do tell if that also needs to be done.
