### ISSUE TITLE
Fix language and license tag names in all Hub datasets

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#5158]
While working on this:
- #5137

we realized there are still many datasets with deprecated "languages" and "licenses" tag names (instead of "language" and "license").

This is a blocking issue: no subsequent PR can be opened to modify their metadata: a ValueError will be thrown.

We should fix the "language" and "license" tag names in all Hub datasets.

TODO:
- [x] Fix language and license tag names in 402 Hub datasets

**Comment by albertvillanova** [comment]
There are currently 402 datasets with deprecated "languages" or "licenses".

**Comment by ayushthe1** [comment]
hey @albertvillanova ,i will love to work on this issue if you like.

**Comment by albertvillanova** [comment]
Hi @ayushthe1, thanks for your offer.

But as you can see, I self-assigned this issue.

I have already fixed 200 out of the 402 datasets. My script is still running and fixing the rest.

**Comment by ayushthe1** [comment]
Thanks for your time. Will try next time. 😇

**Comment by albertvillanova** [comment]
@ayushthe1 feel free to take one of the non-assigned open issues: https://github.com/huggingface/datasets/issues

**Comment by albertvillanova** [comment]
This is done.
