### ISSUE TITLE
prepare dataset for cloud storage doesn't work

### ISSUE THREAD

**Issue by largenn** [huggingface/datasets#5176]
### Describe the bug

Following the [documentation](https://huggingface.co/docs/datasets/filesystems#load-and-save-your-datasets-using-your-cloud-storage-filesystem) and [this PR](https://github.com/huggingface/datasets/pull/4724), I was downloading and storing huggingface dataset to cloud storage.
```
from datasets import load_dataset, load_dataset_builder
dataset = load_dataset_builder("wikipedia", "20220301.en", cache_dir='LOCAL_PATH')
dataset.download_and_prepare("gs://Bucket_NAME", file_format="parquet")
```
The above code successfully downloaded dataset, however, it returns error from `download_and_prepare`. 

> Traceback (most recent call last):
>   File "/shared/zhuiai/research/wiki/wiki/gcsfs.py", line 12, in <module>
>     dataset.download_and_prepare("gs://upgen/dataset/wiki", file_format="parquet")
>   File "/shared/zhuiai/.conda/envs/wiki/lib/python3.9/site-packages/datasets/builder.py", line 671, in download_and_prepare
>     fs_token_paths = fsspec.get_fs_token_paths(output_dir, storage_options=storage_options)
>   File "/shared/zhuiai/.conda/envs/wiki/lib/python3.9/site-packages/fsspec/core.py", line 635, in get_fs_token_paths
>     cls = get_filesystem_class(protocol)
>   File "/shared/zhuiai/.conda/envs/wiki/lib/python3.9/site-packages/fsspec/registry.py", line 234, in get_filesystem_class
>     register_implementation(protocol, _import_class(bit["class"]))
>   File "/shared/zhuiai/.conda/envs/wiki/lib/python3.9/site-packages/fsspec/registry.py", line 257, in _import_class
>     mod = importlib.import_module(mod)
>   File "/shared/zhuiai/.conda/envs/wiki/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/shared/zhuiai/research/wiki/wiki/gcsfs.py", line 12, in <module>
>     dataset.download_and_prepare("gs://upgen/dataset/wiki", file_format="parquet")
>   File "/shared/zhuiai/.conda/envs/wiki/lib/python3.9/site-packages/datasets/builder.py", line 671, in download_and_prepare
>     fs_token_paths = fsspec.get_fs_token_paths(output_dir, storage_options=storage_options)
>   File "/shared/zhuiai/.conda/envs/wiki/lib/python3.9/site-packages/fsspec/core.py", line 635, in get_fs_token_paths
>     cls = get_filesystem_class(protocol)
>   File "/shared/zhuiai/.conda/envs/wiki/lib/python3.9/site-packages/fsspec/registry.py", line 234, in get_filesystem_class
>     register_implementation(protocol, _import_class(bit["class"]))
>   File "/shared/zhuiai/.conda/envs/wiki/lib/python3.9/site-packages/fsspec/registry.py", line 258, in _import_class
>     return getattr(mod, name)
> AttributeError: partially initialized module 'gcsfs' has no attribute 'GCSFileSystem' (most likely due to a circular import)

### Steps to reproduce the bug

1. pip install datasets==2.6.1 gcsfs==2022.8.2
2. Run the following code will reproduce the issue (change `LOCAL_PATH` and `Bucket_NAME` accordingly)
```
from datasets import load_dataset, load_dataset_builder
dataset = load_dataset_builder("wikipedia", "20220301.en", cache_dir='LOCAL_PATH')
dataset.download_and_prepare("gs://Bucket_NAME", file_format="parquet")
```

### Expected behavior

Expecting successful downloading dataset and uploading it to cloud storage.

### Environment info

- `datasets` version: 2.6.1
- Platform: Linux-5.15.0-25-generic-x86_64-with-glibc2.35
- Python version: 3.9.12
- PyArrow version: 7.0.0
- Pandas version: 1.5.1

**Comment by lhoestq** [comment]
It looks like an issue with `gcsfs`, are you able to instantiate a `GCSFileSystem` manually ?

**Comment by lhoestq** [comment]
closing since it was probably due to gcsfs
