### ISSUE TITLE
Add a guide for semantic segmentation

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/datasets#5181]
Currently, we have these guides for object detection and image classification:

* https://huggingface.co/docs/datasets/object_detection
* https://huggingface.co/docs/datasets/image_classification

I am proposing adding a similar guide for semantic segmentation. 

I am happy to contribute a PR for it. 

Cc: @osanseviero @nateraw

**Comment by nateraw** [comment]
Sure this sounds great! Would this be pure torchvision, albumentations, or something else?

**Comment by sayakpaul** [comment]
I am considering `torchvision` and `albumentations`. Also [works with TensorFlow](https://github.com/deep-diver/segformer-tf-transformers/blob/main/notebooks/TFSegFormer_Finetune.ipynb). 

I am assigning the issue to myself then.
