### ISSUE TITLE
Add notebook / other resource links to the task-specific data loading guides

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/datasets#5182]
Does it make sense to include links to notebooks / scripts that show how to use a dataset for training / fine-tuning a model? 

For example, here in [https://huggingface.co/docs/datasets/image_classification] we could include a mention of https://github.com/huggingface/notebooks/blob/main/examples/image_classification.ipynb.

Applies to https://huggingface.co/docs/datasets/object_detection as well.

Cc: @osanseviero @nateraw

**Comment by nateraw** [comment]
Yea this would be great! We would need an object detection tutorial notebook too if it doesn't already exist there.

**Comment by sayakpaul** [comment]
There is one: https://huggingface.co/docs/datasets/object_detection.

I will start the work.
