### ISSUE TITLE
Some links to canonical datasets in the docs are outdated

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/datasets#5200]
As we don't have canonical datasets in the github repo anymore, some old links to them doesn't work. I don't know how many of them are there, I found link to SuperGlue here: https://huggingface.co/docs/datasets/dataset_script#multiple-configurations, probably there are more of them. These links should be replaced by links to the corresponding datasets on the Hub.

**Comment by stevhliu** [comment]
Thanks for catching this, I can go through the docs and replace the links to their corresponding datasets on the Hub!
