### ISSUE TITLE
Implicit type conversion of lists in to_pandas

### ISSUE THREAD

**Issue by sanderland** [huggingface/datasets#5220]
### Describe the bug

```
ds = Dataset.from_list([{'a':[1,2,3]}])
ds.to_pandas().a.values[0]
```
Results in `array([1, 2, 3])`  -- a rather unexpected conversion of types which made downstream tools expecting lists not happy.

### Steps to reproduce the bug

See snippet

### Expected behavior

Keep the original type

### Environment info

datasets 2.6.1
python 3.8.10

**Comment by lhoestq** [comment]
I think this behavior comes from PyArrow:
```python
import pyarrow as pa
t = pa.table({"a": [[0]]})
t.to_pandas().a.values[0]
# array([0])
```

I believe this has to do with zero-copy: you can get a pandas DataFrame without copying the buffers from arrow, and have the data as numpy arrays.

**Comment by sanderland** [comment]
That's interesting, I guess not much to do here then.
