### ISSUE TITLE
datasets.data_files.EmptyDatasetError: The directory at wikisql doesn't contain any data files

### ISSUE THREAD

**Issue by ScottM-wizard** [huggingface/datasets#5227]
### Describe the bug

From these lines:

from datasets import list_datasets, load_dataset
dataset = load_dataset("wikisql","binary")

I get error message:
datasets.data_files.EmptyDatasetError: The directory at wikisql doesn't contain any data files

And yet the 'wikisql' is reported to exist via the list_datasets(). 

Any help appreciated. 

### Steps to reproduce the bug

From these lines:

from datasets import list_datasets, load_dataset
dataset = load_dataset("wikisql","binary")

I get error message:
datasets.data_files.EmptyDatasetError: The directory at wikisql doesn't contain any data files

And yet the 'wikisql' is reported to exist via the list_datasets(). 

Any help appreciated. 

### Expected behavior

Dataset should load. This same code used to work.

### Environment info

Mac OS

**Comment by ScottM-wizard** [comment]
Fixed. Please close.

**Comment by ftffang** [comment]
how to fix?i need your help
