### ISSUE TITLE
Docs are not generated after latest release

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#5251]
After the latest `datasets` release version 0.7.0, the docs were not generated.

As we have changed the release procedure (so that now we do not push directly to main branch), maybe we should also change the corresponding GitHub action:

https://github.com/huggingface/datasets/blob/edf1902f954c5568daadebcd8754bdad44b02a85/.github/workflows/build_documentation.yml#L3-L8

Related to:
- #5250

CC: @mishig25

**Comment by albertvillanova** [comment]
After a discussion with @mishig25:
- He said that this action should be triggered if we call our release branch according to the regex `v*-release`, as transformers does
- I said that our procedure is different: our release branch is *temporary* and it is deleted just after the release PR is merged to main

I was thinking that maybe we could change the triggering event: use `release` instead of `push`.

What do you think, @huggingface/datasets?

**Comment by albertvillanova** [comment]
He says not; but the branch has no tag yet; does the doc building require the tag? Or just the version number in __init__.py or setup.py?

**Comment by lhoestq** [comment]
It uses `module.__version__` (i.e. the one defined in `__init__.py`)

https://github.com/huggingface/doc-builder/blob/81575cf081964c30ea5fd39450f4820db963f18e/src/doc_builder/commands/build.py#L69

**Comment by lhoestq** [comment]
Cool ! this can be closed then ?

**Comment by albertvillanova** [comment]
I was waiting for #5250 to be merged to close this.
