### ISSUE TITLE
load_dataset does not read jsonl metadata file properly

### ISSUE THREAD

**Issue by 065294847** [huggingface/datasets#5278]
### Describe the bug

Hi, I'm following [this page](https://huggingface.co/docs/datasets/image_dataset) to create a dataset of images and captions via an image folder and a metadata.json file, but I can't seem to get the dataloader to recognize the "text" column. It just spits out "image" and "label" as features. 

Below is code to reproduce my exact example/problem.

### Steps to reproduce the bug

```ruby 
dataset_link="19Unu89Ih_kP6zsE7f9Mkw8dy3NwHopRF"
id = dataset_link
output = 'Godardv01.zip'
gdown.download(id=id, output=output, quiet=False)

ds = load_dataset("imagefolder", data_dir="/kaggle/working/Volumes/TOSHIBA/Godard_imgs/Volumes/TOSHIBA/Godard_imgs/Full/train", split="train", drop_labels=False)
print(ds)
```

### Expected behavior

I would expect that it returned "image" and "text" columns from the code above.

### Environment info

- `datasets` version: 2.1.0
- Platform: Linux-5.15.65+-x86_64-with-debian-bullseye-sid
- Python version: 3.7.12
- PyArrow version: 5.0.0
- Pandas version: 1.3.5

**Comment by lhoestq** [comment]
Can you try to remove "drop_labels=false" ? It may force the loader to infer the labels instead of reading the metadata

**Comment by 065294847** [comment]
Hi, thanks for responding. I tried that, but it does not change anything.

**Comment by lhoestq** [comment]
Can you try updating `datasets` ? Metadata support was added in `datasets` 2.4

**Comment by 065294847** [comment]
Probably the issue, will report back asap!

**Comment by 065294847** [comment]
> Can you try updating `datasets` ? Metadata support was added in `datasets` 2.4

Update: This was the issue.
