### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by feketedavid1012** [huggingface/datasets#5280]
https://github.com/huggingface/datasets/blob/cd3d8e637cfab62d352a3f4e5e60e96597b5f0e9/src/datasets/__init__.py#L28

Hy, 
I have error at the above line. I have python version 3.8.13, the message says I need python>=3.7, which is True, but I think the if statement not working properly (or the message wrong)

**Comment by lhoestq** [comment]
Hi ! Can you 
```python
import platform
print(platform.python_version())
```
to see that it returns ?

**Comment by lhoestq** [comment]
Then it should work as expected if you use the same python when using `datasets`

Please make sure you're running your code in the right environment

**Comment by lhoestq** [comment]
If you're having an error then you're not running your code in the right environment.
