### ISSUE TITLE
Datasets: classification_report() got an unexpected keyword argument 'suffix'

### ISSUE THREAD

**Issue by JonathanAlis** [huggingface/datasets#5314]
https://github.com/huggingface/datasets/blob/main/metrics/seqeval/seqeval.py

> import datasets
predictions = [['O', 'O', 'B-MISC', 'I-MISC', 'I-MISC', 'I-MISC', 'O'], ['B-PER', 'I-PER', 'O']]
references = [['O', 'O', 'O', 'B-MISC', 'I-MISC', 'I-MISC', 'O'], ['B-PER', 'I-PER', 'O']]
seqeval = datasets.load_metric("seqeval")
results = seqeval.compute(predictions=predictions, references=references)
print(list(results.keys()))
print(results["overall_f1"])
print(results["PER"]["f1"])

It raises the error:

> TypeError: classification_report() got an unexpected keyword argument 'suffix'

For context, versions on my pip list -v

> datasets                 1.12.1  
seqeval                  1.2.2

**Comment by lhoestq** [comment]
This seems similar to https://github.com/huggingface/datasets/issues/2512 Can you try to update seqeval ?
