### ISSUE TITLE
Support webdataset format

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets#5337]
Webdataset is an efficient format for iterable datasets. It would be nice to support it in `datasets`, as discussed in https://github.com/rom1504/img2dataset/issues/234.

In particular it would be awesome to be able to load one using `load_dataset` in streaming mode (either from a local directory, or from a dataset on the Hugging Face Hub). Some datasets on the Hub are already in webdataset format.

It terms of implementation, we can have something similar to the Parquet loader.
I also think it's fine to have webdataset as an optional dependency.

**Comment by mariosasko** [comment]
I like the idea of having `webdataset` as an optional dependency to make sure our loader generates web datasets the same as the main project.

**Comment by xvjiarui** [comment]
Webdataset is the one of the most popular dataset formats for large scale computer vision tasks. Upvote for this issue.

**Comment by jacobwjs** [comment]
Any updates on this?

**Comment by lhoestq** [comment]
We haven't had the bandwidth to implement it so far, but if someone wants to give it a shot please don't hesitate ^^

**Comment by lhoestq** [comment]
Done in #6391
