### ISSUE TITLE
Is `fs=` deprecated in `load_from_disk()` as well?

### ISSUE THREAD

**Issue by dconathan** [huggingface/datasets#5385]
### Describe the bug

The `fs=` argument was deprecated from `Dataset.save_to_disk` and `Dataset.load_from_disk` in favor of automagically figuring it out via fsspec:
https://github.com/huggingface/datasets/blob/9a7272cd4222383a5b932b0083a4cc173fda44e8/src/datasets/arrow_dataset.py#L1339-L1340

Is there a reason the same thing shouldn't also apply to `datasets.load.load_from_disk()` as well ?

https://github.com/huggingface/datasets/blob/9a7272cd4222383a5b932b0083a4cc173fda44e8/src/datasets/load.py#L1779

### Steps to reproduce the bug

n/a

### Expected behavior

n/a

### Environment info

n/a

**Comment by mariosasko** [comment]
Hi! Yes, we should deprecate the `fs` param here. Would you be interested in submitting a PR?

**Comment by dconathan** [comment]
> Hi! Yes, we should deprecate the `fs` param here. Would you be interested in submitting a PR?

Yeah I can do that sometime next week. Should the storage_options be a new arg here?  I’ll look around for anywhere else where fs is an arg.

**Comment by albertvillanova** [comment]
Closed by #5393.
