### ISSUE TITLE
Best practices for training tokenizers with nlp

### ISSUE THREAD

**Issue by moskomule** [huggingface/datasets#541]
Hi, thank you for developing this library. 

What do you think are the best practices for training tokenizers using `nlp`?  In the document and examples, I could only find pre-trained tokenizers used.

**Comment by mariosasko** [comment]
Docs that explain how to train a tokenizer with `datasets` are available here: https://huggingface.co/docs/tokenizers/training_from_memory#using-the-datasets-library
