### ISSUE TITLE
Add ProgressBar for `to_parquet`

### ISSUE THREAD

**Issue by zanussbaum** [huggingface/datasets#5418]
### Feature request

Add a progress bar for `Dataset.to_parquet`, similar to how `to_json` works.

### Motivation

It's a bit frustrating to not know how long a dataset will take to write to file and if it's stuck or not without a progress bar

### Your contribution

Sure I can help if needed

**Comment by albertvillanova** [comment]
Thanks for your proposal, @zanussbaum. Yes, I agree that would definitely be a nice feature to have!

**Comment by zanussbaum** [comment]
@albertvillanova I’m happy to make a quick PR for the feature! let me know

**Comment by lhoestq** [comment]
That would be awesome ! You can comment `#self-assign` to assign you to this issue and open a PR :) Will be happy to review

**Comment by zanussbaum** [comment]
#self-assign

**Comment by zanussbaum** [comment]
Closing as this has been merged @lhoestq
