### ISSUE TITLE
Support latest Docker image in CI benchmarks

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#5433]
Once we find out the root cause of:
- #5431 

we should revert the temporary pin on the Docker image version introduced by:
- #5432

**Comment by 0x2b3bfa0** [comment]
Sorry, it was us:[^1] see https://github.com/iterative/cml/pull/1317 & https://github.com/iterative/cml/issues/1319#issuecomment-1385599559; should be fixed with [v0.18.17](https://github.com/iterative/cml/releases/tag/v0.18.17).

[^1]: More or less, see https://github.com/yargs/yargs/issues/873.

**Comment by 0x2b3bfa0** [comment]
Opened https://github.com/huggingface/datasets/pull/5436 unpinning again the container image.

**Comment by albertvillanova** [comment]
Hi @0x2b3bfa0, thanks a lot for the investigation and the context about the the root cause!!

We are reviewing your PR to unpin the container image.
