### ISSUE TITLE
sample_dataset module not found

### ISSUE THREAD

**Issue by nickums** [huggingface/datasets#5434]

**Comment by mariosasko** [comment]
Hi! Can you describe what the actual error is?

**Comment by nickums** [comment]
working on the setfit example script

   from setfit import SetFitModel, SetFitTrainer, sample_dataset

ImportError: cannot import name 'sample_dataset' from 'setfit' (C:\Python\Python38\lib\site-packages\setfit\__init__.py)

 apart from that, I also had to hack these loads to import thses modules:
    from datasets.load import load_dataset                        
    from datasets.arrow_dataset import Dataset
    from datasets.dataset_dict import DatasetDict

**Comment by mariosasko** [comment]
Hi! This issue is related to the [SetFit](https://github.com/huggingface/setfit) project, so can you please open it there?
