### ISSUE TITLE
NonMatchingChecksumError for hendrycks_test

### ISSUE THREAD

**Issue by sarahwie** [huggingface/datasets#5464]
### Describe the bug

The checksum of the file has likely changed on the remote host.

### Steps to reproduce the bug

`dataset = nlp.load_dataset("hendrycks_test", "anatomy")`

### Expected behavior

no error thrown

### Environment info

- `datasets` version: 2.2.1
- Platform: macOS-13.1-arm64-arm-64bit
- Python version: 3.9.13
- PyArrow version: 9.0.0
- Pandas version: 1.5.1

**Comment by albertvillanova** [comment]
Thanks for reporting, @sarahwie.

Please note this issue was already fixed:
- #5040

If you update your `datasets` version, you will be able to load the dataset:
```
pip install -U datasets
```

**Comment by sarahwie** [comment]
Oops, missed that I needed to upgrade. Thanks!
