### ISSUE TITLE
Unpin sqlalchemy once issue is fixed

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#5477]
Once the source issue is fixed:
- pandas-dev/pandas#51015

we should revert the pin introduced in:
- #5476

**Comment by lazarust** [comment]
@albertvillanova It looks like that issue has been fixed so I made a PR to unpin sqlalchemy!

**Comment by albertvillanova** [comment]
The source issue:
- https://github.com/pandas-dev/pandas/issues/40686

has been fixed:
- https://github.com/pandas-dev/pandas/pull/48576

The fix was released yesterday (2023-04-03) only in `pandas-2.0.0`:
- https://github.com/pandas-dev/pandas/releases/tag/v2.0.0

but it will not be back-ported to `pandas-1`.

Also note that `pandas-2.0.0` dropped support for Python 3.7:
- https://github.com/pandas-dev/pandas/issues/41678
- https://github.com/pandas-dev/pandas/pull/41989

Therefore, we cannot unpin `sqlalchemy` until we drop support for Python 3.7 (these Python users cannot use `pandas-2`).
