### ISSUE TITLE
Update audio installation doc page

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/datasets#5494]
Our [installation documentation page](https://huggingface.co/docs/datasets/installation#audio) says that one can use Datasets for mp3 only with `torchaudio<0.12`. `torchaudio>0.12` is actually supported too but requires a specific version of ffmpeg which is not easily installed on all linux versions but there is a custom ubuntu repo for it, we have insctructions in the code: https://github.com/huggingface/datasets/blob/main/src/datasets/features/audio.py#L327 
So we should update the doc page. But first investigate [this issue](5488).

**Comment by polinaeterna** [comment]
@albertvillanova yeah sure I should have, but I forgot back then

**Comment by albertvillanova** [comment]
No, @polinaeterna, nothing to be sorry about.

My comment was for all of us datasets team, as a reminder: when making a PR, but also when reviewing some other's PR, we should not forget to update the corresponding docstring and doc pages. It is something we can improve if we help each other in reminding about it... :hugs:

**Comment by mariosasko** [comment]
@polinaeterna I think we can close this issue now as we no longer use `torchaudio` for decoding.
