### ISSUE TITLE
Some functions use a param named `type` shouldn't that be avoided since it's a Python reserved name?

### ISSUE THREAD

**Issue by alvarobartt** [huggingface/datasets#5513]
Hi @mariosasko, @lhoestq, or whoever reads this! :)

After going through `ArrowDataset.set_format` I found out that the `type` param is actually named `type` which is a Python reserved name as you may already know, shouldn't that be renamed to `format_type` before the 3.0.0 is released?

Just wanted to get your input, and if applicable, tackle this issue myself! Thanks 🤗

**Comment by mariosasko** [comment]
Hi! Let's not do this - renaming it would be a breaking change, and going through the deprecation cycle is only worth it if it improves user experience.

**Comment by alvarobartt** [comment]
Ok makes sense, anyway, don't you think it's worth it at some point to start a deprecation cycle i.e. `fs` in `load_from_disk`? It doesn't affect user experience but it's for sure a bad practice IMO, but up to you 😄 Feel free to close this issue otherwise!

**Comment by alvarobartt** [comment]
Sure, makes sense @mariosasko thanks!
