### ISSUE TITLE
Add `Dataset.to_list` to the API

### ISSUE THREAD

**Issue by mariosasko** [huggingface/datasets#5606]
Since there is `Dataset.from_list` in the API, we should also add `Dataset.to_list` to be consistent.
 
Regarding the implementation, we can re-use `Dataset.to_dict`'s code and replace the `to_pydict` calls with `to_pylist`.

**Comment by kyoto7250** [comment]
Hello, I have an interest in this issue.
Is the `Dataset.to_dict` you are describing correct in the code here?

https://github.com/huggingface/datasets/blob/35b789e8f6826b6b5a6b48fcc2416c890a1f326a/src/datasets/arrow_dataset.py#L4633-L4667

**Comment by mariosasko** [comment]
Yes, this is where `Dataset.to_dict` is defined.

**Comment by kyoto7250** [comment]
#self-assign
