### ISSUE TITLE
expanduser in save_to_disk

### ISSUE THREAD

**Issue by RmZeta2718** [huggingface/datasets#5651]
### Describe the bug

save_to_disk() does not expand `~`

1. `dataset = load_datasets("any dataset")`
2. `dataset.save_to_disk("~/data")`
3. a folder named "~" created in current folder
4. FileNotFoundError is raised, because the expanded path does not exist (`/home/<user>/data`)

related issue https://github.com/huggingface/transformers/issues/10628

### Steps to reproduce the bug

As described above.

### Expected behavior

expanduser correctly

### Environment info

- datasets 2.10.1
- python 3.10

**Comment by mariosasko** [comment]
`save_to_disk` should indeed expand `~`. Marking it as a "good first issue".

**Comment by benjaminbrown038** [comment]
How to access where this issue is in the code?

**Comment by benjaminbrown038** [comment]
#self-assign

**Comment by ashikshafi08** [comment]
Hello, 
It says `save_to_disk` is deprecated in 2.8.0, so the alternative to this will be `storage_options`? 

https://huggingface.co/docs/datasets/package_reference/main_classes#datasets.Dataset.save_to_disk

**Comment by benjaminbrown038** [comment]
#un-assign

**Comment by Unknown3141592** [comment]
@ashikshafi08 I think you misunderstood the warning. The method `save_to_disk` is not deprecated only the optional parameter `fs`.
Also @benjaminbrown038 as I cannot find your PR I would like to work on this if you don't mind.

**Comment by RmZeta2718** [comment]
@mariosasko It's been several months and the PR is not reviewed. Could you please take a look? I assume this is not complicated and could be merged fairly soon.
