### ISSUE TITLE
Add support to create a Dataset from spark dataframe

### ISSUE THREAD

**Issue by lu-wang-dl** [huggingface/datasets#5678]
### Feature request

Add a new API `Dataset.from_spark` to create a Dataset from Spark DataFrame.

### Motivation

Spark is a distributed computing framework that can handle large datasets. By supporting loading Spark DataFrames directly into Hugging Face Datasets, we enable take the advantages of spark to processing the data in parallel. 

By providing a seamless integration between these two frameworks, we make it easier for data scientists and developers to work with both Spark and Hugging Face in the same workflow.

### Your contribution

We can discuss about the ideas and I can help preparing a PR for this feature.

**Comment by yanzia12138** [comment]
if i read spark Dataframe error on  multi-node Spark cluster.
did the Api (Dataset.from_spark) support Spark cluster, read dataframe and save_to_disk

**Comment by oakkas84** [comment]
How to perform predictions on Dataset object in Spark with multi-node cluster parallelism?

**Comment by mariosasko** [comment]
Addressed in #5701

**Comment by lhoestq** [comment]
Hi ! for your information we are working on some more documentation on how to use Spark with HF Datasets repositories (without the need for the `datasets` library) here: https://github.com/huggingface/datasets/pull/5701

Cc @lu-wang-dl @maddiedawson let me know what you think !

**Comment by lhoestq** [comment]
sorry, wrong link: https://github.com/huggingface/hub-docs/pull/1392
