### ISSUE TITLE
Add information about patterns search order to the doc about structuring repo

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/datasets#5681]
Following [this](https://github.com/huggingface/datasets/issues/5650) issue I think we should add a note about the order of patterns that is used to find splits, see [my comment](https://github.com/huggingface/datasets/issues/5650#issuecomment-1488412527). Also we should reference this page in pages about packaged loaders. 

I have a déjà vu that it had already been discussed as some point but I don't remember....

**Comment by stevhliu** [comment]
Good idea, I think I've seen this a couple of times before too on the forums. I can work on this :)

**Comment by stevhliu** [comment]
Closed in #5693
