### ISSUE TITLE
Dataset sizes are in MiB instead of MB in dataset cards

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#5708]
As @severo reported in an internal discussion (https://github.com/huggingface/moon-landing/issues/5929):

Now we show the dataset size:
- from the dataset card (in the side column)
- from the datasets-server (in the viewer)

But, even if the size is the same, we see a mismatch because the viewer shows MB, while the info from the README generally shows MiB (even if it's written MB -> https://huggingface.co/datasets/blimp/blob/main/README.md?code=true#L1932)

<img width="664" alt="Capture d’écran 2023-04-04 à 10 16 01" src="https://user-images.githubusercontent.com/1676121/229730887-0bd8fa6e-9462-46c6-bd4e-4d2c5784cabb.png">

TODO: Values to be fixed in: `Size of downloaded dataset files:`, `Size of the generated dataset:` and `Total amount of disk used:`
- [x] Bulk edit on the Hub to fix this in all canonical datasets
- [x] Bulk PR on the Hub to fix ancient canonical datasets that were moved to organizations

**Comment by albertvillanova** [comment]
Example of bulk edit: https://huggingface.co/datasets/aeslc/discussions/5

**Comment by julien-c** [comment]
looks great! 

Do you encode the fact that you've already converted a dataset? (to not convert it twice) or do you base yourself on the info contained in `dataset_info`

**Comment by albertvillanova** [comment]
I am only looping trough the dataset cards, assuming that all of them were created with MiB.

I agree we should only run the bulk edit once for all canonical datasets: I'm using a for-loop.

**Comment by julien-c** [comment]
yes, worst case, we have this in structured data:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/326577/230037051-06caddcb-08c8-4953-a710-f3d122917db3.png">

**Comment by albertvillanova** [comment]
I have just included as well the conversion from MB to GB if necessary. See: https://huggingface.co/datasets/asnq/discussions/2/files

**Comment by severo** [comment]
Nice. Is it another loop? Because in https://huggingface.co/datasets/amazon_us_reviews/discussions/2/files we have `32377.29 MB` for example

**Comment by albertvillanova** [comment]
First, I tested in batches of 10. Then I incorporated the MB to GB conversion.

**Comment by albertvillanova** [comment]
The bulk edit parsed 751 canonical datasets and updated 166.

**Comment by severo** [comment]
Thanks a lot!

**Comment by severo** [comment]
should we force merge the PR and close this issue?

**Comment by albertvillanova** [comment]
I merged the PRs for "scicite" and "scifact".
