### ISSUE TITLE
Handle empty audio

### ISSUE THREAD

**Issue by v-yunbin** [huggingface/datasets#5716]
Some audio paths exist, but they are empty, and an error will be reported when reading the audio path.How to use the filter function to avoid the empty audio path?
when a audio is empty, when do resample , it will break:
`array, sampling_rate = sf.read(f) array = librosa.resample(array, orig_sr=sampling_rate, target_sr=self.sampling_rate)`

**Comment by mariosasko** [comment]
I'm closing this issue as the reproducer hasn't been provided.
