### ISSUE TITLE
How to limit the number of examples in dataset, for testing?

### ISSUE THREAD

**Issue by ndvbd** [huggingface/datasets#5725]
### Describe the bug

I am using this command:
`data = load_dataset("json", data_files=data_path)`
However, I want to add a parameter, to limit the number of loaded examples to be 10, for development purposes, but can't find this simple parameter.

### Steps to reproduce the bug

In the description.

### Expected behavior

To be able to limit the number of examples

### Environment info

Nothing special

**Comment by mariosasko** [comment]
Hi! You can use the `nrows` parameter for this:
```python
data = load_dataset("json", data_files=data_path, nrows=10)
```

**Comment by ndvbd** [comment]
@mariosasko I get:

`TypeError: __init__() got an unexpected keyword argument 'nrows'`

**Comment by mariosasko** [comment]
I misread the format in which the dataset is stored -  the `nrows` parameter works for CSV, but not JSON.

This means the only option is first to create a DataFrame and then convert it to a Dataset object:
```
import pandas as pd
from datasets import Dataset

df = pd.read_json(data_path, lines=True, nrows=10)
ds = Dataset.from_pandas(df)
```
