### ISSUE TITLE
IterableDataset.with_format("torch") not working

### ISSUE THREAD

**Issue by jiangwy99** [huggingface/datasets#5793]
### Describe the bug

After calling the with_format("torch") method on an IterableDataset instance, the data format is unchanged.

### Steps to reproduce the bug

```python
from datasets import IterableDataset
def gen():
    for i in range(4):
        yield {"a": [i] * 4}
dataset = IterableDataset.from_generator(gen).with_format("torch")
next(iter(dataset))
```

### Expected behavior

`{"a": torch.tensor([0, 0, 0, 0])}` is expected, but `{"a": [0, 0, 0, 0]}` is observed.

### Environment info

```bash
platform==ubuntu 22.04.01
python==3.10.9
datasets==2.11.0
```

**Comment by lhoestq** [comment]
Hi ! Thanks for reporting, I'm working on it ;)
