### ISSUE TITLE
wiki_dpr details for Open Domain Question Answering tasks

### ISSUE THREAD

**Issue by yulgok22** [huggingface/datasets#5809]
Hey guys!

Thanks for creating the wiki_dpr dataset!

I am currently trying to combine wiki_dpr and my own datasets. but I don't know how to make the embedding value the same way as wiki_dpr.

As an experiment, I embeds the text of id="7" of wiki_dpr, but this result was very different from wiki_dpr.

**Comment by lhoestq** [comment]
Hi ! I don't remember exactly how it was done, but maybe you have to embed f"{title}<sep>{text}" ?
