### ISSUE TITLE
Streaming support for `load_from_disk`

### ISSUE THREAD

**Issue by Nilabhra** [huggingface/datasets#5838]
### Feature request

Support for streaming datasets stored in object stores in `load_from_disk`. 

### Motivation

The `load_from_disk` function supports fetching datasets stored in object stores such as `s3`. In many cases, the datasets that are stored in object stores are very large and being able to stream the data from the buckets becomes essential.

### Your contribution

I'd be happy to contribute this feature if I could get the guidance on how to do so.

**Comment by lhoestq** [comment]
As the name says, `load_from_disk` load the data from your disk. If the data is hosted on S3, it is first downloaded locally and then loaded from your disk.

There is a discussion on streaming data from S3 here though: #5281

**Comment by Nilabhra** [comment]
@lhoestq 
Thanks for your comment. I have checked out the discussion before and attempted at replicating the mentioned changes in the main branch. What I found was that if a dataset is saved using `save_to_disk`, it cannot be read by `load_dataset`. The error message asks me to to use `load_from_disk` instead. What would be the correct way of saving the data in this scenario?

**Comment by lhoestq** [comment]
Using `push_to_hub` you can save the dataset on the HF Hub as parquet files, and reload it / stream it using `load_dataset` :)

If you want to save your dataset somewhere else you can use `.to_parquet` to get a parquet file. If your dataset is big it's usually recommended to shard it into multi parquet files (around 1GB each).

**Comment by Nilabhra** [comment]
@lhoestq 
Thanks for the explanation. Appreciate it. I'll try this out.

**Comment by Nilabhra** [comment]
@lhoestq
I tried the method you mentioned. This the current scenario I'm facing:

- The parquet file can be read from disk and streaming can be enabled.
- The parquet file can be read from `s3` (local MinIO).
- When `streaming=True` is enabled for `s3`, I get the error mentioned below:

```
File ~/.../lib/python3.8/site-packages/s3fs/core.py:502, in S3FileSystem.set_session(self, refresh, kwargs)
    500 conf = AioConfig(**config_kwargs)
    501 if self.session is None:
--> 502     self.session = aiobotocore.session.AioSession(**self.kwargs)
    504 for parameters in (config_kwargs, self.kwargs, init_kwargs, client_kwargs):
    505     for option in ("region_name", "endpoint_url"):

TypeError: __init__() got an unexpected keyword argument 'headers'
```

Does this mean there is a bug in the main branch?

**Comment by lhoestq** [comment]
Streaming from S3 is still experimental, there might be a few bugs unfortunately.

Can you share the full stack trace ?

**Comment by lhoestq** [comment]
Is `"data-parquet"` a file ? In `data_files` you should pass the paths to the parquet files (not to a directory). Glob patterns are not supported yet for S3 URLs.

The bug seems to happen because your provided data file has no extension. Because of that it tries to infer it from the file content, but fails because `_get_extraction_protocol` doesn't support S3 URLs yet.

**Comment by Nilabhra** [comment]
@lhoestq 
Thank you for your answer. Saving the file with `.parquet` extension solved the issue! This is really great! Really appreciate all the help! 

Let me know if I should close the issue or feel free to close it if you want.

**Comment by TianduoWang** [comment]
> As the name says, `load_from_disk` load the data from your disk. If the data is hosted on S3, it is first downloaded locally and then loaded from your disk.
> 
> There is a discussion on streaming data from S3 here though: #5281

Hi @lhoestq,

Thanks for your answer here! I would like to know if it is possible to use `load_from_disk` from S3 without downloading it locally. For now my dataset is quite large, and my local machine doesn't have such big storage.

**Comment by lhoestq** [comment]
Hi ! Have you considered hosting your dataset on HF instead ? This way you can use `load_dataset` with `streaming=True` (which is not available in load_from_disk which is for memory mapping Arrow files on disk)
