### ISSUE TITLE
load model error.

### ISSUE THREAD

**Issue by LanShanPi** [huggingface/datasets#5840]
### Describe the bug

I had trained one model use deepspeed, when I load the final load I get the follow error:
OSError: Can't load tokenizer for '/XXX/DeepSpeedExamples/applications/DeepSpeed-Chat/output/step3-models/1.3b/actor'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/home/fm001/hzl/Project/DeepSpeedExamples/applications/DeepSpeed-Chat/output/step3-models/1.3b/actor' is the correct path to a directory containing all relevant files for a BloomTokenizerFast tokenizer.

my load code is : python chat.py --path /XXX/DeepSpeedExamples/applications/DeepSpeed-Chat/output/step3-models/1.3b/actor/

### Steps to reproduce the bug

。。。

### Expected behavior

。。。

### Environment info

。。。

**Comment by mariosasko** [comment]
Please report this in the `transformers` repo, as it's not related to `datasets`
