### ISSUE TITLE
Remove columns in interable dataset

### ISSUE THREAD

**Issue by surya-narayanan** [huggingface/datasets#5842]
### Feature request

Right now, remove_columns() produces a NotImplementedError for iterable style datasets

### Motivation

It would be great to have the same functionality irrespective of whether one is using an iterable or a map-style dataset

### Your contribution

hope and courage.

**Comment by Bearnardd** [comment]
Hi @surya-narayanan! Could you provide some code snippet?

**Comment by mariosasko** [comment]
This method has been recently added to the `IterableDataset`, so you need to update the `datasets`' installation (`pip install -U datasets`) to use it.
