### ISSUE TITLE
Is it possible to change a cached file and 're-cache' it instead of re-generating?

### ISSUE THREAD

**Issue by zyh3826** [huggingface/datasets#5868]
### Feature request

Hi,
I have a huge cached file using `map`(over 500GB), and I want to change an attribution of each element, is there possible to do it using some method instead of re-generating, because `map` takes over 24 hours

### Motivation

For large datasets, I think it is very important because we always face the problem which is changing something in the original cache without re-generating it.

### Your contribution

For now, I can't help, sorry.

**Comment by mariosasko** [comment]
Arrow files/primitives are immutable, so re-generating them is the only option, I'm afraid.

**Comment by zyh3826** [comment]
> 

Got it, thanks for your reply
