### ISSUE TITLE
User access requests with manual review do not notify the dataset owner

### ISSUE THREAD

**Issue by leondz** [huggingface/datasets#5892]
### Describe the bug

When a user access requests are enabled, and new requests are set to Manual Review, the dataset owner should be notified of the pending requests. However, instead, currently nothing happens, and so the dataset request can go unanswered for quite some time until the owner happens to check that particular dataset's Settings pane.

### Steps to reproduce the bug

1. Enable a dataset's user access requests
2. Set to Manual Review
3. Ask another HF user to request access to the dataset
4. Dataset owner is not notified

### Expected behavior

The dataset owner should receive some kind of notification, perhaps in their HF site inbox, or by email, when a dataset access request is made and manual review is enabled.

### Environment info

n/a

**Comment by mariosasko** [comment]
cc @SBrandeis

**Comment by mariosasko** [comment]
I think this has been addressed.

Please open a new issue if you are still not getting notified.
