### ISSUE TITLE
Viewing dataset card returns “502 Bad Gateway”

### ISSUE THREAD

**Issue by tbenthompson** [huggingface/datasets#5980]
The url is: https://huggingface.co/datasets/Confirm-Labs/pile_ngrams_trigrams

I am able to successfully view the “Files and versions” tab: [Confirm-Labs/pile_ngrams_trigrams at main](https://huggingface.co/datasets/Confirm-Labs/pile_ngrams_trigrams/tree/main)

Any help would be appreciated! Thanks! I hope this is the right place to report an issue like this.

**Comment by mariosasko** [comment]
Can you try again? Maybe there was a minor outage.

**Comment by tbenthompson** [comment]
Yes, it seems to be working now. In case it's helpful, the outage lasted several days. It was failing as late as yesterday morning.

**Comment by julien-c** [comment]
we fixed something on the server side, glad it's fixed now
