### ISSUE TITLE
ConnectionError: Couldn't reach dataset_infos.json 

### ISSUE THREAD

**Issue by yulingao** [huggingface/datasets#5988]
### Describe the bug

I'm trying to load codeparrot/codeparrot-clean-train, but get the following error:

ConnectionError: Couldn't reach https://huggingface.co/datasets/codeparrot/codeparrot-clean-train/resolve/main/dataset_infos.json (ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))))

### Steps to reproduce the bug

train_data = load_dataset('codeparrot/codeparrot-clean-train', split='train')

### Expected behavior

download the dataset

### Environment info

centos7

**Comment by mariosasko** [comment]
Unfortunately, I can't reproduce the error. What does the following code return for you?
```
import requests
from huggingface_hub import hf_hub_url
r = requests.get(hf_hub_url("codeparrot/codeparrot-clean-train", "dataset_infos.json"))
```

Also, can you provide more info about your network (region, proxies, etc.)?
