### ISSUE TITLE
Don't use the old NYU GLUE dataset URLs

### ISSUE THREAD

**Issue by jeswan** [huggingface/datasets#608]
NYU is switching dataset hosting from Google to FB. Initial changes to `datasets` are in https://github.com/jeswan/nlp/commit/b7d4a071d432592ded971e30ef73330529de25ce. What tests do you suggest I run before opening a PR?

See: https://github.com/jiant-dev/jiant/issues/161 and https://github.com/nyu-mll/jiant/pull/1112

**Comment by lhoestq** [comment]
Feel free to open the PR ;)
Thanks for updating the dataset_info.json file !
