### ISSUE TITLE
How do i get "amazon_us_reviews

### ISSUE THREAD

**Issue by IqraBaluch** [huggingface/datasets#6099]
### Feature request

I have been trying to load 'amazon_us_dataset" but unable to do so. 

`amazon_us_reviews = load_dataset('amazon_us_reviews')`
`print(amazon_us_reviews)`

> [ValueError: Config name is missing.

Please pick one among the available configs: ['Wireless_v1_00', 'Watches_v1_00', 'Video_Games_v1_00', 'Video_DVD_v1_00', 'Video_v1_00', 'Toys_v1_00', 'Tools_v1_00', 'Sports_v1_00', 'Software_v1_00', 'Shoes_v1_00', 'Pet_Products_v1_00', 'Personal_Care_Appliances_v1_00', 'PC_v1_00', 'Outdoors_v1_00', 'Office_Products_v1_00', 'Musical_Instruments_v1_00', 'Music_v1_00', 'Mobile_Electronics_v1_00', 'Mobile_Apps_v1_00', 'Major_Appliances_v1_00', 'Luggage_v1_00', 'Lawn_and_Garden_v1_00', 'Kitchen_v1_00', 'Jewelry_v1_00', 'Home_Improvement_v1_00', 'Home_Entertainment_v1_00', 'Home_v1_00', 'Health_Personal_Care_v1_00', 'Grocery_v1_00', 'Gift_Card_v1_00', 'Furniture_v1_00', 'Electronics_v1_00', 'Digital_Video_Games_v1_00', 'Digital_Video_Download_v1_00', 'Digital_Software_v1_00', 'Digital_Music_Purchase_v1_00', 'Digital_Ebook_Purchase_v1_00', 'Camera_v1_00', 'Books_v1_00', 'Beauty_v1_00', 'Baby_v1_00', 'Automotive_v1_00', 'Apparel_v1_00', 'Digital_Ebook_Purchase_v1_01', 'Books_v1_01', 'Books_v1_02']
Example of usage:
	`load_dataset('amazon_us_reviews', 'Wireless_v1_00')`]

__________________________________________________________________________
`amazon_us_reviews = load_dataset('amazon_us_reviews', 'Watches_v1_00')
print(amazon_us_reviews)`

**ERROR**
`Generating` train split: 0%
0/960872 [00:00<?, ? examples/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/datasets/builder.py in _prepare_split_single(self, gen_kwargs, fpath, file_format, max_shard_size, split_info, check_duplicate_keys, job_id)
   1692                         )
-> 1693                     example = self.info.features.encode_example(record) if self.info.features is not None else record
   1694                     writer.write(example, key)

11 frames
KeyError: 'marketplace'

The above exception was the direct cause of the following exception:

DatasetGenerationError                    Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/datasets/builder.py in _prepare_split_single(self, gen_kwargs, fpath, file_format, max_shard_size, split_info, check_duplicate_keys, job_id)
   1710             if isinstance(e, SchemaInferenceError) and e.__context__ is not None:
   1711                 e = e.__context__
-> 1712             raise DatasetGenerationError("An error occurred while generating the dataset") from e
   1713 
   1714         yield job_id, True, (total_num_examples, total_num_bytes, writer._features, num_shards, shard_lengths)

DatasetGenerationError: An error occurred while generating the dataset

### Motivation

The dataset I'm using
https://huggingface.co/datasets/amazon_us_reviews

### Your contribution

What is the best way to load this data

**Comment by robertoschiavone** [comment]
Seems like the problem isn't with the library, but the dataset itself hosted on AWS S3.

Its [homepage](https://s3.amazonaws.com/amazon-reviews-pds/readme.html) returns an `AccessDenied` XML response, which is the same thing you get if you try to log the `record` that triggers the exception

```python
try:
    example = self.info.features.encode_example(record) if self.info.features is not None else record
except Exception as e:
    print(record)
```

⬇️

```
{'<?xml version="1.0" encoding="UTF-8"?>': '<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>N2HFJ82ZV8SZW9BV</RequestId><HostId>Zw2DQ0V2GdRmvH5qWEpumK4uj5+W8YPcilQbN9fLBr3VqQOcKPHOhUZLG3LcM9X5fkOetxp48Os=</HostId></Error>'}
```

**Comment by Maryam-Mostafa** [comment]
I'm getting same errors when loading this dataset

**Comment by IqraBaluch** [comment]
I have figured it out. there was an option of **parquet formated files**  i downloaded some from there.

**Comment by Maryam-Mostafa** [comment]
Thanks for the help.

**Comment by sercasti** [comment]
this dataset is unfortunately no longer public

**Comment by albertvillanova** [comment]
Thanks for reporting, @IqraBaluch.

We contacted the authors and unfortunately they reported that Amazon has decided to stop distributing this dataset.

**Comment by Maryam-Mostafa** [comment]
If anyone still need this dataset, you could find it on kaggle here : https://www.kaggle.com/datasets/cynthiarempel/amazon-us-customer-reviews-dataset

**Comment by IqraBaluch** [comment]
Thanks @Maryam-Mostafa

**Comment by IqraBaluch** [comment]
@albertvillanova don't tell 'em, we have figured it out. XD

**Comment by TTXiong** [comment]
I noticed that some book data is missing, we can only get Books_v1_02 data. 
Is there any way we can get the Books_v1_00 and Books_v1_01? 
Really appreciate !!!

**Comment by mylesmharrison** [comment]
@albertvillanova will this dataset be retired given the data are no longer hosted on S3? What is done in cases such as these?
