### ISSUE TITLE
Why not use self._epoch as seed to shuffle in distributed training with IterableDataset

### ISSUE THREAD

**Issue by npuichigo** [huggingface/datasets#6156]
### Describe the bug

Currently, distributed training with `IterableDataset` needs to pass fixed seed to shuffle to keep each node use the same seed to avoid overlapping.
https://github.com/huggingface/datasets/blob/a7f8d9019e7cb104eac4106bdc6ec0292f0dc61a/src/datasets/iterable_dataset.py#L1174-L1177

My question is why not directly use `self._epoch` which is set by `set_epoch` as seed? It's almost the same across nodes.
https://github.com/huggingface/datasets/blob/a7f8d9019e7cb104eac4106bdc6ec0292f0dc61a/src/datasets/iterable_dataset.py#L1790-L1801

If not using `self._epoch` as shuffling seed, what does this method do to prepare an epoch seeded generator?
https://github.com/huggingface/datasets/blob/a7f8d9019e7cb104eac4106bdc6ec0292f0dc61a/src/datasets/iterable_dataset.py#L1206

### Steps to reproduce the bug

As mentioned above.

### Expected behavior

As mentioned above.

### Environment info

Not related

**Comment by npuichigo** [comment]
@lhoestq

**Comment by lhoestq** [comment]
`_effective_generator` returns a RNG that takes into account `self._epoch` and the current dataset's shuffling RNG (e.g. it can be set by specifying `seed=` in `.shuffle()`)

**Comment by npuichigo** [comment]
Thanks for the reply
