### ISSUE TITLE
Mistakes in MLQA features names

### ISSUE THREAD

**Issue by M-Salti** [huggingface/datasets#619]
I think the following features in MLQA shouldn't be named the way they are:
1. `questions` (should be `question`)
2. `ids` (should be `id`)
3. `start` (should be `answer_start`)

The reasons I'm suggesting these features be renamed are:
* To make them consistent with other QA datasets like SQuAD, XQuAD, TyDiQA etc. and hence make it easier to concatenate multiple QA datasets.
* The features names are not the same as the ones provided in the original MLQA datasets (it uses the names I suggested).

I know these columns can be renamed using  using `Dataset.rename_column_`, `questions` and `ids` can be easily renamed but `start` on the other hand is annoying to rename since it's nested inside the feature `answers`.

**Comment by lhoestq** [comment]
Indeed you're right ! Thanks for reporting that

Could you open a PR to fix the features names ?
