### ISSUE TITLE
`Invalid user token` even when correct user token is passed!

### ISSUE THREAD

**Issue by Vaibhavs10** [huggingface/datasets#6190]
### Describe the bug

I'm working on a dataset which comprises other datasets on the hub.
URL: https://huggingface.co/datasets/open-asr-leaderboard/datasets-test-only

Note: Some of the sub-datasets in this metadataset require explicit access.

All the other datasets work fine, except, `common_voice`.

### Steps to reproduce the bug

https://github.com/Vaibhavs10/scratchpad/blob/main/cv_datasets_bug_repro.ipynb

### Expected behavior

It should work if the provided access token is valid (as it does for all the other datasets)

### Environment info

datasets version -> 2.14.4

**Comment by lhoestq** [comment]
This is because `download_config.use_auth_token` is deprecated - you should use `download_config.token` instead
