### ISSUE TITLE
with_format() function returns bytes instead of PIL images even when image column is not part of "columns"

### ISSUE THREAD

**Issue by leot13** [huggingface/datasets#6366]
### Describe the bug

When using the with_format() function on a dataset containing images, even if the image column is not part of the columns provided in the function, its type will be changed to bytes.
Here is a minimal reproduction of the bug:
https://colab.research.google.com/drive/1hyaOspgyhB41oiR1-tXE3k_gJCdJUQCf?usp=sharing

### Steps to reproduce the bug

1. Load the image dataset
2. apply with_format(columns=["text"])
3. Check the type of images in the "image" column before and after applying with_format

### Expected behavior

The type should stay the same, but it does not

### Environment info

datasets==2.14.6

**Comment by mariosasko** [comment]
Thanks for reporting! I've opened a PR with a fix.
