### ISSUE TITLE
Safely load datasets by disabling execution of dataset loading script

### ISSUE THREAD

**Issue by irenedea** [huggingface/datasets#6400]
### Feature request

Is there a way to disable execution of dataset loading script using `load_dataset`? This is a security vulnerability that could lead to arbitrary code execution. 

Any suggested workarounds are welcome as well. 

### Motivation

This is a security vulnerability that could lead to arbitrary code execution. 

### Your contribution

n/a

**Comment by julien-c** [comment]
great idea IMO

**Comment by dakinggg** [comment]
@julien-c that would be great!

**Comment by lhoestq** [comment]
We added the `trust_remote_code` argument to `load_dataset()` in `datasets` 2.16:
- in the future users will have to pass trust_remote_code=True to use datasets with a script
- for now we just show a warning when a dataset script is used
- we fallback on the Hugging Face Parquet exports when possible (to keep compatibility with old datasets with scripts)

So feel free to use `trust_remote_code=False` in the meantime to disable loading from dataset loading scripts :)

**Comment by lhoestq** [comment]
Passing `trust_remote_code=True` explicitly is now mandatory to load a dataset with a script since https://github.com/huggingface/datasets/pull/6954
