### ISSUE TITLE
Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by kopyl** [huggingface/datasets#6435]
### Describe the bug

1. I ran dataset mapping with `num_proc=6` in it and got this error:
`RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method`

I can't actually find a way to run multi-GPU dataset mapping. Can you help?

### Steps to reproduce the bug

1. Rund SDXL training with `num_proc=6`: https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py

### Expected behavior

Should work well

### Environment info

6x A100 SXM, Linux

**Comment by mariosasko** [comment]
[This doc section](https://huggingface.co/docs/datasets/main/en/process#multiprocessing) explains how to modify the script to avoid this error.

**Comment by kopyl** [comment]
@mariosasko thank you very much, i'll check it

**Comment by kopyl** [comment]
@mariosasko no it does not

`Dataset.filter() got an unexpected keyword argument 'with_rank'`

**Comment by kopyl** [comment]
@mariosasko not really.

https://github.com/huggingface/datasets/issues/6621

Do you have a valid guide with which i can get my multi-GPU processing to work?
