### ISSUE TITLE
Trouble Loading a Gated Dataset For User with Granted Permission

### ISSUE THREAD

**Issue by e-trop** [huggingface/datasets#6441]
### Describe the bug

I have granted permissions to several users to access a gated huggingface dataset. The users accepted the invite and when trying to load the dataset using their access token they get 
`FileNotFoundError: Couldn't find a dataset script at .....` . Also when they try to click the url link for the dataset they get a 404 error.

### Steps to reproduce the bug

1. Grant access to gated dataset for specific users 
2. Users accept invitation
3. Users login to hugging face hub using cli login
4. Users run load_dataset

### Expected behavior

Dataset is loaded normally for users who were granted access to the gated dataset.

### Environment info

datasets==2.15.0

**Comment by mariosasko** [comment]
> Also when they try to click the url link for the dataset they get a 404 error.

This seems to be a Hub error then (cc @SBrandeis)

**Comment by severo** [comment]
Could you report this to https://discuss.huggingface.co/c/hub/23? If you can, could you provide the URL of the datase, or at least if the dataset is public or private?

**Comment by e-trop** [comment]
Thanks for the reply! I've created an issue on the hub's board here: https://discuss.huggingface.co/t/trouble-loading-a-gated-dataset-for-user-with-granted-permission/65565
