### ISSUE TITLE
Support multiple image/audio columns in ImageFolder/AudioFolder

### ISSUE THREAD

**Issue by severo** [huggingface/datasets#6450]
### Feature request

Have a metadata.csv file with multiple columns that point to relative image or audio files.

### Motivation

Currently, ImageFolder allows one column, called `file_name`, pointing to relative image files. On the same model, AudioFolder allows one column, called `file_name`, pointing to relative audio files.

But it's not possible to have two image columns, or to have two audio column, or to have one audio column and one image column.

### Your contribution

no specific contribution

**Comment by mariosasko** [comment]
A duplicate of https://github.com/huggingface/datasets/issues/5760
