### ISSUE TITLE
Cannot download dataset_info.json

### ISSUE THREAD

**Issue by chiyuzhang94** [huggingface/datasets#647]
I am running my job on a cloud server where does not provide for connections from the standard compute nodes to outside resources. Hence, when I use `dataset.load_dataset()` to load data, I got an error like this:

```
ConnectionError: Couldn't reach https://storage.googleapis.com/huggingface-nlp/cache/datasets/text/default-53ee3045f07ba8ca/0.0.0/dataset_info.json
```

I tried to open this link manually, but I cannot access this file. How can I download this file and pass it through `dataset.load_dataset()` manually?

Versions:
Python version 3.7.3
PyTorch version 1.6.0
TensorFlow version 2.3.0
datasets version: 1.0.1

**Comment by lhoestq** [comment]
Thanks for reporting !
We should add support for servers without internet connection indeed
I'll do that early next week

**Comment by chiyuzhang94** [comment]
Thanks, @lhoestq !
Please let me know when it is available.

**Comment by lhoestq** [comment]
#652 should allow you to load text/json/csv/pandas datasets without an internet connection **IF** you've the dataset script locally.

Example: 
If you have `datasets/text/text.py` locally, then you can do `load_dataset("./datasets/text", data_files=...)`
