### ISSUE TITLE
How to load data from lakefs

### ISSUE THREAD

**Issue by d710055071** [huggingface/datasets#6478]
My dataset is stored on the company's lakefs server. How can I write code to load the dataset? It would be great if I could provide code examples or provide some references

**Comment by d710055071** [comment]
@mariosasko  hello,
This can achieve and https://huggingface.co/datasets Does the same effect apply to the dataset? For example, downloading while using

**Comment by andimarafioti** [comment]
There is a blogspot from lakes on this topic: https://lakefs.io/blog/data-version-control-hugging-face-datasets/
