### ISSUE TITLE
Cannot import name 'load_dataset' from .... module ‘datasets’

### ISSUE THREAD

**Issue by ciaoyizhen** [huggingface/datasets#6553]
### Describe the bug

use python -m pip install datasets to install

### Steps to reproduce the bug

from datasets import load_dataset

### Expected behavior

it doesn't work

### Environment info

datasets version==2.15.0
python == 3.10.12
linux  version I don't know??

**Comment by ciaoyizhen** [comment]
I don't know  My conpany conputer cannot work. but in my computer, it work?

**Comment by winglian** [comment]
Do you have a folder in your working directory called datasets?
