### ISSUE TITLE
Latest version 2.16.1, when load dataset error occurs. ValueError: BuilderConfig 'allenai--c4' not found. Available: ['default']

### ISSUE THREAD

**Issue by zhulinJulia24** [huggingface/datasets#6559]
### Describe the bug

python script is:
```

from datasets import load_dataset
cache_dir = 'path/to/your/cache/directory'
dataset = load_dataset('allenai/c4','allenai--c4', data_files={'train': 'en/c4-train.00000-of-01024.json.gz'}, split='train',  use_auth_token=False, cache_dir=cache_dir)
```

the script success when datasets version is 2.14.7. 
when using 2.16.1, error occurs
`
ValueError: BuilderConfig 'allenai--c4' not found. Available: ['default']`

### Steps to reproduce the bug

1. pip install datasets==2.16.1
2. run python script:
```

from datasets import load_dataset
cache_dir = 'path/to/your/cache/directory'
dataset = load_dataset('allenai/c4','allenai--c4', data_files={'train': 'en/c4-train.00000-of-01024.json.gz'}, split='train',  use_auth_token=False, cache_dir=cache_dir)
```

### Expected behavior

the dataset should be loaded successful in the latest version. 

### Environment info

datasets 2.16.1

**Comment by lhoestq** [comment]
Hi ! The "allenai--c4" config doesn't exist (this naming schema comes from old versions of `datasets`)

You can load it this way instead:

```python
from datasets import load_dataset
cache_dir = 'path/to/your/cache/directory'
dataset = load_dataset('allenai/c4', data_files={'train': 'en/c4-train.00000-of-01024.json.gz'}, split='train', cache_dir=cache_dir)
```

**Comment by zhulinJulia24** [comment]
> Hi ! The "allenai--c4" config doesn't exist (this naming schema comes from old versions of `datasets`)
> 
> You can load it this way instead:
> 
> ```python
> from datasets import load_dataset
> cache_dir = 'path/to/your/cache/directory'
> dataset = load_dataset('allenai/c4', data_files={'train': 'en/c4-train.00000-of-01024.json.gz'}, split='train', cache_dir=cache_dir)
> ```

thanks, the command run successfully in the latest version

**Comment by Edenzzzz** [comment]
> Hi ! The "allenai--c4" config doesn't exist (this naming schema comes from old versions of `datasets`)
> 
> You can load it this way instead:
> 
> ```python
> from datasets import load_dataset
> cache_dir = 'path/to/your/cache/directory'
> dataset = load_dataset('allenai/c4', data_files={'train': 'en/c4-train.00000-of-01024.json.gz'}, split='train', cache_dir=cache_dir)
> ```

@lhoestq 
In this case, should we traverse through al 1024 json files to load the whole dataset?
Thanks!

**Comment by lhoestq** [comment]
It will only load the first file (`data_files={'train': 'en/c4-train.00000-of-01024.json.gz'}` only mentions one file)

**Comment by Edenzzzz** [comment]
> It will only load the first file (`data_files={'train': 'en/c4-train.00000-of-01024.json.gz'}` only mentions one file)

Then what if we want to load the whole dataset?

**Comment by lhoestq** [comment]
There is a "en" subset that you can load (see the list in the "subset" dropdown at https://huggingface.co/datasets/allenai/c4)

```python
dataset = load_dataset('allenai/c4', 'en', split="train")
```

alternatively you can specify all the the files yourself using a glob pattern (or a list):

```python
dataset = load_dataset('allenai/c4', data_files='en/c4-train.00000-of-*.json.gz', split="train")
```

**Comment by Edenzzzz** [comment]
> There is a "en" subset that you can load (see the list in the "subset" dropdown at https://huggingface.co/datasets/allenai/c4)
> 
> ```python
> dataset = load_dataset('allenai/c4', 'en', split="train")
> ```
> 
> alternatively you can specify all the the files yourself using a glob pattern (or a list):
> 
> ```python
> dataset = load_dataset('allenai/c4', data_files='en/c4-train.00000-of-*.json.gz', split="train")
> ```

Thanks, the second solution works. The first line simply fails due to missing schema specific to this dataset.

**Comment by umarbutler** [comment]
The latest version of `datasets` seems to have broken my dataset for my users (see this Hugging Face issue: https://huggingface.co/datasets/umarbutler/open-australian-legal-corpus/discussions/3). I changed it by renaming my dataset's config to `default` instead of `train` and then updating my dataset card accordingly.
