### ISSUE TITLE
`Dataset.filter` missing `with_rank` parameter

### ISSUE THREAD

**Issue by kopyl** [huggingface/datasets#6564]
### Describe the bug

The issue shall be open: https://github.com/huggingface/datasets/issues/6435

When i try to pass `with_rank` to `Dataset.filter()`, i get this:

`Dataset.filter() got an unexpected keyword argument 'with_rank'`

### Steps to reproduce the bug

Run notebook:

https://colab.research.google.com/drive/1WUNKph8BdP0on5ve3gQnh_PE0cFLQqTn?usp=sharing

### Expected behavior

Should work?

### Environment info

NVIDIA RTX 4090

**Comment by mariosasko** [comment]
Thanks for reporting! I've opened a PR with a fix

**Comment by kopyl** [comment]
@mariosasko thank you very much :)
