### ISSUE TITLE
No online docs for 2.16 release

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#6570]
We do not have the online docs for the latest minor release 2.16 (2.16.0 nor 2.16.1).

In the online docs, the latest version appearing is 2.15.0: https://huggingface.co/docs/datasets/index

![Screenshot from 2024-01-09 08-43-08](https://github.com/huggingface/datasets/assets/8515462/83613222-867f-41f4-8833-7a4a76582f44)

**Comment by lhoestq** [comment]
Though the `build / build_main_documentation` CI job ran for 2.16.0: https://github.com/huggingface/datasets/actions/runs/7300836845/job/19896275099 🤔

**Comment by albertvillanova** [comment]
Yes, I saw it. Maybe @mishig25 can give us some hint...

**Comment by mishig25** [comment]
fixed https://huggingface.co/docs/datasets/v2.16.0/en/index

**Comment by albertvillanova** [comment]
Still missing 2.16.1.

**Comment by mishig25** [comment]
> Still missing 2.16.1.

re-running the doc-buld job for the missing ones should fix

**Comment by albertvillanova** [comment]
Re-running the job for the 2.16.1 release: https://github.com/huggingface/datasets/actions/runs/7365231552

**Comment by albertvillanova** [comment]
Fixed for 2.16.1: https://huggingface.co/docs/datasets/v2.16.1/en/index
