### ISSUE TITLE
While importing load_dataset from datasets 

### ISSUE THREAD

**Issue by Era-cell** [huggingface/datasets#6618]
### Describe the bug

cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' this is the error i received

### Steps to reproduce the bug

from datasets import load_dataset

### Expected behavior

No errors

### Environment info

python 3.11.5

**Comment by mariosasko** [comment]
Hi! Can you please share the error's stack trace so we can see where it comes from?

**Comment by albertvillanova** [comment]
We cannot reproduce the issue and we do not have enough information: environment info (need to run `datasets-cli env`), stack trace,...

I am closing the issue. Feel free to reopen it (with additional information) if the problem persists.

**Comment by Era-cell** [comment]
Yeah 👍

**Comment by TongDaxia** [comment]
Please downgrade the version of urllib3 if you have the same issue:

!pip install urllib3==1.25.11

**Comment by treya-lin** [comment]
> Please downgrade the version of urllib3 if you have the same issue:
> 
> !pip install urllib3==1.25.11

This worked for me. Thanks.

I use python 3.11 and datasets==2.20.0. Downgrading urllib3 to 1.25.11 worked in my case.
