### ISSUE TITLE
Release not pushed to conda channel

### ISSUE THREAD

**Issue by atulsaurav** [huggingface/datasets#6657]
### Describe the bug

The github actions step to publish the release 2.17.0 to conda channel has failed due to expired token. Can some one please update the anaconda token rerun the failed action? @albertvillanova ?
 
![image](https://github.com/huggingface/datasets/assets/7138162/1b56ad3d-7643-4778-9cce-4bf531717700)

### Steps to reproduce the bug

Please see this actions [link](https://github.com/huggingface/datasets/actions/runs/7842473662)

### Expected behavior

The action runs successfully and the latest release is pushed to HuggingFace conda channel

### Environment info

Not applicable.

**Comment by albertvillanova** [comment]
Thanks for reporting, @atulsaurav.

We are investigating the issue.

**Comment by albertvillanova** [comment]
I can't fix this issue because I do not appear as a team member of the huggingface datasets project: https://anaconda.org/huggingface/datasets

@lhoestq could you please add `datasets` team members to the corresponding Anaconda project?

**Comment by lhoestq** [comment]
I think @LysandreJik has access ?

**Comment by lhoestq** [comment]
FYI it failed for 2.18.0 too: https://github.com/huggingface/datasets/actions/runs/8117132330/job/22188677936

**Comment by lhoestq** [comment]
We updated the token and I re-ran the conda releases :)
