### ISSUE TITLE
`write_examples_on_file` and `write_batch` are broken in `ArrowWriter`

### ISSUE THREAD

**Issue by bryant1410** [huggingface/datasets#6663]
### Describe the bug

`write_examples_on_file` and `write_batch` are broken in `ArrowWriter` since #6636. The order between the columns and the schema is not preserved anymore. So these functions don't work anymore unless the order happens to align well.

### Steps to reproduce the bug

Try to do `write_batch` with anything that has many columns, and it's likely to break.

### Expected behavior

I expect these functions to work, instead of it trying to cast a column to its incorrect type.

### Environment info

- `datasets` version: 2.17.0
- Platform: Linux-5.15.0-1040-aws-x86_64-with-glibc2.35
- Python version: 3.10.13
- `huggingface_hub` version: 0.19.4
- PyArrow version: 15.0.0
- Pandas version: 2.2.0
- `fsspec` version: 2023.10.0

**Comment by mariosasko** [comment]
Thanks for reporting! I've left some comments on the PR on how to fix this recent change rather than reverting it.

**Comment by bryant1410** [comment]
> Thanks for reporting! I've left some comments on the PR on how to fix this recent change rather than reverting it.

I feel that'd be good, but it'd be great to release a hotfix ASAP (a revert is a fast thing to do) so people can continue using this library and then focus on still applying the improvement.

**Comment by albertvillanova** [comment]
Fixed by #6664
