### ISSUE TITLE
 Depprcated Overview.ipynb Link to new Quickstart Notebook invalid

### ISSUE THREAD

**Issue by Codeblockz** [huggingface/datasets#6674]
### Describe the bug

For the dreprecated notebook found  [here](https://github.com/huggingface/datasets/blob/main/notebooks/Overview.ipynb). The link to the new notebook is broken. 

### Steps to reproduce the bug

Click the [Quickstart notebook](https://github.com/huggingface/notebooks/blob/main/datasets_doc/quickstart.ipynb) link in the notebook.

### Expected behavior

I believe is it suposed to link [here](https://github.com/huggingface/notebooks/blob/main/datasets_doc/en/quickstart.ipynb). That is mentioned in the readme.

### Environment info

Colab

**Comment by mariosasko** [comment]
Good catch! Feel free to open a PR to fix the link.
