### ISSUE TITLE
How to skip a example when running dataset.map

### ISSUE THREAD

**Issue by xixiaoyao** [huggingface/datasets#669]
in processing func, I process examples and detect some invalid examples, which I did not want it to be added into train dataset. However I did not find how to skip this recognized invalid example when doing dataset.map.

**Comment by thomwolf** [comment]
Hi @xixiaoyao,
Depending on what you want to do you can:
- use a first step of `filter` to filter out the invalid examples: https://huggingface.co/docs/datasets/processing.html#filtering-rows-select-and-filter
- or directly detect the invalid examples inside the callable used with `map` and return them unchanged or even remove them at the same time if you are using `map` in batched mode: https://huggingface.co/docs/datasets/processing.html#augmenting-the-dataset

**Comment by lhoestq** [comment]
Closing this one.
Feel free to re-open if you have other questions

**Comment by plamb-viso** [comment]
Letting finders-of-this-thread know that the new link is: https://huggingface.co/docs/datasets/process#data-augmentation
