### ISSUE TITLE
load_dataset() does not support tsv

### ISSUE THREAD

**Issue by dipsivenkatesh** [huggingface/datasets#6691]
### Feature request

the load_dataset() for local functions support file types like csv, json etc but not of type tsv (tab separated values).

### Motivation

cant easily load files of type tsv, have to convert them to another type like csv then load

### Your contribution

Can try by raising a PR with a little help, currently went through the code but didn't fully understand

**Comment by harsh1504660** [comment]
#self-assign

**Comment by albertvillanova** [comment]
Hi @harsh1504660,

Please note that this functionality is already implemented. Our CSV builder uses `pandas.read_csv` under the hood, and you can pass the parameter `delimiter="\t"` to read TSV files.

See the list of CSV config parameters in our docs: https://huggingface.co/docs/datasets/package_reference/loading_methods#datasets.packaged_modules.csv.CsvConfig
