### ISSUE TITLE
blog_authorship_corpus crashed

### ISSUE THREAD

**Issue by Moshiii** [huggingface/datasets#673]
This is just to report that When I pick blog_authorship_corpus in 
https://huggingface.co/nlp/viewer/?dataset=blog_authorship_corpus
I get this:
![image](https://user-images.githubusercontent.com/7553188/94349542-4364f300-0013-11eb-897d-b25660a449f0.png)

**Comment by lhoestq** [comment]
Thanks for reporting !
We'll free some memory
