### ISSUE TITLE
Small typo on the documentation

### ISSUE THREAD

**Issue by fostiropoulos** [huggingface/datasets#6755]
### Describe the bug

There is a small typo on https://github.com/huggingface/datasets/blob/d5468836fe94e8be1ae093397dd43d4a2503b926/src/datasets/dataset_dict.py#L938

It should be `caching is enabled`. 

### Steps to reproduce the bug

Please visit 

https://github.com/huggingface/datasets/blob/d5468836fe94e8be1ae093397dd43d4a2503b926/src/datasets/dataset_dict.py#L938

### Expected behavior

`caching is enabled`

### Environment info

- `datasets` version: 2.17.1
- Platform: Linux-5.15.0-101-generic-x86_64-with-glibc2.35
- Python version: 3.11.7
- `huggingface_hub` version: 0.20.3
- PyArrow version: 15.0.0
- Pandas version: 2.2.1
- `fsspec` version: 2023.10.0

**Comment by mariosasko** [comment]
Thanks for reporting @fostiropoulos! I've edited your comment to fix the link to the problematic line.

**Comment by JINO-ROHIT** [comment]
@mariosasko can i take this up?

**Comment by JINO-ROHIT** [comment]
#self-assign
