### ISSUE TITLE
Allow deleting a subset/config from a no-script dataset

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#6810]
As proposed by @BramVanroy, it would be neat to have this functionality through the API.

**Comment by mariosasko** [comment]
Probably best to implement this as a CLI command?

**Comment by albertvillanova** [comment]
Thanks for your comment, @mariosasko. Or maybe both (in Python and as CLI command)? The Python command would be just the reverse of `push_to_hub`...

I am working on a draft implementation, so we can discuss about the API and UX.

**Comment by lmmx** [comment]
2nd time I've come here in the past few days so for reference this doesn't work for me at the moment (token auth error despite successful `whoami` and all auths applied) so I resorted to [reverting](https://discuss.huggingface.co/t/how-to-revert-to-an-earlier-commit-on-a-repo/65735/2) to a previous commit (after installing git lfs)
