### ISSUE TITLE
Dataset browser url is still https://huggingface.co/nlp/viewer/

### ISSUE THREAD

**Issue by jarednielsen** [huggingface/datasets#686]
Might be worth updating to https://huggingface.co/datasets/viewer/

**Comment by julien-c** [comment]
Yes! might do it with @srush one of these days. Hopefully it won't break too many links (we can always redirect from old url to new)

**Comment by julien-c** [comment]
This was fixed but forgot to close the issue. cc @lhoestq @yjernite 

Thanks @jarednielsen!
