### ISSUE TITLE
[WebDataset] KeyError with user-defined `Features` when a field is missing in an example

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets#6900]
reported at https://huggingface.co/datasets/ProGamerGov/synthetic-dataset-1m-dalle3-high-quality-captions/discussions/1

```
File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/packaged_modules/webdataset/webdataset.py", line 109, in _generate_examples
    example[field_name] = {"path": example["__key__"] + "." + field_name, "bytes": example[field_name]}
```

**Comment by ProGamerGov** [comment]
@lhoestq How difficult of fix is this?

**Comment by lhoestq** [comment]
It shouldn't be difficult, I think it's just a matter of adding the missing fields from `self.config.features` in `example` here:

https://github.com/huggingface/datasets/blob/768cb35ede5a6c35fa7545aa3671f3e321c96440/src/datasets/packaged_modules/webdataset/webdataset.py#L113-L116

**Comment by lhoestq** [comment]
Yup this is the solution !

```python
            for field_name in all_field_names:
                if field_name not in example:
                    example[field_name] = None
```

**Comment by ProGamerGov** [comment]
@lhoestq Awesome, thanks! I made a PR with the fixes
