### ISSUE TITLE
irc_disentangle - Issue with splitting data

### ISSUE THREAD

**Issue by eor51355** [huggingface/datasets#6906]
### Describe the bug

I am trying to access your database through python using "datasets.load_dataset("irc_disentangle")" and I am getting this error message:

ValueError: Instruction "train" corresponds to no data!

### Steps to reproduce the bug

import datasets
ds = datasets.load_dataset('irc_disentangle')
ds

### Expected behavior

The data is supposed to load into ds and be accessable as such:
ds['train'][1050], ds['train'][1055]

### Environment info

I tired Python 3.12 and 3.10

**Comment by cybest0608** [comment]
I add a "streaming=True" after the name of the dataset, and it works.....hope it can help you

**Comment by cybest0608** [comment]
> I add a "streaming=True" after the name of the dataset, and it works.....hope it can help you

And if you install the version datasets==2.15.0, this bug will not happen. I don't know why, but all of them works

**Comment by eor51355** [comment]
Thank you I will try this out!

**Comment by cybest0608** [comment]
I still find out that there are some strange bug in v2.15.0 of datasets. it seems like that the *.arrow file cannot be established. it may be an index of the subsets. well I still try to debug it. but, one of the most efficient way may be using the google colab to build this index in the ~/huggingface/datasets, and than download them to replace the local file.....lol......it works!

**Comment by eor51355** [comment]
Yeah I did try what you suggested and it didn’t work. I was able to get it
on a local from someone who access the dataset in the past. Let me know
when you end up fixing this bug.

**Comment by albertvillanova** [comment]
Could you please provide more information, as required by the Bug template: https://github.com/huggingface/datasets/issues/new?assignees=&labels=&projects=&template=bug-report.yml

Without all that information, it is very difficult for us to understand the underlying issue and to give a pertinent answer.

What are the versions of the libraries you are using? Datasets, pyarrow, fsspec,...
> Environment info
> Please share your environemnt info with us. You can run the command datasets-cli env and copy-paste its output below.

What is the output you get after executing these code lines?
```python
import datasets
ds = datasets.load_dataset('irc_disentangle')
ds
```

**Comment by albertvillanova** [comment]
We have made the following fixes:
- [Fix source data URL](https://huggingface.co/datasets/jkkummerfeld/irc_disentangle/discussions/4)
- [Convert dataset to Parquet](https://huggingface.co/datasets/jkkummerfeld/irc_disentangle/discussions/5)

**Comment by eor51355** [comment]
Thank you for the fixes. Sorry I lost this conversation in my inbox.
