### ISSUE TITLE
Add UI filter to filter datasets based on task

### ISSUE THREAD

**Issue by praateekmahajan** [huggingface/datasets#691]
This is great work, so huge shoutout to contributors and huggingface.

The [/nlp/viewer](https://huggingface.co/nlp/viewer/) is great and the [/datasets](https://huggingface.co/datasets) page is great. I was wondering if in both or either places we can have a filter that selects if a dataset is good for the following tasks (non exhaustive list)

- Classification
	- Multi label
	- Multi class
- Q&A
- Summarization
- Translation

I believe this feature might have some value, for folks trying to find datasets for a particular task, and then testing their model capabilities.

Thank you :)

**Comment by albertvillanova** [comment]
Already supported.
