### ISSUE TITLE
Add option to disable progress bar when reading a dataset ("Loading dataset from disk")

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/datasets#7030]
### Feature request

Add an option in load_from_disk to disable the progress bar even if the number of files is larger than 16.

### Motivation

I am reading a lot of datasets that it creates lots of logs.

<img width="1432" alt="image" src="https://github.com/huggingface/datasets/assets/57996478/8d4bbf03-6b89-44b6-937c-932f01b4eb2a">

### Your contribution

Seems like an easy fix to make.  I can create a PR if necessary.

**Comment by Dref360** [comment]
You can disable progress bars for all of `datasets` with `disable_progress_bars`. [Link](https://huggingface.co/docs/datasets/en/package_reference/utilities#datasets.enable_progress_bars)

So you could do something like:

```python
from datasets import load_from_disk, enable_progress_bars, disable_progress_bars

disable_progress_bars()
# Your code
load_from_disk(....)

enable_progress_bars()
```

**Comment by yuvalkirstain** [comment]
Thank you! Closing the issue.
