### ISSUE TITLE
ImportError: numpy.core.multiarray when using `filter`

### ISSUE THREAD

**Issue by kamilakesbi** [huggingface/datasets#7048]
### Describe the bug

I can't apply the filter method on my dataset. 

### Steps to reproduce the bug

The following snippet generates a bug: 

```python
from datasets import load_dataset 

ami = load_dataset('kamilakesbi/ami', 'ihm')

ami['train'].filter(
    lambda example: example["file_name"] == 'EN2001a'
)
```

I get the following error: 

`ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).`

### Expected behavior

It should work properly! 

### Environment info

- `datasets` version: 2.20.0
- Platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- `huggingface_hub` version: 0.23.4
- PyArrow version: 16.1.0
- Pandas version: 2.2.2
- `fsspec` version: 2024.5.0

**Comment by albertvillanova** [comment]
Could you please check your `numpy` version?

**Comment by kamilakesbi** [comment]
I got this issue while using numpy version 2.0. 

I solved it by switching back to numpy 1.26.0 :)

**Comment by albertvillanova** [comment]
We recently added support for numpy 2.0, but it is not released yet.

**Comment by kamilakesbi** [comment]
Ok I see, thanks! I think we can close this issue for now as switching back to version 1.26.0 solves the problem :)
