### ISSUE TITLE
HfHubHTTPError: 500 Server Error: Internal Server Error for url:

### ISSUE THREAD

**Issue by neoneye** [huggingface/datasets#7079]
### Describe the bug

newly uploaded datasets, since yesterday, yields an error.

old datasets, works fine.

Seems like the datasets api server returns a 500

I'm getting the same error, when I invoke `load_dataset` with my dataset.

Long discussion about it here, but I'm not sure anyone from huggingface have seen it.
https://discuss.huggingface.co/t/hfhubhttperror-500-server-error-internal-server-error-for-url/99580/1

### Steps to reproduce the bug

this api url: 

https://huggingface.co/api/datasets/neoneye/simon-arc-shape-v4-rev3

respond with:

```
{"error":"Internal Error - We're working hard to fix this as soon as possible!"}
```

### Expected behavior

return no error with newer datasets.

With older datasets I can load the datasets fine.

### Environment info

# Browser
When I access the api in the browser:
https://huggingface.co/api/datasets/neoneye/simon-arc-shape-v4-rev3

```
{"error":"Internal Error - We're working hard to fix this as soon as possible!"}
```

### Request headers

```
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding	gzip, deflate, br, zstd
Accept-Language	en-US,en;q=0.5
Connection	keep-alive
Host	huggingface.co
Priority	u=1
Sec-Fetch-Dest	document
Sec-Fetch-Mode	navigate
Sec-Fetch-Site	cross-site
Upgrade-Insecure-Requests	1
User-Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
```

### Response headers

```
X-Firefox-Spdy	h2
access-control-allow-origin	https://huggingface.co
access-control-expose-headers	X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range
content-length	80
content-type	application/json; charset=utf-8
cross-origin-opener-policy	same-origin
date	Fri, 26 Jul 2024 19:09:45 GMT
etag	W/"50-9qrwU+BNI4SD0Fe32p/nofkmv0c"
referrer-policy	strict-origin-when-cross-origin
vary	Origin
via	1.1 1624c79cd07e6098196697a6a7907e4a.cloudfront.net (CloudFront)
x-amz-cf-id	SP8E7n5qRaP6i9c9G83dNAiOzJBU4GXSrDRAcVNTomY895K35H0nJQ==
x-amz-cf-pop	CPH50-C1
x-cache	Error from cloudfront
x-error-message	Internal Error - We're working hard to fix this as soon as possible!
x-powered-by	huggingface-moon
x-request-id	Root=1-66a3f479-026417465ef42f49349fdca1
```

**Comment by PosoSAgapo** [comment]
same issue here.

**Comment by ACMCMC** [comment]
Also impacted by this issue in many of my datasets (though not all) - this seems to affect datasets that have been updated recently:
- https://huggingface.co/api/datasets/acmc/cheat_reduced
- https://huggingface.co/api/datasets/acmc/ghostbuster_reuter_reduced
- https://huggingface.co/api/datasets/acmc/ghostbuster_wp_reduced
- https://huggingface.co/api/datasets/acmc/ghostbuster_essay_reduced

**Comment by codeboy5** [comment]
Hey how to download these datasets using git cloning?

**Comment by neoneye** [comment]
Also reported here
https://github.com/huggingface/huggingface_hub/issues/2425

**Comment by nedith** [comment]
I have been getting the same error for the past 8 hours as well

**Comment by daniel-dona** [comment]
Same error since yesterday, fails on any new dataset created

**Comment by scottsuk0306** [comment]
Same here. I cannot download the HelpSteer2 dataset: https://huggingface.co/datasets/nvidia/HelpSteer2 which has been uploaded about a month ago

**Comment by ACMCMC** [comment]
> Hey how to download these datasets using git cloning?

You'll find a guide [here](https://huggingface.co/docs/hub/en/datasets-downloading) 👍🏻

**Comment by ooolivia2333** [comment]
Same here for imdb dataset

**Comment by iakovialexiou** [comment]
It also happens with this dataset: https://huggingface.co/datasets/ylacombe/jenny-tts-6h-tagged

**Comment by bobox2997** [comment]
same here for all datsets in the sentence-tramsformers repo and related collections.

same issue with dataset that i recently uploaded on my repo.
seems that the upload date of the datset is not relevat (getting this issue with both old datasets and newer ones)

for some reason, i was able to get the dataset by turning it private and accessing it with the id token (accessing it as public while providing the token doesn not work)..... but i can say if that is just a random coincidence.

seems not much deterministic, for a specific dataset (sentence-transformer nq ) , that was "down" since some hours , worked for like 5-10 minutes, then stopped again

**Comment by lhoestq** [comment]
we're working on a fix !

**Comment by lhoestq** [comment]
We fixed the issue, you can load datasets again, sorry for the inconvenience !

**Comment by neoneye** [comment]
I can confirm, it's working now. I can load the dataset, yay. Thank you @lhoestq

**Comment by bobox2997** [comment]
@lhoestq thank you so much!

**Comment by lhoestq** [comment]
Thanks for reporting, we are investigating !
