### ISSUE TITLE
Adding pseudo-labels to datasets

### ISSUE THREAD

**Issue by sshleifer** [huggingface/datasets#723]
I recently [uploaded pseudo-labels](https://github.com/huggingface/transformers/blob/master/examples/seq2seq/precomputed_pseudo_labels.md) for CNN/DM, XSUM and WMT16-en-ro to s3, and thom mentioned I should add them to this repo.
Since pseudo-labels are just a large model's generations on an existing dataset, what is the right way to structure this contribution.
I read https://huggingface.co/docs/datasets/add_dataset.html, but it doesn't really cover this type of contribution.

I could, for example, make a new directory, `xsum_bart_pseudolabels` for each set of pseudolabels or add some sort of parametrization to `xsum.py`: https://github.com/huggingface/datasets/blob/5f4c6e830f603830117877b8990a0e65a2386aa6/datasets/xsum/xsum.py

What do you think @lhoestq ?

**Comment by lhoestq** [comment]
Nice ! :)
It's indeed the first time we have such contributions so we'll have to figure out the appropriate way to integrate them.
Could you add details on what they could be used for ?

**Comment by sshleifer** [comment]
They can be used as training data for a smaller model.

**Comment by thomwolf** [comment]
Sounds just like a regular dataset to me then, no?

**Comment by lhoestq** [comment]
A new configuration for those datasets should do the job then.
Note that until now datasets like xsum only had one configuration. It means that users didn't have to specify the configuration name when loading the dataset. If we add new configs, users that update the lib will have to update their code to specify the default/standard configuration name (not the one with pseudo labels).

**Comment by thomwolf** [comment]
Could also be a `user-namespace` datasets maybe?

**Comment by lhoestq** [comment]
Oh yes why not. I'm more in favor for this actually since pseudo labels are things that users (not dataset authors) can compute by themselves and share with the community

**Comment by sshleifer** [comment]
![image](https://user-images.githubusercontent.com/6045025/96045248-b528a380-0e3f-11eb-9124-bd55afa031bb.png)

I assume I should (for example) rename the xsum dir, change the URL, and put the modified dir somewhere in S3?

**Comment by lhoestq** [comment]
You can use the `datasets-cli` to upload the folder with your version of xsum with the pseudo labels.

```
datasets-cli upload_dataset path/to/xsum
```
