### ISSUE TITLE
Clicking on a metric in the search page points to datasets page giving "Missing dataset" warning

### ISSUE THREAD

**Issue by ogabrielluiz** [huggingface/datasets#752]
Hi! Sorry if this isn't the right place to talk about the website, I just didn't exactly where to write this.

Searching a metric in https://huggingface.co/metrics gives the right results but clicking on a metric (E.g ROUGE) points to https://huggingface.co/datasets/rouge. Clicking on a metric without searching points to the right page.

Thanks for all the great work!

**Comment by julien-c** [comment]
Thanks for the report, can reproduce. Will fix

**Comment by julien-c** [comment]
Fixed now @ogabrielluiz
