### ISSUE TITLE
[GEM] add DART data-to-text generation dataset

### ISSUE THREAD

**Issue by yjernite** [huggingface/datasets#766]
## Adding a Dataset
- **Name:** DART
- **Description:** DART consists of 82,191 examples across different domains with each input being a semantic RDF triple set derived from data records in tables and the tree ontology of the schema, annotated with sentence descriptions that cover all facts in the triple set.
- **Paper:** https://arxiv.org/abs/2007.02871v1
- **Data:** https://github.com/Yale-LILY/dart
- **Motivation:** the dataset will likely be included in the GEM benchmark

Instructions to add a new dataset can be found [here](https://huggingface.co/docs/datasets/share_dataset.html).

**Comment by ghomasHudson** [comment]
Is this a duplicate of #924 ?

**Comment by yjernite** [comment]
Yup, closing! Haven't been keeping track of the solved issues during the sprint.
