### ISSUE TITLE
Adding CC-100: Monolingual Datasets from Web Crawl Data

### ISSUE THREAD

**Issue by yjernite** [huggingface/datasets#773]
## Adding a Dataset
- **Name:** CC-100: Monolingual Datasets from Web Crawl Data
- **Description:** https://twitter.com/alex_conneau/status/1321507120848625665
- **Paper:** https://arxiv.org/abs/1911.02116
- **Data:** http://data.statmt.org/cc-100/
- **Motivation:** A large scale multi-lingual language modeling dataset. Text is de-duplicated and filtered by how "Wikipedia-like" it is, hopefully helping avoid some of the worst parts of the common crawl.

Instructions to add a new dataset can be found [here](https://huggingface.co/docs/datasets/share_dataset.html).

**Comment by yjernite** [comment]
cc @aconneau ;)

**Comment by AnzorGozalishvili** [comment]
These dataset files are no longer available.  https://data.statmt.org/cc-100/ files provided in this link are no longer available. Can anybody fix that issue?
@abhishekkrthakur @yjernite

**Comment by lhoestq** [comment]
Hi ! Can you open an issue to report this problem ? This will help keep track of the fix :)

**Comment by AnzorGozalishvili** [comment]
Ok
