### ISSUE TITLE
Error running pip install -e ".[dev]" on MacOS 10.13.6: faiss/python does not exist

### ISSUE THREAD

**Issue by shawwn** [huggingface/datasets#790]
I was following along with https://huggingface.co/docs/datasets/share_dataset.html#adding-tests-and-metadata-to-the-dataset when I ran into this error.

```sh
git clone https://github.com/huggingface/datasets
cd datasets
virtualenv venv -p python3 --system-site-packages
source venv/bin/activate
pip install -e ".[dev]"
```

![image](https://user-images.githubusercontent.com/59632/97868518-72871800-1cd5-11eb-9cd2-37d4e9d20b39.png)

![image](https://user-images.githubusercontent.com/59632/97868592-977b8b00-1cd5-11eb-8f3c-0c409616149c.png)

Python 3.7.7

**Comment by lhoestq** [comment]
I saw that `faiss-cpu` 1.6.4.post2 was released recently to fix the installation on macos. It should work now

**Comment by lhoestq** [comment]
Closing this one.
Feel free to re-open if you still have issues
