### ISSUE TITLE
Descriptions of raw and processed versions of wikitext are inverted

### ISSUE THREAD

**Issue by fraboniface** [huggingface/datasets#795]
Nothing of importance, but it looks like the descriptions of wikitext-n-v1 and wikitext-n-raw-v1 are inverted for both n=2 and n=103. I just verified by loading them and the `<unk>` tokens are present in the non-raw versions, which confirms that it's a mere inversion of the descriptions and not of the datasets themselves.

Also it would be nice if those descriptions appeared in the dataset explorer.

https://github.com/huggingface/datasets/blob/87bd0864845ea0a1dd7167918dc5f341bf807bd3/datasets/wikitext/wikitext.py#L52

**Comment by lhoestq** [comment]
Yes indeed ! Thanks for reporting

**Comment by albertvillanova** [comment]
Fixed by:
- #3241
