### ISSUE TITLE
Token classification labels are strings and we don't have the list of labels

### ISSUE THREAD

**Issue by sgugger** [huggingface/datasets#797]
Not sure if this is an issue we want to fix or not, putting it here so it's not forgotten. Right now, in token classification datasets, the labels for NER, POS and the likes are typed as `Sequence` of `strings`, which is wrong in my opinion. These should be `Sequence` of `ClassLabel` or some types that gives easy access to the underlying labels.

The main problem for preprocessing those datasets is that the list of possible labels is not stored inside the `Dataset` object which makes converting the labels to IDs quite difficult (you either have to know the list of labels in advance or run a full pass through the dataset to get the list of labels, the `unique` method being useless with the type `Sequence[str]`).

**Comment by thomwolf** [comment]
Indeed. Pinging @stefan-it here if he want to give an expert opinion :)

**Comment by thomwolf** [comment]
Related is https://github.com/huggingface/datasets/pull/636

**Comment by stefan-it** [comment]
Should definitely be a ClassLabel 👍

**Comment by albertvillanova** [comment]
Already done.
