### ISSUE TITLE
How to join two datasets?

### ISSUE THREAD

**Issue by shangw-nvidia** [huggingface/datasets#801]
Hi,

I'm wondering if it's possible to join two (preprocessed) datasets with the same number of rows but different labels? 

I'm currently trying to create paired sentences for BERT from `wikipedia/'20200501.en`, and I couldn't figure out a way to create a paired sentence using `.map()` where the second sentence is **not** the next sentence (i.e., from a different article) of the first sentence.

Thanks!

**Comment by rabeehkarimimahabadi** [comment]
Hi this is also my question. thanks

**Comment by lhoestq** [comment]
Hi ! Currently the only way to add new fields to a dataset is by using `.map` and picking items from the other dataset

**Comment by lhoestq** [comment]
Closing this one. Feel free to re-open if you have other questions about this issue.

Also linking another discussion about joining datasets: #853
