### ISSUE TITLE
nlp viewer error

### ISSUE THREAD

**Issue by jc-hou** [huggingface/datasets#811]
Hello, 
when I select amazon_us_reviews in nlp viewer, it shows error.
https://huggingface.co/nlp/viewer/?dataset=amazon_us_reviews
![image](https://user-images.githubusercontent.com/30210529/98447334-4aa81200-2124-11eb-9dca-82c3ab34ccc2.png)

**Comment by jc-hou** [comment]
and also for 'blog_authorship_corpus'
https://huggingface.co/nlp/viewer/?dataset=blog_authorship_corpus
![image](https://user-images.githubusercontent.com/30210529/98557329-5c182800-22a4-11eb-9b01-5b910fb8fcd4.png)

**Comment by jc-hou** [comment]
Is this the problem of my local computer or ??

**Comment by albertvillanova** [comment]
Already fixed.

**Comment by albertvillanova** [comment]
Related to:
- #673
