### ISSUE TITLE
How to implement DistributedSampler with datasets 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/datasets#813]
Hi,
I am using your datasets to define my dataloaders, and I am training finetune_trainer.py in huggingface repo on them.
I need a distributedSampler to be able to train the models on TPUs being able to distribute the load across the TPU cores. Could you tell me how I can implement the distribued sampler when using datasets in which datasets are iterative? To give you more context, I have multiple of datasets and I need to write sampler for this case. thanks.

**Comment by rabeehkarimimahabadi** [comment]
Hi Apparently I need to shard the data and give one host a chunk, could you provide me please with examples on how to do it? I want to use it jointly with finetune_trainer.py in huggingface repo seq2seq examples. thanks.

**Comment by JulesBelveze** [comment]
Hey @rabeehkarimimahabadi I'm actually looking for the same feature. Did you manage to get somewhere?

**Comment by mariosasko** [comment]
Hi! I think you can use the `accelerate` library for that, which implements distributed sampling.
