### ISSUE TITLE
[GEM] add ToTTo Table-to-text dataset

### ISSUE THREAD

**Issue by yjernite** [huggingface/datasets#830]
## Adding a Dataset
- **Name:** ToTTo
- **Description:** ToTTo is an open-domain English table-to-text dataset with over 120,000 training examples that proposes a controlled generation task: given a Wikipedia table and a set of highlighted table cells, produce a one-sentence description.
- **Paper:** https://arxiv.org/abs/2004.14373
- **Data:** https://github.com/google-research-datasets/totto
- **Motivation:** Included in the GEM shared task

Instructions to add a new dataset can be found [here](https://huggingface.co/docs/datasets/share_dataset.html).

**Comment by abhishekkrthakur** [comment]
closed via #1098
