### ISSUE TITLE
Add HoVer multi-hop fact verification dataset

### ISSUE THREAD

**Issue by yjernite** [huggingface/datasets#846]
## Adding a Dataset
- **Name:** HoVer
- **Description:** https://twitter.com/YichenJiang9/status/1326954363806429186 contains 20K claim verification examples
- **Paper:** https://arxiv.org/abs/2011.03088
- **Data:** https://hover-nlp.github.io/
- **Motivation:** There are still few multi-hop information extraction benchmarks (HotpotQA, which dataset wase based off, notwithstanding)

Instructions to add a new dataset can be found [here](https://huggingface.co/docs/datasets/share_dataset.html).

**Comment by tenjjn** [comment]
Hi I'm new but wanted to contribute. Has anyone already taken this problem and do you think it is suitable for newbies?

**Comment by yjernite** [comment]
Hi @tenjjin! This dataset is still up for grabs! Here's the link with the guide to add it. You should play around with the library first (download and look at a few datasets), then follow the steps here:

https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md

**Comment by abhishekkrthakur** [comment]
Closed by #1399
