### ISSUE TITLE
concatenate_datasets support axis=0 or 1 ？

### ISSUE THREAD

**Issue by renqingcolin** [huggingface/datasets#853]
I want to achieve the following result
![image](https://user-images.githubusercontent.com/12437751/99207426-f0c8db80-27f8-11eb-820a-4d9f7287b742.png)

**Comment by lhoestq** [comment]
Unfortunately `concatenate_datasets` only supports concatenating the rows, while what you want to achieve is concatenate the columns.
Currently to add more columns to a dataset, one must use `map`.
What you can do is somehting like this:
```python
# suppose you have datasets d1, d2, d3
def add_columns(example, index):
    example.update(d2[index])
    example.update(d3[index])
    return example

full_dataset = d1.map(add_columns, with_indices=True)
```

**Comment by lhoestq** [comment]
Closing this one, feel free to re-open if you have other questions about this issue

**Comment by thomwolf** [comment]
That's not really difficult to add, though, no?
I think it can be done without copy.
Maybe let's add it to the roadmap?

**Comment by lhoestq** [comment]
Actually it's doable but requires to update the `Dataset._data_files` schéma to support this.
I'm re-opening this since we may want to add this in the future

**Comment by KMFODA** [comment]
Hi @lhoestq, I would love to help and add this feature if still needed. My plan is to add an axis variable in the `concatenate_datasets` function in `arrow_dataset.py` and when that is set to 1 concatenate columns instead of rows.

**Comment by lhoestq** [comment]
Hi ! I would love to see this feature implemented as well :) Thank you for proposing your help !

Here is a few things about the current implementation:
- A dataset object is a wrapper of one `pyarrow.Table` that contains the data
- Pyarrow offers an API that allows to transform Table objects. For example there are functions like `concat_tables`, `Table.rename_columns`, `Table.add_column` etc.

Therefore adding columns from another dataset is possible thanks to the pyarrow API and in particular `Table.add_column` :) 

However this breaks some features we have regarding pickle. A dataset object can be pickled and unpickled without loading all the data in memory. It is useful for multiprocessing for example. Pickling a dataset object is possible thanks to the `Dataset._data_files` which defines the list of arrow files that will be used to form the final Table (basically all the data from each files are concatenated on axis 0).

Therefore to be able to add columns to a Dataset and still be able to work with it in a multiprocessing setup, we need to extend this last aspect to be able to reconstruct a Table object from multiple arrow files that are combined in both axis 0 and 1. Currently this reconstruction mechanism only supports axis 0.

I'm sure we can figure something out that enables users to add columns from another dataset while keeping the multiprocessing support.

**Comment by albertvillanova** [comment]
@lhoestq, we have two Pull Requests to implement:
- Dataset.add_item: #1870
- Dataset.add_column: #2145
which add a single row or column, repectively.

The request here is to implement the concatenation of *multiple* rows/columns. Am I right?

We should agree on the API:
- `concatenate_datasets` with `axis`?
- other Dataset method name?

**Comment by albertvillanova** [comment]
@lhoestq I think I guessed your suggestions in advance... 😉 #2151

**Comment by lhoestq** [comment]
Cool ! Sorry I missed this one ^^
I'm taking a look ;)
