### ISSUE TITLE
Very slow cold-start

### ISSUE THREAD

**Issue by AmitMY** [huggingface/datasets#885]
Hi,
I expect when importing `datasets` that nothing major happens in the background, and so the import should be insignificant.
When I load a metric, or a dataset, its fine that it takes time.

The following ranges from 3 to 9 seconds:
```
python -m timeit -n 1 -r 1 'from datasets import load_dataset'
```

edit:
sorry for the mis-tag, not sure how I added it.

**Comment by thomwolf** [comment]
Good point!

**Comment by lhoestq** [comment]
Yes indeed. We can probably improve that by using lazy imports

**Comment by lhoestq** [comment]
#1690 added fast start-up of the library
