### ISSUE TITLE
Problem downloading amazon_reviews_multi

### ISSUE THREAD

**Issue by hfawaz** [huggingface/datasets#993]
Thanks for adding the dataset. 
After trying to load the dataset, I am getting the following error: 
`ConnectionError: Couldn't reach https://amazon-reviews-ml.s3-us-west-2.amazonaws.com/json/train/dataset_fr_train.json
`
I used the following code to load the dataset: 
`load_dataset(
            dataset_name,
            "all_languages",
            cache_dir=".data"
        )`

I am using version 1.1.3 of `datasets`

Note that I can perform a successfull `wget https://amazon-reviews-ml.s3-us-west-2.amazonaws.com/json/train/dataset_fr_train.json`

**Comment by yjernite** [comment]
Hi @hfawaz ! This is working fine for me. Is it a repeated occurence? Have you tried from the latest verion?

**Comment by hfawaz** [comment]
Hi, it seems a connection problem. 
Now it says: 
`ConnectionError: Couldn't reach https://amazon-reviews-ml.s3-us-west-2.amazonaws.com/json/train/dataset_ja_train.json`
